/**
 * 图标组合 4/5(Lucide 细线与变体)字形表 —— 自 iconSetTables.ts 拆出
 * (文件规模铁则;主文件持组合 1-3 与解析)。逐键 A≠B,4↔5 切换全表
 * morph;fold 双键不入表(resolve 回 phosphor)。
 */
import {
  AppWindow,
  ArrowDownUp,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  BadgeCheck,
  Bell,
  Binoculars,
  Blocks,
  Bot,
  Bookmark,
  Brain,
  Brush,
  Cable,
  CalendarDays,
  Cast,
  ChevronDown,
  ChevronUp,
  ChevronsDown,
  ChevronsUp,
  CloudUpload,
  Compass,
  Cpu as LCpu,
  Eye as LEye,
  ExternalLink,
  FileDiff,
  FilePlus,
  FilePlus2,
  Flag,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus as LFolderPlus,
  GitBranch,
  GitCompare,
  GitFork,
  GitMerge as LGitMerge,
  Globe,
  GraduationCap as LGraduationCap,
  History,
  House as LHouse,
  Inbox,
  KeyRound,
  Layers,
  LayoutGrid,
  LayoutList,
  List,
  ListChecks,
  ListTodo,
  ListTree,
  Lightbulb as LLightbulb,
  Megaphone as LMegaphone,
  Monitor,
  MonitorPlay,
  Network,
  NotebookPen,
  PanelLeft,
  Palette,
  PenTool,
  Plug,
  Puzzle,
  Radio,
  RefreshCcw,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Rows3,
  Server,
  Settings2,
  ShoppingBag,
  Shuffle,
  SlidersHorizontal,
  Sparkles,
  Split,
  SquareArrowOutUpRight,
  SquareTerminal,
  Star,
  Store,
  Table as LTable,
  Terminal,
  TextQuote,
  UserRound,
  WandSparkles,
  Zap,
} from "lucide";
import type { IconNode as LucideNode } from "lucide";
import type { IconDecorId } from "./settingsAppearance";

/** 组合4(Lucide 细线)字形表:语义贴近组合1 现状。 */
export const LUCIDE_A: Partial<Record<IconDecorId, LucideNode>> = {
  newchat: Rocket,
  "ssh-panel": Server,
  "system-proxy": Globe,
  "panel-files": Folder,
  "panel-git": GitBranch,
  "panel-checkpoints": History,
  "panel-memory": Brain,
  "panel-marks": Bookmark,
  "panel-approval-inbox": Bell,
  "panel-skill-hub": Puzzle,
  "panel-mcp-hub": Plug,
  "wsl-panel": Monitor,
  terminal: Terminal,
  "intent-canvas": Compass,
  "session-board": CalendarDays,
  "remote-control": MonitorPlay,
  worktree: GitFork,
  "ws-files": Rows3,
  "ws-manage": ListChecks,
  "ws-refresh": RefreshCw,
  market: ShoppingBag,
  home: LHouse,
  "stage-expand": ChevronUp,
  "stage-collapse": ChevronDown,
  "composer-drawer": PanelLeft,
  "wake-agent": Bot,
  "wake-prompt": TextQuote,
  "ai-draw": Palette,
  broadcast: Radio,
  enhance: WandSparkles,
  "wake-skill": LLightbulb,
  "wake-mcp": Blocks,
  "git-open": ExternalLink,
  "git-row-actions": SlidersHorizontal,
  "git-view": LEye,
  "git-layout": List,
  "git-remote": ArrowUpDown,
  "git-worktree": ListTree,
  "git-repo-ops": ArrowUp,
  "files-new-file": FilePlus,
  "files-new-folder": LFolderPlus,
  "files-refresh": RefreshCcw,
  "files-git-toggle": GitCompare,
};

/** 组合5(Lucide 细线变体)字形表:逐键换隐喻,与组合4 逐键不同 → 4↔5 切换全表 morph。 */
export const LUCIDE_B: Partial<Record<IconDecorId, LucideNode>> = {
  newchat: Sparkles,
  "ssh-panel": KeyRound,
  "system-proxy": Shuffle,
  "panel-files": FolderOpen,
  "panel-git": LGitMerge,
  "panel-checkpoints": BadgeCheck,
  "panel-memory": LCpu,
  "panel-marks": Flag,
  "panel-approval-inbox": Inbox,
  "panel-skill-hub": LGraduationCap,
  "panel-mcp-hub": Cable,
  "wsl-panel": AppWindow,
  terminal: SquareTerminal,
  "intent-canvas": PenTool,
  "session-board": LayoutGrid,
  "remote-control": Cast,
  worktree: Network,
  "ws-files": LTable,
  "ws-manage": ListTodo,
  "ws-refresh": RotateCw,
  market: Store,
  home: ArrowLeft,
  "stage-expand": ChevronsUp,
  "stage-collapse": ChevronsDown,
  "composer-drawer": Layers,
  "wake-agent": UserRound,
  "wake-prompt": NotebookPen,
  "ai-draw": Brush,
  broadcast: LMegaphone,
  enhance: Zap,
  "wake-skill": Star,
  "wake-mcp": Server,
  "git-open": SquareArrowOutUpRight,
  "git-row-actions": Settings2,
  "git-view": Binoculars,
  "git-layout": LayoutList,
  "git-remote": ArrowDownUp,
  "git-worktree": Split,
  "git-repo-ops": CloudUpload,
  "files-new-file": FilePlus2,
  "files-new-folder": FolderInput,
  "files-refresh": RotateCcw,
  "files-git-toggle": FileDiff,
};
