/**
 * VS Code dark 主题 preset 数据 —— 移植自 codemoss features/theme/constants/vscodeThemePresets.ts(勿手改,说明见 ./index.ts)。
 */
/* 本文件自 dark1.ts/dark2.ts 拆出(文件规模铁则收紧至 300 行):承接 one-dark-pro/monokai/solarized-dark/dracula 四个 preset。 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const DARK_PRESETS_PART2 = {
  "vscode-one-dark-pro": {
    "id": "vscode-one-dark-pro",
    "appearance": "dark",
    "colors": {
      "foreground": "#abb2bf",
      "descriptionForeground": "#7f848e",
      "editor.background": "#282c34",
      "editor.foreground": "#abb2bf",
      "sideBar.background": "#21252b",
      "sideBar.foreground": "#abb2bf",
      "panel.background": "#282c34",
      "panel.border": "#3b4048",
      "input.background": "#1e2228",
      "input.foreground": "#abb2bf",
      "input.border": "#3b4048",
      "button.background": "#61afef",
      "button.foreground": "#0b0f14",
      "button.secondaryBackground": "#2c313c",
      "button.secondaryForeground": "#abb2bf",
      "dropdown.background": "#21252b",
      "dropdown.border": "#3b4048",
      "editorWidget.background": "#21252b",
      "list.hoverBackground": "#2c313c",
      "list.activeSelectionBackground": "#3e4451",
      "list.activeSelectionForeground": "#ffffff",
      "activityBar.background": "#21252b",
      "activityBar.foreground": "#d7dae0",
      "statusBar.background": "#21252b",
      "statusBar.foreground": "#abb2bf",
      "titleBar.activeBackground": "#282c34",
      "titleBar.activeForeground": "#abb2bf",
      "terminal.background": "#282c34",
      "terminal.foreground": "#abb2bf",
      "terminal.selectionBackground": "#3e4451",
      "terminalCursor.foreground": "#61afef",
      "editorLineNumber.foreground": "#636d83",
      "editorGutter.addedBackground": "#98c379",
      "editorGutter.modifiedBackground": "#e5c07b",
      "editorGutter.deletedBackground": "#e06c75",
      "textLink.foreground": "#61afef",
      "badge.background": "#3e4451",
      "badge.foreground": "#ffffff"
    },
    "syntax": {
      "keyword": "#c678dd",
      "string": "#98c379",
      "comment": "#5c6370",
      "number": "#d19a66",
      "function": "#61afef",
      "operator": "#56b6c2",
      "type": "#e5c07b",
      "tag": "#e06c75"
    },
    "diff": {
      "inserted": "#98c379",
      "removed": "#e06c75"
    },
    "label": "One Dark Pro"
  },
  "vscode-monokai": {
    "id": "vscode-monokai",
    "appearance": "dark",
    "colors": {
      "foreground": "#f8f8f2",
      "descriptionForeground": "#b6b6aa",
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "sideBar.background": "#1e1f1c",
      "sideBar.foreground": "#f8f8f2",
      "panel.background": "#272822",
      "panel.border": "#414339",
      "input.background": "#3b3a32",
      "input.foreground": "#f8f8f2",
      "input.border": "#5b5c57",
      "button.background": "#66d9ef",
      "button.foreground": "#1a1b17",
      "button.secondaryBackground": "#414339",
      "button.secondaryForeground": "#f8f8f2",
      "dropdown.background": "#3b3a32",
      "dropdown.border": "#5b5c57",
      "editorWidget.background": "#1e1f1c",
      "list.hoverBackground": "#3b3a32",
      "list.activeSelectionBackground": "#49483e",
      "list.activeSelectionForeground": "#f8f8f2",
      "activityBar.background": "#1e1f1c",
      "activityBar.foreground": "#f8f8f2",
      "statusBar.background": "#414339",
      "statusBar.foreground": "#f8f8f2",
      "titleBar.activeBackground": "#272822",
      "titleBar.activeForeground": "#f8f8f2",
      "terminal.background": "#272822",
      "terminal.foreground": "#f8f8f2",
      "terminal.selectionBackground": "#49483e",
      "terminalCursor.foreground": "#f8f8f2",
      "editorLineNumber.foreground": "#90908a",
      "editorGutter.addedBackground": "#a6e22e",
      "editorGutter.modifiedBackground": "#e6db74",
      "editorGutter.deletedBackground": "#f92672",
      "textLink.foreground": "#66d9ef",
      "badge.background": "#5b5c57",
      "badge.foreground": "#f8f8f2"
    },
    "syntax": {
      "keyword": "#f92672",
      "string": "#e6db74",
      "comment": "#75715e",
      "number": "#ae81ff",
      "function": "#a6e22e",
      "operator": "#f92672",
      "type": "#66d9ef",
      "tag": "#f92672"
    },
    "diff": {
      "inserted": "#a6e22e",
      "removed": "#f92672"
    },
    "label": "Monokai"
  },
  "vscode-solarized-dark": {
    "id": "vscode-solarized-dark",
    "appearance": "dark",
    "colors": {
      "foreground": "#839496",
      "descriptionForeground": "#72898f",
      "editor.background": "#002b36",
      "editor.foreground": "#839496",
      "sideBar.background": "#073642",
      "sideBar.foreground": "#839496",
      "panel.background": "#002b36",
      "panel.border": "#17454f",
      "input.background": "#073642",
      "input.foreground": "#839496",
      "input.border": "#17454f",
      "button.background": "#268bd2",
      "button.foreground": "#fdf6e3",
      "button.secondaryBackground": "#17454f",
      "button.secondaryForeground": "#93a1a1",
      "dropdown.background": "#073642",
      "dropdown.border": "#17454f",
      "editorWidget.background": "#073642",
      "list.hoverBackground": "#0b3a47",
      "list.activeSelectionBackground": "#0f4c5c",
      "list.activeSelectionForeground": "#fdf6e3",
      "activityBar.background": "#073642",
      "activityBar.foreground": "#93a1a1",
      "statusBar.background": "#073642",
      "statusBar.foreground": "#93a1a1",
      "titleBar.activeBackground": "#002b36",
      "titleBar.activeForeground": "#93a1a1",
      "terminal.background": "#002b36",
      "terminal.foreground": "#839496",
      "terminal.selectionBackground": "#0f4c5c",
      "terminalCursor.foreground": "#268bd2",
      "editorLineNumber.foreground": "#586e75",
      "editorGutter.addedBackground": "#859900",
      "editorGutter.modifiedBackground": "#b58900",
      "editorGutter.deletedBackground": "#dc322f",
      "textLink.foreground": "#268bd2",
      "badge.background": "#17454f",
      "badge.foreground": "#93a1a1"
    },
    "syntax": {
      "keyword": "#859900",
      "string": "#2aa198",
      "comment": "#586e75",
      "number": "#d33682",
      "function": "#268bd2",
      "operator": "#93a1a1",
      "type": "#b58900",
      "tag": "#268bd2"
    },
    "diff": {
      "inserted": "#859900",
      "removed": "#dc322f"
    },
    "label": "Solarized Dark"
  },
  "vscode-dracula": {
    "id": "vscode-dracula",
    "appearance": "dark",
    "colors": {
      "foreground": "#f8f8f2",
      "descriptionForeground": "#bfb7d5",
      "editor.background": "#282a36",
      "editor.foreground": "#f8f8f2",
      "sideBar.background": "#21222c",
      "sideBar.foreground": "#f8f8f2",
      "panel.background": "#282a36",
      "panel.border": "#44475a",
      "input.background": "#44475a",
      "input.foreground": "#f8f8f2",
      "input.border": "#6272a4",
      "button.background": "#bd93f9",
      "button.foreground": "#282a36",
      "button.secondaryBackground": "#44475a",
      "button.secondaryForeground": "#f8f8f2",
      "dropdown.background": "#343746",
      "dropdown.border": "#6272a4",
      "editorWidget.background": "#343746",
      "list.hoverBackground": "#343746",
      "list.activeSelectionBackground": "#44475a",
      "list.activeSelectionForeground": "#f8f8f2",
      "activityBar.background": "#21222c",
      "activityBar.foreground": "#f8f8f2",
      "statusBar.background": "#191a21",
      "statusBar.foreground": "#f8f8f2",
      "titleBar.activeBackground": "#282a36",
      "titleBar.activeForeground": "#f8f8f2",
      "terminal.background": "#282a36",
      "terminal.foreground": "#f8f8f2",
      "terminal.selectionBackground": "#44475a",
      "terminalCursor.foreground": "#f8f8f2",
      "editorLineNumber.foreground": "#6272a4",
      "editorGutter.addedBackground": "#50fa7b",
      "editorGutter.modifiedBackground": "#f1fa8c",
      "editorGutter.deletedBackground": "#ff5555",
      "textLink.foreground": "#8be9fd",
      "badge.background": "#44475a",
      "badge.foreground": "#f8f8f2"
    },
    "syntax": {
      "keyword": "#ff79c6",
      "string": "#f1fa8c",
      "comment": "#6272a4",
      "number": "#bd93f9",
      "function": "#50fa7b",
      "operator": "#ff79c6",
      "type": "#8be9fd",
      "tag": "#ff79c6"
    },
    "diff": {
      "inserted": "#50fa7b",
      "removed": "#ff5555"
    },
    "label": "Dracula"
  },
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
