/**
 * VS Code dark 主题 preset 数据 —— 移植自 codemoss features/theme/constants/vscodeThemePresets.ts(勿手改,说明见 ./index.ts)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const DARK_PRESETS_PART1 = {
  "vscode-dark-modern": {
    "id": "vscode-dark-modern",
    "appearance": "dark",
    "colors": {
      "foreground": "#cccccc",
      "descriptionForeground": "#9d9d9d",
      "editor.background": "#1f1f1f",
      "editor.foreground": "#cccccc",
      "sideBar.background": "#181818",
      "sideBar.foreground": "#cccccc",
      "panel.background": "#181818",
      "panel.border": "#2b2b2b",
      "input.background": "#313131",
      "input.foreground": "#cccccc",
      "input.border": "#3c3c3c",
      "button.background": "#0078d4",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#313131",
      "button.secondaryForeground": "#cccccc",
      "dropdown.background": "#313131",
      "dropdown.border": "#3c3c3c",
      "editorWidget.background": "#202020",
      "list.hoverBackground": "#242424",
      "list.activeSelectionBackground": "#04395e",
      "list.activeSelectionForeground": "#ffffff",
      "activityBar.background": "#181818",
      "activityBar.foreground": "#d7d7d7",
      "statusBar.background": "#181818",
      "statusBar.foreground": "#cccccc",
      "titleBar.activeBackground": "#181818",
      "titleBar.activeForeground": "#cccccc",
      "terminal.background": "#1f1f1f",
      "terminal.foreground": "#cccccc",
      "terminal.selectionBackground": "#264f78",
      "terminalCursor.foreground": "#cccccc",
      "editorLineNumber.foreground": "#6e7681",
      "editorGutter.addedBackground": "#2ea043",
      "editorGutter.modifiedBackground": "#0078d4",
      "editorGutter.deletedBackground": "#f85149",
      "textLink.foreground": "#4daafc",
      "badge.background": "#616161",
      "badge.foreground": "#f8f8f8"
    },
    "syntax": {
      "keyword": "#569cd6",
      "string": "#ce9178",
      "comment": "#6a9955",
      "number": "#b5cea8",
      "function": "#dcdcaa",
      "operator": "#d4d4d4",
      "type": "#4ec9b0",
      "tag": "#569cd6"
    },
    "diff": {
      "inserted": "#2ea043",
      "removed": "#f85149"
    },
    "label": "Dark Modern"
  },
  "vscode-dark-plus": {
    "id": "vscode-dark-plus",
    "appearance": "dark",
    "colors": {
      "foreground": "#cccccc",
      "descriptionForeground": "#969696",
      "editor.background": "#1e1e1e",
      "editor.foreground": "#d4d4d4",
      "sideBar.background": "#252526",
      "sideBar.foreground": "#cccccc",
      "panel.background": "#1e1e1e",
      "panel.border": "#2b2b2b",
      "input.background": "#3c3c3c",
      "input.foreground": "#cccccc",
      "input.border": "#3c3c3c",
      "button.background": "#0e639c",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#3a3d41",
      "button.secondaryForeground": "#cccccc",
      "dropdown.background": "#3c3c3c",
      "dropdown.border": "#3c3c3c",
      "editorWidget.background": "#252526",
      "list.hoverBackground": "#2a2d2e",
      "list.activeSelectionBackground": "#094771",
      "list.activeSelectionForeground": "#ffffff",
      "activityBar.background": "#333333",
      "activityBar.foreground": "#ffffff",
      "statusBar.background": "#007acc",
      "statusBar.foreground": "#ffffff",
      "titleBar.activeBackground": "#3c3c3c",
      "titleBar.activeForeground": "#cccccc",
      "terminal.background": "#1e1e1e",
      "terminal.foreground": "#cccccc",
      "terminal.selectionBackground": "#264f78",
      "terminalCursor.foreground": "#aeafad",
      "editorLineNumber.foreground": "#858585",
      "editorGutter.addedBackground": "#2ea043",
      "editorGutter.modifiedBackground": "#007acc",
      "editorGutter.deletedBackground": "#f14c4c",
      "textLink.foreground": "#3794ff",
      "badge.background": "#4d4d4d",
      "badge.foreground": "#ffffff"
    },
    "syntax": {
      "keyword": "#569cd6",
      "string": "#ce9178",
      "comment": "#6a9955",
      "number": "#b5cea8",
      "function": "#dcdcaa",
      "operator": "#d4d4d4",
      "type": "#4ec9b0",
      "tag": "#569cd6"
    },
    "diff": {
      "inserted": "#2ea043",
      "removed": "#f14c4c"
    },
    "label": "Dark+"
  },
  "vscode-github-dark": {
    "id": "vscode-github-dark",
    "appearance": "dark",
    "colors": {
      "foreground": "#c9d1d9",
      "descriptionForeground": "#8b949e",
      "editor.background": "#0d1117",
      "editor.foreground": "#c9d1d9",
      "sideBar.background": "#010409",
      "sideBar.foreground": "#c9d1d9",
      "panel.background": "#0d1117",
      "panel.border": "#30363d",
      "input.background": "#161b22",
      "input.foreground": "#c9d1d9",
      "input.border": "#30363d",
      "button.background": "#2f81f7",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#21262d",
      "button.secondaryForeground": "#c9d1d9",
      "dropdown.background": "#161b22",
      "dropdown.border": "#30363d",
      "editorWidget.background": "#161b22",
      "list.hoverBackground": "#161b22",
      "list.activeSelectionBackground": "#1f6feb",
      "list.activeSelectionForeground": "#ffffff",
      "activityBar.background": "#010409",
      "activityBar.foreground": "#f0f6fc",
      "statusBar.background": "#161b22",
      "statusBar.foreground": "#c9d1d9",
      "titleBar.activeBackground": "#0d1117",
      "titleBar.activeForeground": "#c9d1d9",
      "terminal.background": "#0d1117",
      "terminal.foreground": "#c9d1d9",
      "terminal.selectionBackground": "#264f78",
      "terminalCursor.foreground": "#c9d1d9",
      "editorLineNumber.foreground": "#6e7681",
      "editorGutter.addedBackground": "#3fb950",
      "editorGutter.modifiedBackground": "#2f81f7",
      "editorGutter.deletedBackground": "#f85149",
      "textLink.foreground": "#58a6ff",
      "badge.background": "#30363d",
      "badge.foreground": "#f0f6fc"
    },
    "syntax": {
      "keyword": "#ff7b72",
      "string": "#a5d6ff",
      "comment": "#8b949e",
      "number": "#79c0ff",
      "function": "#d2a8ff",
      "operator": "#c9d1d9",
      "type": "#ffa657",
      "tag": "#7ee787"
    },
    "diff": {
      "inserted": "#3fb950",
      "removed": "#f85149"
    },
    "label": "GitHub Dark"
  },
  "vscode-github-dark-dimmed": {
    "id": "vscode-github-dark-dimmed",
    "appearance": "dark",
    "colors": {
      "foreground": "#adbac7",
      "descriptionForeground": "#768390",
      "editor.background": "#22272e",
      "editor.foreground": "#adbac7",
      "sideBar.background": "#1c2128",
      "sideBar.foreground": "#adbac7",
      "panel.background": "#22272e",
      "panel.border": "#373e47",
      "input.background": "#2d333b",
      "input.foreground": "#adbac7",
      "input.border": "#444c56",
      "button.background": "#539bf5",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#373e47",
      "button.secondaryForeground": "#adbac7",
      "dropdown.background": "#2d333b",
      "dropdown.border": "#444c56",
      "editorWidget.background": "#2d333b",
      "list.hoverBackground": "#2d333b",
      "list.activeSelectionBackground": "#316dca",
      "list.activeSelectionForeground": "#ffffff",
      "activityBar.background": "#1c2128",
      "activityBar.foreground": "#adbac7",
      "statusBar.background": "#22272e",
      "statusBar.foreground": "#adbac7",
      "titleBar.activeBackground": "#22272e",
      "titleBar.activeForeground": "#adbac7",
      "terminal.background": "#22272e",
      "terminal.foreground": "#adbac7",
      "terminal.selectionBackground": "#264f78",
      "terminalCursor.foreground": "#adbac7",
      "editorLineNumber.foreground": "#636e7b",
      "editorGutter.addedBackground": "#57ab5a",
      "editorGutter.modifiedBackground": "#539bf5",
      "editorGutter.deletedBackground": "#e5534b",
      "textLink.foreground": "#539bf5",
      "badge.background": "#444c56",
      "badge.foreground": "#f0f6fc"
    },
    "syntax": {
      "keyword": "#f47067",
      "string": "#96cbca",
      "comment": "#8b949e",
      "number": "#6cb6ff",
      "function": "#b392f0",
      "operator": "#9d9d9d",
      "type": "#c69026",
      "tag": "#adbac7"
    },
    "diff": {
      "inserted": "#57ab5a",
      "removed": "#e5534b"
    },
    "label": "GitHub Dark Dimmed"
  },
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
