/**
 * tmd 原创深色主题 preset(低饱和高级灰取向,2026-10-02 定稿,原型见 docs/design/premium-themes.html)。
 * 非 codemoss 移植件,不受「勿手改」约束;键集合须与 dark 族单一签名一致(38 键,主题不变量测试钉死)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const DARK_PRESETS_PART4 = {
  "tmd-graphite": {
    "id": "tmd-graphite",
    "appearance": "dark",
    "colors": {
      "foreground": "#d4d4d9",
      "descriptionForeground": "#8b8b93",
      "editor.background": "#0f0f12",
      "editor.foreground": "#d4d4d9",
      "sideBar.background": "#131316",
      "sideBar.foreground": "#b8b8bf",
      "panel.background": "#131316",
      "panel.border": "#232329",
      "input.background": "#1a1a1e",
      "input.foreground": "#d4d4d9",
      "input.border": "#2c2c33",
      "button.background": "#5b5bd6",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#1f1f24",
      "button.secondaryForeground": "#c4c4cb",
      "dropdown.background": "#1a1a1e",
      "dropdown.border": "#2c2c33",
      "editorWidget.background": "#16161a",
      "list.hoverBackground": "#1b1b20",
      "list.activeSelectionBackground": "#28284a",
      "list.activeSelectionForeground": "#ececff",
      "activityBar.background": "#131316",
      "activityBar.foreground": "#c9c9d1",
      "statusBar.background": "#131316",
      "statusBar.foreground": "#8b8b93",
      "titleBar.activeBackground": "#131316",
      "titleBar.activeForeground": "#b8b8bf",
      "terminal.background": "#0f0f12",
      "terminal.foreground": "#d4d4d9",
      "terminal.selectionBackground": "#2b2b45",
      "terminalCursor.foreground": "#d4d4d9",
      "editorLineNumber.foreground": "#4c4c55",
      "editorGutter.addedBackground": "#3d9a50",
      "editorGutter.modifiedBackground": "#5b5bd6",
      "editorGutter.deletedBackground": "#e5484d",
      "textLink.foreground": "#7c7ce0",
      "badge.background": "#2a2a31",
      "badge.foreground": "#d4d4d9"
    },
    "syntax": {
      "keyword": "#8a86e8",
      "string": "#c9997c",
      "comment": "#62626b",
      "number": "#c2a878",
      "function": "#c9bd85",
      "operator": "#a3a3ab",
      "type": "#6fb3b8",
      "tag": "#8a86e8"
    },
    "diff": {
      "inserted": "#3d9a50",
      "removed": "#e5484d"
    },
    "label": "石墨"
  },
  "tmd-ink": {
    "id": "tmd-ink",
    "appearance": "dark",
    "colors": {
      "foreground": "#ccd3dc",
      "descriptionForeground": "#7e8894",
      "editor.background": "#0e1218",
      "editor.foreground": "#ccd3dc",
      "sideBar.background": "#12161d",
      "sideBar.foreground": "#b0b9c4",
      "panel.background": "#12161d",
      "panel.border": "#222a35",
      "input.background": "#181e27",
      "input.foreground": "#ccd3dc",
      "input.border": "#28303c",
      "button.background": "#4a7db8",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#1b222c",
      "button.secondaryForeground": "#bcc5d0",
      "dropdown.background": "#181e27",
      "dropdown.border": "#28303c",
      "editorWidget.background": "#141922",
      "list.hoverBackground": "#161d26",
      "list.activeSelectionBackground": "#1e3049",
      "list.activeSelectionForeground": "#e3ecf7",
      "activityBar.background": "#12161d",
      "activityBar.foreground": "#c2cad4",
      "statusBar.background": "#12161d",
      "statusBar.foreground": "#7e8894",
      "titleBar.activeBackground": "#12161d",
      "titleBar.activeForeground": "#b0b9c4",
      "terminal.background": "#0e1218",
      "terminal.foreground": "#ccd3dc",
      "terminal.selectionBackground": "#223350",
      "terminalCursor.foreground": "#ccd3dc",
      "editorLineNumber.foreground": "#49525e",
      "editorGutter.addedBackground": "#3d9a50",
      "editorGutter.modifiedBackground": "#4a7db8",
      "editorGutter.deletedBackground": "#e5484d",
      "textLink.foreground": "#6fa3d8",
      "badge.background": "#232b36",
      "badge.foreground": "#ccd3dc"
    },
    "syntax": {
      "keyword": "#8a9fd8",
      "string": "#c2997c",
      "comment": "#5d6773",
      "number": "#c2a878",
      "function": "#c9bd85",
      "operator": "#9aa4b0",
      "type": "#6fa8a8",
      "tag": "#8a9fd8"
    },
    "diff": {
      "inserted": "#3d9a50",
      "removed": "#e5484d"
    },
    "label": "黛蓝"
  },
  "tmd-ember": {
    "id": "tmd-ember",
    "appearance": "dark",
    "colors": {
      "foreground": "#d6d0c8",
      "descriptionForeground": "#91897e",
      "editor.background": "#131110",
      "editor.foreground": "#d6d0c8",
      "sideBar.background": "#171413",
      "sideBar.foreground": "#bcb3a6",
      "panel.background": "#171413",
      "panel.border": "#292421",
      "input.background": "#1d1a18",
      "input.foreground": "#d6d0c8",
      "input.border": "#332d29",
      "button.background": "#b3743f",
      "button.foreground": "#fff8f0",
      "button.secondaryBackground": "#211d1b",
      "button.secondaryForeground": "#c8c0b6",
      "dropdown.background": "#1d1a18",
      "dropdown.border": "#332d29",
      "editorWidget.background": "#1a1715",
      "list.hoverBackground": "#1c1917",
      "list.activeSelectionBackground": "#332618",
      "list.activeSelectionForeground": "#f0e6d8",
      "activityBar.background": "#171413",
      "activityBar.foreground": "#c6beb2",
      "statusBar.background": "#171413",
      "statusBar.foreground": "#91897e",
      "titleBar.activeBackground": "#171413",
      "titleBar.activeForeground": "#bcb3a6",
      "terminal.background": "#131110",
      "terminal.foreground": "#d6d0c8",
      "terminal.selectionBackground": "#3a2d1c",
      "terminalCursor.foreground": "#d6d0c8",
      "editorLineNumber.foreground": "#544e47",
      "editorGutter.addedBackground": "#3d9a50",
      "editorGutter.modifiedBackground": "#b3743f",
      "editorGutter.deletedBackground": "#e5484d",
      "textLink.foreground": "#d0975c",
      "badge.background": "#2a2521",
      "badge.foreground": "#d6d0c8"
    },
    "syntax": {
      "keyword": "#c98d6b",
      "string": "#a8b57c",
      "comment": "#66605a",
      "number": "#c2a878",
      "function": "#cfc085",
      "operator": "#a39a8e",
      "type": "#7ba8a0",
      "tag": "#c98d6b"
    },
    "diff": {
      "inserted": "#3d9a50",
      "removed": "#e5484d"
    },
    "label": "暖炭"
  },
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
