/**
 * VS Code light 主题 preset 数据 —— 2026-09-08 浅色扩充批(勿手改,说明见 ./index.ts)。
 * 源:各主题官方仓库一手 json / Kanagawa 官方色板 / One Half·Tomorrow·Xcode 经典色板;
 * terminal.ansi* 按浅底可读适配(16 槽对 terminal 背景 WCAG 对比度 ≥3:1,详见 spec)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART5 = {
  "vscode-kanagawa-lotus": {
    "id": "vscode-kanagawa-lotus",
    "appearance": "light",
    "label": "Kanagawa Lotus",
    "colors": {
      "foreground": "#545464",
      "editor.background": "#f2ecbc",
      "editor.foreground": "#545464",
      "sideBar.background": "#f2ecbc",
      "sideBar.foreground": "#545464",
      "panel.background": "#f2ecbc",
      "panel.border": "#c9cbd1",
      "input.background": "#f9f5e7",
      "input.foreground": "#43436c",
      "input.border": "#c9cbd1",
      "button.background": "#4d699b",
      "button.foreground": "#f2ecbc",
      "button.secondaryBackground": "#e5ddc0",
      "button.secondaryForeground": "#43436c",
      "dropdown.background": "#f9f5e7",
      "dropdown.border": "#c9cbd1",
      "editorWidget.background": "#e5ddc0",
      "list.hoverBackground": "#e5ddc0",
      "list.activeSelectionBackground": "#dcd7ba",
      "list.activeSelectionForeground": "#43436c",
      "activityBar.background": "#f2ecbc",
      "activityBar.foreground": "#43436c",
      "statusBar.background": "#e5ddc0",
      "statusBar.foreground": "#43436c",
      "titleBar.activeBackground": "#f2ecbc",
      "titleBar.activeForeground": "#43436c",
      "terminal.background": "#f2ecbc",
      "terminal.foreground": "#545464",
      "terminal.selectionBackground": "#c9cbd1",
      "terminalCursor.foreground": "#43436c",
      "editorLineNumber.foreground": "#8a8980",
      "editorGutter.addedBackground": "#6f894e",
      "editorGutter.modifiedBackground": "#4d699b",
      "editorGutter.deletedBackground": "#c84053",
      "textLink.foreground": "#4d699b",
      "badge.background": "#dcd7ba",
      "badge.foreground": "#43436c",
      "terminal.ansiBlack": "#1f1f28",
      "terminal.ansiBrightBlack": "#7f7e76",
      "terminal.ansiRed": "#c84053",
      "terminal.ansiBrightRed": "#d7474b",
      "terminal.ansiGreen": "#6f894e",
      "terminal.ansiBrightGreen": "#658557",
      "terminal.ansiYellow": "#77713f",
      "terminal.ansiBrightYellow": "#836f4a",
      "terminal.ansiBlue": "#4d699b",
      "terminal.ansiBrightBlue": "#5e87b0",
      "terminal.ansiMagenta": "#b35b79",
      "terminal.ansiBrightMagenta": "#624c83",
      "terminal.ansiCyan": "#597b75",
      "terminal.ansiBrightCyan": "#5e857a",
      "terminal.ansiWhite": "#545464",
      "terminal.ansiBrightWhite": "#43436c"
    },
    "syntax": {
      "keyword": "#624c83",
      "string": "#6f894e",
      "comment": "#716e61",
      "number": "#836f4a",
      "function": "#6693bf",
      "operator": "#43436c",
      "type": "#4e8ca2",
      "tag": "#c84053"
    },
    "diff": {
      "inserted": "#6f894e",
      "removed": "#d7474b"
    }
  },
  "vscode-vitesse-light": {
    "id": "vscode-vitesse-light",
    "appearance": "light",
    "label": "Vitesse Light",
    "colors": {
      "foreground": "#393a34",
      "descriptionForeground": "#393a34",
      "editor.background": "#ffffff",
      "editor.foreground": "#393a34",
      "sideBar.background": "#ffffff",
      "sideBar.foreground": "#4e4f47",
      "panel.background": "#ffffff",
      "panel.border": "#f0f0f0",
      "input.background": "#f7f7f7",
      "input.foreground": "#393a34",
      "input.border": "#f0f0f0",
      "button.background": "#1c6b48",
      "button.foreground": "#ffffff",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#f0f0f0",
      "editorWidget.background": "#ffffff",
      "list.hoverBackground": "#f7f7f7",
      "list.activeSelectionBackground": "#f7f7f7",
      "list.activeSelectionForeground": "#393a34",
      "activityBar.background": "#ffffff",
      "activityBar.foreground": "#393a34",
      "statusBar.background": "#ffffff",
      "statusBar.foreground": "#4e4f47",
      "titleBar.activeBackground": "#ffffff",
      "titleBar.activeForeground": "#4e4f47",
      "terminal.foreground": "#393a34",
      "terminal.selectionBackground": "#222222",
      "editorLineNumber.foreground": "#393a34",
      "editorGutter.addedBackground": "#1e754f",
      "editorGutter.modifiedBackground": "#296aa3",
      "editorGutter.deletedBackground": "#ab5959",
      "textLink.foreground": "#1c6b48",
      "badge.background": "#393a34",
      "badge.foreground": "#ffffff",
      "terminal.ansiBlack": "#121212",
      "terminal.ansiRed": "#ab5959",
      "terminal.ansiGreen": "#1e754f",
      "terminal.ansiYellow": "#a08b2f",
      "terminal.ansiBlue": "#296aa3",
      "terminal.ansiMagenta": "#a13865",
      "terminal.ansiCyan": "#2993a3",
      "terminal.ansiWhite": "#908e84",
      "terminal.ansiBrightBlack": "#909090",
      "terminal.ansiBrightRed": "#ab5959",
      "terminal.ansiBrightGreen": "#1e754f",
      "terminal.ansiBrightYellow": "#a08b2f",
      "terminal.ansiBrightBlue": "#296aa3",
      "terminal.ansiBrightMagenta": "#a13865",
      "terminal.ansiBrightCyan": "#2993a3",
      "terminal.ansiBrightWhite": "#919191",
      "button.secondaryBackground": "#efefef",
      "button.secondaryForeground": "#393a34",
      "terminal.background": "#ffffff",
      "terminalCursor.foreground": "#393a34"
    },
    "syntax": {
      "keyword": "#1e754f",
      "string": "#b56959",
      "comment": "#a0ada0",
      "number": "#2f798a",
      "function": "#59873a",
      "operator": "#ab5959",
      "type": "#2e8f82",
      "tag": "#1e754f"
    },
    "diff": {
      "inserted": "#1e754f",
      "removed": "#ab5959"
    }
  },
  "vscode-eva-light": {
    "id": "vscode-eva-light",
    "appearance": "light",
    "label": "Eva Light",
    "colors": {
      "foreground": "#626264",
      "descriptionForeground": "#626264",
      "editor.background": "#ebeef5",
      "editor.foreground": "#5d5d5f",
      "sideBar.background": "#e1e4eb",
      "sideBar.foreground": "#626264",
      "panel.background": "#ebeef5",
      "panel.border": "#e1e4eb",
      "input.background": "#ebeef5",
      "input.foreground": "#5d5d5f",
      "input.border": "#e1e4eb",
      "button.background": "#a0a1a7",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#a0a1a7",
      "button.secondaryForeground": "#ffffff",
      "dropdown.background": "#f1f4fb",
      "dropdown.border": "#ced1d7",
      "editorWidget.background": "#e1e4eb",
      "list.hoverBackground": "#0065ff",
      "list.activeSelectionBackground": "#0065ff",
      "list.activeSelectionForeground": "#5d5d5f",
      "activityBar.background": "#ebeef5",
      "activityBar.foreground": "#787a7f",
      "statusBar.background": "#e1e4eb",
      "statusBar.foreground": "#5d5d5f",
      "titleBar.activeBackground": "#ebeef5",
      "titleBar.activeForeground": "#626264",
      "terminal.background": "#ebeef5",
      "terminal.foreground": "#5d5d5f",
      "terminal.selectionBackground": "#0065ff",
      "terminalCursor.foreground": "#fc8357",
      "editorLineNumber.foreground": "#b3b3b4",
      "editorGutter.addedBackground": "#44c145",
      "editorGutter.modifiedBackground": "#9277e6",
      "editorGutter.deletedBackground": "#f14c4c",
      "textLink.foreground": "#4d91f8",
      "badge.background": "#b3b3b4",
      "badge.foreground": "#ffffff",
      "terminal.ansiBlack": "#5d5d5f",
      "terminal.ansiRed": "#ec0000",
      "terminal.ansiGreen": "#359735",
      "terminal.ansiYellow": "#ac7907",
      "terminal.ansiBlue": "#4480f4",
      "terminal.ansiMagenta": "#c838c6",
      "terminal.ansiCyan": "#009499",
      "terminal.ansiWhite": "#5d5d5f",
      "terminal.ansiBrightBlack": "#84868d",
      "terminal.ansiBrightRed": "#f14c4c",
      "terminal.ansiBrightGreen": "#359735",
      "terminal.ansiBrightYellow": "#d85c10",
      "terminal.ansiBrightBlue": "#4785e4",
      "terminal.ansiBrightMagenta": "#ba6fa8",
      "terminal.ansiBrightCyan": "#009499",
      "terminal.ansiBrightWhite": "#888888"
    },
    "syntax": {
      "keyword": "#7c4dff",
      "string": "#53a053",
      "comment": "#a9a9aa",
      "number": "#ff6d12",
      "function": "#437aed",
      "operator": "#00bec4",
      "type": "#00bec4",
      "tag": "#cd6069"
    },
    "diff": {
      "inserted": "#83C654",
      "removed": "#f14c4c"
    }
  }
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
