/**
 * VS Code light 主题 preset 数据 —— 移植自 codemoss(勿手改,说明见 ./index.ts)。
 * terminal.ansi* 16 色浅底可读适配:色相取自各主题官方终端色板(Solarized 官方配色 /
 * Catppuccin 官方 kitty / Tokyo Night 官方 day),对比度不足处保 H/S 降 L 至 WCAG ≥3:1。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART2 = {
  "vscode-solarized-light": {
    "id": "vscode-solarized-light",
    "appearance": "light",
    "colors": {
      "foreground": "#657b83",
      "descriptionForeground": "#6c7f86",
      "editor.background": "#fdf6e3",
      "editor.foreground": "#586e75",
      "sideBar.background": "#eee8d5",
      "sideBar.foreground": "#586e75",
      "panel.background": "#f7f0dd",
      "panel.border": "#d8cfb5",
      "input.background": "#fdf6e3",
      "input.foreground": "#586e75",
      "input.border": "#cfc7ad",
      "button.background": "#268bd2",
      "button.foreground": "#fdf6e3",
      "button.secondaryBackground": "#eee8d5",
      "button.secondaryForeground": "#586e75",
      "dropdown.background": "#fdf6e3",
      "dropdown.border": "#cfc7ad",
      "editorWidget.background": "#f7f0dd",
      "list.hoverBackground": "#f1ead7",
      "list.activeSelectionBackground": "#dce8ef",
      "list.activeSelectionForeground": "#073642",
      "activityBar.background": "#eee8d5",
      "activityBar.foreground": "#586e75",
      "statusBar.background": "#eee8d5",
      "statusBar.foreground": "#586e75",
      "titleBar.activeBackground": "#fdf6e3",
      "titleBar.activeForeground": "#586e75",
      "terminal.background": "#fdf6e3",
      "terminal.foreground": "#586e75",
      "terminal.selectionBackground": "#dce8ef",
      "terminalCursor.foreground": "#268bd2",
      "editorLineNumber.foreground": "#93a1a1",
      "editorGutter.addedBackground": "#859900",
      "editorGutter.modifiedBackground": "#b58900",
      "editorGutter.deletedBackground": "#dc322f",
      "textLink.foreground": "#268bd2",
      "badge.background": "#e0d8be",
      "badge.foreground": "#586e75",
      "terminal.ansiBlack": "#073642",
      "terminal.ansiRed": "#dc322f",
      "terminal.ansiGreen": "#839600",
      "terminal.ansiYellow": "#b38700",
      "terminal.ansiBlue": "#268bd2",
      "terminal.ansiMagenta": "#d33682",
      "terminal.ansiCyan": "#299d95",
      "terminal.ansiWhite": "#657b83",
      "terminal.ansiBrightBlack": "#586e75",
      "terminal.ansiBrightRed": "#cb4b16",
      "terminal.ansiBrightGreen": "#839600",
      "terminal.ansiBrightYellow": "#b38700",
      "terminal.ansiBrightBlue": "#268bd2",
      "terminal.ansiBrightMagenta": "#d33682",
      "terminal.ansiBrightCyan": "#299d95",
      "terminal.ansiBrightWhite": "#7f9193"
    },
    "syntax": {
      "keyword": "#859900",
      "string": "#2aa198",
      "comment": "#93a1a1",
      "number": "#d33682",
      "function": "#268bd2",
      "operator": "#586e75",
      "type": "#b58900",
      "tag": "#268bd2"
    },
    "diff": {
      "inserted": "#859900",
      "removed": "#dc322f"
    },
    "label": "Solarized Light"
  },
  "vscode-catppuccin-latte": {
    "id": "vscode-catppuccin-latte",
    "appearance": "light",
    "colors": {
      "foreground": "#4c4f69",
      "descriptionForeground": "#6c6f85",
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      "sideBar.background": "#e6e9ef",
      "sideBar.foreground": "#4c4f69",
      "panel.background": "#eff1f5",
      "panel.border": "#ccd0da",
      "input.background": "#e6e9ef",
      "input.foreground": "#4c4f69",
      "input.border": "#bcc0cc",
      "button.background": "#1e66f5",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#dce0e8",
      "button.secondaryForeground": "#4c4f69",
      "dropdown.background": "#e6e9ef",
      "dropdown.border": "#bcc0cc",
      "editorWidget.background": "#e6e9ef",
      "list.hoverBackground": "#dce0e8",
      "list.activeSelectionBackground": "#ccd0da",
      "list.activeSelectionForeground": "#1e1e2e",
      "activityBar.background": "#dce0e8",
      "activityBar.foreground": "#4c4f69",
      "statusBar.background": "#e6e9ef",
      "statusBar.foreground": "#4c4f69",
      "titleBar.activeBackground": "#eff1f5",
      "titleBar.activeForeground": "#4c4f69",
      "terminal.background": "#eff1f5",
      "terminal.foreground": "#4c4f69",
      "terminal.selectionBackground": "#ccd0da",
      "terminalCursor.foreground": "#1e66f5",
      "editorLineNumber.foreground": "#8c8fa1",
      "editorGutter.addedBackground": "#40a02b",
      "editorGutter.modifiedBackground": "#df8e1d",
      "editorGutter.deletedBackground": "#d20f39",
      "textLink.foreground": "#1e66f5",
      "badge.background": "#ccd0da",
      "badge.foreground": "#4c4f69",
      "terminal.ansiBlack": "#5c5f77",
      "terminal.ansiRed": "#d20f39",
      "terminal.ansiGreen": "#3f9d2a",
      "terminal.ansiYellow": "#c07b19",
      "terminal.ansiBlue": "#1e66f5",
      "terminal.ansiMagenta": "#e44dbc",
      "terminal.ansiCyan": "#179299",
      "terminal.ansiWhite": "#84899e",
      "terminal.ansiBrightBlack": "#6c6f85",
      "terminal.ansiBrightRed": "#d20f39",
      "terminal.ansiBrightGreen": "#3f9d2a",
      "terminal.ansiBrightYellow": "#c07b19",
      "terminal.ansiBrightBlue": "#1e66f5",
      "terminal.ansiBrightMagenta": "#e44dbc",
      "terminal.ansiBrightCyan": "#179299",
      "terminal.ansiBrightWhite": "#8289a0"
    },
    "syntax": {
      "keyword": "#8839ef",
      "string": "#40a02b",
      "comment": "#9ca0b0",
      "number": "#fe640b",
      "function": "#1e66f5",
      "operator": "#7c7f93",
      "type": "#df8e1d",
      "tag": "#dd7878"
    },
    "diff": {
      "inserted": "#40a02b",
      "removed": "#d20f39"
    },
    "label": "Catppuccin Latte"
  },
  "vscode-tokyo-day": {
    "id": "vscode-tokyo-day",
    "appearance": "light",
    "colors": {
      "foreground": "#343b58",
      "descriptionForeground": "#5a607f",
      "editor.background": "#e1e2e7",
      "editor.foreground": "#343b58",
      "sideBar.background": "#d5d6db",
      "sideBar.foreground": "#343b58",
      "panel.background": "#e9e9ed",
      "panel.border": "#c4c8d8",
      "input.background": "#dfe1e8",
      "input.foreground": "#343b58",
      "input.border": "#b8bfd6",
      "button.background": "#2e7de9",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#cfd2e1",
      "button.secondaryForeground": "#343b58",
      "dropdown.background": "#dfe1e8",
      "dropdown.border": "#b8bfd6",
      "editorWidget.background": "#dfe1e8",
      "list.hoverBackground": "#d5d6db",
      "list.activeSelectionBackground": "#c6d7ff",
      "list.activeSelectionForeground": "#1f2335",
      "activityBar.background": "#cfd2e1",
      "activityBar.foreground": "#343b58",
      "statusBar.background": "#d5d6db",
      "statusBar.foreground": "#343b58",
      "titleBar.activeBackground": "#e1e2e7",
      "titleBar.activeForeground": "#343b58",
      "terminal.background": "#e1e2e7",
      "terminal.foreground": "#343b58",
      "terminal.selectionBackground": "#c6d7ff",
      "terminalCursor.foreground": "#2e7de9",
      "editorLineNumber.foreground": "#8990b3",
      "editorGutter.addedBackground": "#587539",
      "editorGutter.modifiedBackground": "#8c6c3e",
      "editorGutter.deletedBackground": "#c64343",
      "textLink.foreground": "#2e7de9",
      "badge.background": "#c4c8d8",
      "badge.foreground": "#343b58",
      "terminal.ansiBlack": "#7e8086",
      "terminal.ansiRed": "#f52561",
      "terminal.ansiGreen": "#587539",
      "terminal.ansiYellow": "#8c6c3e",
      "terminal.ansiBlue": "#2e7de9",
      "terminal.ansiMagenta": "#9854f1",
      "terminal.ansiCyan": "#007197",
      "terminal.ansiWhite": "#6172b0",
      "terminal.ansiBrightBlack": "#767dab",
      "terminal.ansiBrightRed": "#ff003e",
      "terminal.ansiBrightGreen": "#5c8524",
      "terminal.ansiBrightYellow": "#a27629",
      "terminal.ansiBrightBlue": "#1a7bff",
      "terminal.ansiBrightMagenta": "#9e58ff",
      "terminal.ansiBrightCyan": "#007ea8",
      "terminal.ansiBrightWhite": "#3760bf"
    },
    "syntax": {
      "keyword": "#343b58",
      "string": "#587539",
      "comment": "#848cb5",
      "number": "#965027",
      "function": "#166775",
      "operator": "#343b58",
      "type": "#b15c00",
      "tag": "#343b58"
    },
    "diff": {
      "inserted": "#587539",
      "removed": "#c64343"
    },
    "label": "Tokyo Day"
  }
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
