/**
 * VS Code light 主题 preset 数据 —— 2026-09-08 浅色扩充批(勿手改,说明见 ./index.ts)。
 * 源:各主题官方仓库一手 json / Kanagawa 官方色板 / One Half·Tomorrow·Xcode 经典色板;
 * terminal.ansi* 按浅底可读适配(16 槽对 terminal 背景 WCAG 对比度 ≥3:1,详见 spec)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART6 = {
  "vscode-bluloco-light": {
    "id": "vscode-bluloco-light",
    "appearance": "light",
    "label": "Bluloco Light",
    "colors": {
      "foreground": "#383a42",
      "editor.background": "#f9f9f9",
      "editor.foreground": "#383a42",
      "sideBar.background": "#e8e8e8",
      "sideBar.foreground": "#383a42",
      "panel.background": "#e8e8e8",
      "panel.border": "#d5d7d8",
      "input.background": "#f9f9f9",
      "input.foreground": "#383a42",
      "input.border": "#d5d7d8",
      "button.background": "#0083c0",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#d5d7d8",
      "button.secondaryForeground": "#0083c0",
      "dropdown.background": "#e8e8e8",
      "dropdown.border": "#d5d7d8",
      "editorWidget.background": "#e8e8e8",
      "list.hoverBackground": "#f1f1f1",
      "list.activeSelectionBackground": "#00a7f5",
      "list.activeSelectionForeground": "#ffffff",
      "activityBar.background": "#f1f1f1",
      "activityBar.foreground": "#383a42",
      "statusBar.background": "#ebebeb",
      "statusBar.foreground": "#383a42",
      "titleBar.activeBackground": "#c2c4c7",
      "titleBar.activeForeground": "#383a42",
      "terminalCursor.foreground": "#f31459",
      "editorLineNumber.foreground": "#a0a1a7",
      "editorGutter.addedBackground": "#3cbc66",
      "editorGutter.modifiedBackground": "#0099e1",
      "editorGutter.deletedBackground": "#a05a48",
      "textLink.foreground": "#0099e1",
      "badge.background": "#0099e1",
      "badge.foreground": "#ffffff",
      "terminal.ansiBlack": "#383a42",
      "terminal.ansiRed": "#d52753",
      "terminal.ansiGreen": "#23974a",
      "terminal.ansiYellow": "#df631c",
      "terminal.ansiBlue": "#275fe4",
      "terminal.ansiMagenta": "#823ff1",
      "terminal.ansiCyan": "#26608c",
      "terminal.ansiWhite": "#909097",
      "terminal.ansiBrightBlack": "#676a77",
      "terminal.ansiBrightRed": "#eb5b75",
      "terminal.ansiBrightGreen": "#339f56",
      "terminal.ansiBrightYellow": "#a78a2a",
      "terminal.ansiBrightBlue": "#0099e1",
      "terminal.ansiBrightMagenta": "#ce33c0",
      "terminal.ansiBrightCyan": "#6d92ba",
      "terminal.ansiBrightWhite": "#8b8b8b",
      "descriptionForeground": "#383a42",
      "terminal.background": "#f9f9f9",
      "terminal.selectionBackground": "#00a7f5"
    },
    "syntax": {
      "keyword": "#0098dd",
      "string": "#c5a332",
      "comment": "#a0a1a7",
      "number": "#ce33c0",
      "function": "#23974a",
      "operator": "#7a82da",
      "type": "#d52753",
      "tag": "#275fe4"
    },
    "diff": {
      "inserted": "#23974a",
      "removed": "#a05a48"
    }
  },
  "vscode-winteriscoming-light": {
    "id": "vscode-winteriscoming-light",
    "appearance": "light",
    "label": "Winter is Coming Light",
    "colors": {
      "foreground": "#1857a4",
      "editor.background": "#ffffff",
      "editor.foreground": "#236ebf",
      "sideBar.background": "#f3f3f3",
      "sideBar.foreground": "#0d3464",
      "panel.background": "#ffffff",
      "panel.border": "#49a7cf",
      "input.background": "#eeeeee",
      "input.foreground": "#111111",
      "input.border": "#5f7e97",
      "button.background": "#03648a",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#d8d8d8",
      "button.secondaryForeground": "#1857a4",
      "dropdown.background": "#eeeeee",
      "dropdown.border": "#2f86d2",
      "editorWidget.background": "#dddddd",
      "list.hoverBackground": "#cccccc",
      "list.activeSelectionBackground": "#219fd5",
      "activityBar.foreground": "#99d0f7",
      "statusBar.background": "#2f86d2",
      "titleBar.activeBackground": "#112233",
      "titleBar.activeForeground": "#eeefff",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#403f53",
      "terminal.selectionBackground": "#4373c2",
      "terminalCursor.foreground": "#219fd5",
      "editorLineNumber.foreground": "#2f86d2",
      "textLink.foreground": "#236ebf",
      "badge.background": "#219fd5",
      "badge.foreground": "#ffffff",
      "terminal.ansiBlack": "#011627",
      "terminal.ansiRed": "#de3d3b",
      "terminal.ansiGreen": "#08916a",
      "terminal.ansiYellow": "#a78a2a",
      "terminal.ansiBlue": "#236ebf",
      "terminal.ansiMagenta": "#7c4dff",
      "terminal.ansiCyan": "#0097a7",
      "terminal.ansiWhite": "#7e8993",
      "terminal.ansiBrightBlack": "#403f53",
      "terminal.ansiBrightRed": "#e36363",
      "terminal.ansiBrightGreen": "#39a289",
      "terminal.ansiBrightYellow": "#a68b31",
      "terminal.ansiBrightBlue": "#4e8cdf",
      "terminal.ansiBrightMagenta": "#b15a91",
      "terminal.ansiBrightCyan": "#009fb3",
      "terminal.ansiBrightWhite": "#403f53",
      "descriptionForeground": "#403f53",
      "statusBar.foreground": "#403f53",
      "activityBar.background": "#f3f3f3",
      "editorGutter.modifiedBackground": "#03648a",
      "list.activeSelectionForeground": "#403f53"
    },
    "syntax": {
      "keyword": "#0991b6",
      "string": "#a44185",
      "comment": "#357b42",
      "number": "#174781",
      "function": "#b1108e",
      "operator": "#7b30d0",
      "type": "#0444ac",
      "tag": "#0444ac"
    },
    "diff": {
      "inserted": "#a44185",
      "removed": "#0444ac"
    }
  },
  "vscode-alabaster": {
    "id": "vscode-alabaster",
    "appearance": "light",
    "label": "Alabaster",
    "colors": {
      "editor.background": "#f7f7f7",
      "editor.foreground": "#000000",
      "sideBar.background": "#f0f0f0",
      "panel.background": "#f0f0f0",
      "list.activeSelectionBackground": "#dddddd",
      "list.activeSelectionForeground": "#000000",
      "activityBar.background": "#f0f0f0",
      "activityBar.foreground": "#007acc",
      "statusBar.background": "#dddddd",
      "statusBar.foreground": "#474747",
      "editorLineNumber.foreground": "#9da39a",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#aa3731",
      "terminal.ansiGreen": "#448c27",
      "terminal.ansiYellow": "#bb8400",
      "terminal.ansiBlue": "#325cc0",
      "terminal.ansiMagenta": "#7a3e9d",
      "terminal.ansiCyan": "#0083b2",
      "terminal.ansiWhite": "#858585",
      "terminal.ansiBrightBlack": "#777777",
      "terminal.ansiBrightRed": "#f05050",
      "terminal.ansiBrightGreen": "#4b9e00",
      "terminal.ansiBrightYellow": "#b78643",
      "terminal.ansiBrightBlue": "#007acc",
      "terminal.ansiBrightMagenta": "#d446d4",
      "terminal.ansiBrightCyan": "#009cbb",
      "terminal.ansiBrightWhite": "#8f8f8f",
      "descriptionForeground": "#000000",
      "sideBar.foreground": "#000000",
      "badge.foreground": "#000000",
      "button.secondaryBackground": "#e3e3e3",
      "button.secondaryForeground": "#000000",
      "terminal.background": "#f7f7f7",
      "terminalCursor.foreground": "#000000",
      "terminal.selectionBackground": "#dddddd",
      "editorWidget.background": "#f0f0f0",
      "input.background": "#ffffff",
      "input.foreground": "#000000",
      "list.hoverBackground": "#ebebeb",
      "titleBar.activeBackground": "#f0f0f0",
      "titleBar.activeForeground": "#000000",
      "panel.border": "#d2d2d2",
      "badge.background": "#d9d9d9",
      "dropdown.background": "#ffffff",
      "foreground": "#000000"
    },
    "syntax": {
      "string": "#448c27",
      "comment": "#aa3731",
      "number": "#7a3e9d",
      "keyword": "#325cc0",
      "function": "#325cc0",
      "operator": "#000000",
      "type": "#7a3e9d",
      "tag": "#325cc0"
    },
    "diff": {
      "inserted": "#448c27",
      "removed": "#aa3731"
    }
  }
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
