/**
 * VS Code light 主题 preset 数据 —— 2026-09-08 浅色扩充批(勿手改,说明见 ./index.ts)。
 * 源:各主题官方仓库一手 json / Kanagawa 官方色板 / One Half·Tomorrow·Xcode 经典色板;
 * terminal.ansi* 按浅底可读适配(16 槽对 terminal 背景 WCAG 对比度 ≥3:1,方法同 light1-3)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART4 = {
  "vscode-one-half-light": {
    "id": "vscode-one-half-light",
    "appearance": "light",
    "label": "One Half Light",
    "colors": {
      "foreground": "#383a42",
      "editor.background": "#fafafa",
      "editor.foreground": "#383a42",
      "sideBar.background": "#fafafa",
      "sideBar.foreground": "#383a42",
      "panel.background": "#fafafa",
      "panel.border": "#ededed",
      "input.background": "#ffffff",
      "input.foreground": "#383a42",
      "input.border": "#ededed",
      "button.background": "#0184bc",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e8e8e8",
      "button.secondaryForeground": "#383a42",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#ededed",
      "editorWidget.background": "#f5f5f5",
      "list.hoverBackground": "#f0f0f0",
      "list.activeSelectionBackground": "#e8e8e8",
      "list.activeSelectionForeground": "#000000",
      "activityBar.background": "#fafafa",
      "activityBar.foreground": "#383a42",
      "statusBar.background": "#f5f5f5",
      "statusBar.foreground": "#383a42",
      "titleBar.activeBackground": "#f5f5f5",
      "titleBar.activeForeground": "#383a42",
      "terminal.background": "#fafafa",
      "terminal.foreground": "#383a42",
      "terminal.selectionBackground": "#bfceff",
      "terminalCursor.foreground": "#383a42",
      "editorLineNumber.foreground": "#9d9d9d",
      "editorGutter.addedBackground": "#50a14f",
      "editorGutter.modifiedBackground": "#0184bc",
      "editorGutter.deletedBackground": "#e45649",
      "textLink.foreground": "#0184bc",
      "badge.background": "#e0e0e0",
      "badge.foreground": "#383a42",
      "terminal.ansiBlack": "#383a42",
      "terminal.ansiRed": "#e45649",
      "terminal.ansiGreen": "#50a14f",
      "terminal.ansiYellow": "#c18401",
      "terminal.ansiBlue": "#0184bc",
      "terminal.ansiMagenta": "#a626a4",
      "terminal.ansiCyan": "#0997b3",
      "terminal.ansiWhite": "#676a75",
      "terminal.ansiBrightBlack": "#4f525e",
      "terminal.ansiBrightRed": "#e45649",
      "terminal.ansiBrightGreen": "#50a14f",
      "terminal.ansiBrightYellow": "#c18401",
      "terminal.ansiBrightBlue": "#0184bc",
      "terminal.ansiBrightMagenta": "#a626a4",
      "terminal.ansiBrightCyan": "#0997b3",
      "terminal.ansiBrightWhite": "#4f525e"
    },
    "syntax": {
      "keyword": "#a626a4",
      "string": "#50a14f",
      "comment": "#898b8f",
      "number": "#b76b01",
      "function": "#6182b8",
      "operator": "#383a42",
      "type": "#0184bc",
      "tag": "#e45649"
    },
    "diff": {
      "inserted": "#50a14f",
      "removed": "#e45649"
    }
  },
  "vscode-tomorrow-light": {
    "id": "vscode-tomorrow-light",
    "appearance": "light",
    "label": "Tomorrow",
    "colors": {
      "foreground": "#4d4d4c",
      "editor.background": "#ffffff",
      "editor.foreground": "#4d4d4c",
      "sideBar.background": "#efefef",
      "sideBar.foreground": "#4d4d4c",
      "panel.background": "#ffffff",
      "panel.border": "#d6d6d6",
      "input.background": "#ffffff",
      "input.foreground": "#4d4d4c",
      "input.border": "#d6d6d6",
      "button.background": "#4271ae",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e0e0e0",
      "button.secondaryForeground": "#4d4d4c",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#d6d6d6",
      "editorWidget.background": "#efefef",
      "list.hoverBackground": "#efefef",
      "list.activeSelectionBackground": "#d6d6d6",
      "list.activeSelectionForeground": "#4d4d4c",
      "activityBar.background": "#efefef",
      "activityBar.foreground": "#4d4d4c",
      "statusBar.background": "#efefef",
      "statusBar.foreground": "#4d4d4c",
      "titleBar.activeBackground": "#efefef",
      "titleBar.activeForeground": "#4d4d4c",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#4d4d4c",
      "terminal.selectionBackground": "#d6d6d6",
      "terminalCursor.foreground": "#4d4d4c",
      "editorLineNumber.foreground": "#8e908c",
      "editorGutter.addedBackground": "#718c00",
      "editorGutter.modifiedBackground": "#4271ae",
      "editorGutter.deletedBackground": "#c82829",
      "textLink.foreground": "#4271ae",
      "badge.background": "#d6d6d6",
      "badge.foreground": "#4d4d4c",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#c82829",
      "terminal.ansiGreen": "#718c00",
      "terminal.ansiYellow": "#8e7000",
      "terminal.ansiBlue": "#4271ae",
      "terminal.ansiMagenta": "#8959a8",
      "terminal.ansiCyan": "#3e999f",
      "terminal.ansiWhite": "#8e908c",
      "terminal.ansiBrightBlack": "#8e908c",
      "terminal.ansiBrightRed": "#c82829",
      "terminal.ansiBrightGreen": "#718c00",
      "terminal.ansiBrightYellow": "#8e7000",
      "terminal.ansiBrightBlue": "#4271ae",
      "terminal.ansiBrightMagenta": "#8959a8",
      "terminal.ansiBrightCyan": "#3e999f",
      "terminal.ansiBrightWhite": "#4d4d4c"
    },
    "syntax": {
      "keyword": "#8959a8",
      "string": "#718c00",
      "comment": "#8e908c",
      "number": "#f5871f",
      "function": "#4271ae",
      "operator": "#4d4d4c",
      "type": "#c82829",
      "tag": "#c82829"
    },
    "diff": {
      "inserted": "#718c00",
      "removed": "#c82829"
    }
  },
  "vscode-xcode-light": {
    "id": "vscode-xcode-light",
    "appearance": "light",
    "label": "Xcode Default Light",
    "colors": {
      "foreground": "#000000",
      "editor.background": "#ffffff",
      "editor.foreground": "#000000",
      "sideBar.background": "#f5f5f5",
      "sideBar.foreground": "#000000",
      "panel.background": "#f5f5f5",
      "panel.border": "#dedede",
      "input.background": "#ffffff",
      "input.foreground": "#000000",
      "input.border": "#dedede",
      "button.background": "#007aff",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e8e8e8",
      "button.secondaryForeground": "#000000",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#dedede",
      "editorWidget.background": "#f5f5f5",
      "list.hoverBackground": "#ebebeb",
      "list.activeSelectionBackground": "#dcdcdc",
      "list.activeSelectionForeground": "#000000",
      "activityBar.background": "#f5f5f5",
      "activityBar.foreground": "#000000",
      "statusBar.background": "#f5f5f5",
      "statusBar.foreground": "#000000",
      "titleBar.activeBackground": "#f5f5f5",
      "titleBar.activeForeground": "#000000",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#000000",
      "terminal.selectionBackground": "#b3d7ff",
      "terminalCursor.foreground": "#000000",
      "editorLineNumber.foreground": "#a0a0a0",
      "editorGutter.addedBackground": "#177500",
      "editorGutter.modifiedBackground": "#1c00cf",
      "editorGutter.deletedBackground": "#c41a16",
      "textLink.foreground": "#007aff",
      "badge.background": "#e9e9e9",
      "badge.foreground": "#000000",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#c41a16",
      "terminal.ansiGreen": "#177500",
      "terminal.ansiYellow": "#8e7000",
      "terminal.ansiBlue": "#1c00cf",
      "terminal.ansiMagenta": "#aa0d91",
      "terminal.ansiCyan": "#3f6e74",
      "terminal.ansiWhite": "#6e6e73",
      "terminal.ansiBrightBlack": "#6e6e73",
      "terminal.ansiBrightRed": "#c41a16",
      "terminal.ansiBrightGreen": "#177500",
      "terminal.ansiBrightYellow": "#8e7000",
      "terminal.ansiBrightBlue": "#1c00cf",
      "terminal.ansiBrightMagenta": "#aa0d91",
      "terminal.ansiBrightCyan": "#3f6e74",
      "terminal.ansiBrightWhite": "#3a3a3c"
    },
    "syntax": {
      "keyword": "#aa0d91",
      "string": "#c41a16",
      "comment": "#177500",
      "number": "#1c00cf",
      "function": "#3f6e74",
      "operator": "#000000",
      "type": "#5b269a",
      "tag": "#aa0d91"
    },
    "diff": {
      "inserted": "#177500",
      "removed": "#c41a16"
    }
  }
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
