/**
 * VS Code light 主题 preset 数据 —— 移植自 codemoss features/theme/constants/vscodeThemePresets.ts(勿手改,说明见 ./index.ts)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART2 = {
  "vscode-tokyo-day": {
    "id": "vscode-tokyo-day",
    "appearance": "light",
    "colors": {
      "foreground": "#343b58",
      "descriptionForeground": "#5a607f",
      "editor.background": "#e1e2e7",
      "editor.foreground": "#343b58",
      "sideBar.background": "#d5d6db",
      "sideBar.foreground": "#343b58",
      "panel.background": "#e9e9ed",
      "panel.border": "#c4c8d8",
      "input.background": "#dfe1e8",
      "input.foreground": "#343b58",
      "input.border": "#b8bfd6",
      "button.background": "#2e7de9",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#cfd2e1",
      "button.secondaryForeground": "#343b58",
      "dropdown.background": "#dfe1e8",
      "dropdown.border": "#b8bfd6",
      "editorWidget.background": "#dfe1e8",
      "list.hoverBackground": "#d5d6db",
      "list.activeSelectionBackground": "#c6d7ff",
      "list.activeSelectionForeground": "#1f2335",
      "activityBar.background": "#cfd2e1",
      "activityBar.foreground": "#343b58",
      "statusBar.background": "#d5d6db",
      "statusBar.foreground": "#343b58",
      "titleBar.activeBackground": "#e1e2e7",
      "titleBar.activeForeground": "#343b58",
      "terminal.background": "#e1e2e7",
      "terminal.foreground": "#343b58",
      "terminal.selectionBackground": "#c6d7ff",
      "terminalCursor.foreground": "#2e7de9",
      "editorLineNumber.foreground": "#8990b3",
      "editorGutter.addedBackground": "#587539",
      "editorGutter.modifiedBackground": "#8c6c3e",
      "editorGutter.deletedBackground": "#c64343",
      "textLink.foreground": "#2e7de9",
      "badge.background": "#c4c8d8",
      "badge.foreground": "#343b58"
    },
    "syntax": {
      "keyword": "#343b58",
      "string": "#587539",
      "comment": "#848cb5",
      "number": "#965027",
      "function": "#166775",
      "operator": "#343b58",
      "type": "#b15c00",
      "tag": "#343b58"
    },
    "diff": {
      "inserted": "#587539",
      "removed": "#c64343"
    },
    "label": "Tokyo Day"
  },
  "vscode-rose-pine-dawn": {
    "id": "vscode-rose-pine-dawn",
    "appearance": "light",
    "colors": {
      "foreground": "#575279",
      "descriptionForeground": "#797593",
      "editor.background": "#faf4ed",
      "editor.foreground": "#575279",
      "sideBar.background": "#fffaf3",
      "sideBar.foreground": "#575279",
      "panel.background": "#f2e9e1",
      "panel.border": "#dfdad9",
      "input.background": "#fffaf3",
      "input.foreground": "#575279",
      "input.border": "#cecacd",
      "button.background": "#286983",
      "button.foreground": "#fffaf3",
      "button.secondaryBackground": "#f2e9e1",
      "button.secondaryForeground": "#575279",
      "dropdown.background": "#fffaf3",
      "dropdown.border": "#cecacd",
      "editorWidget.background": "#fffaf3",
      "list.hoverBackground": "#f2e9e1",
      "list.activeSelectionBackground": "#eadfd7",
      "list.activeSelectionForeground": "#575279",
      "activityBar.background": "#f2e9e1",
      "activityBar.foreground": "#575279",
      "statusBar.background": "#f2e9e1",
      "statusBar.foreground": "#575279",
      "titleBar.activeBackground": "#faf4ed",
      "titleBar.activeForeground": "#575279",
      "terminal.background": "#faf4ed",
      "terminal.foreground": "#575279",
      "terminal.selectionBackground": "#eadfd7",
      "terminalCursor.foreground": "#286983",
      "editorLineNumber.foreground": "#9893a5",
      "editorGutter.addedBackground": "#56949f",
      "editorGutter.modifiedBackground": "#ea9d34",
      "editorGutter.deletedBackground": "#b4637a",
      "textLink.foreground": "#286983",
      "badge.background": "#dfdad9",
      "badge.foreground": "#575279"
    },
    "syntax": {
      "keyword": "#286983",
      "string": "#d7827e",
      "comment": "#9893a5",
      "number": "#ea9d34",
      "function": "#907aa9",
      "operator": "#5c5a77",
      "type": "#d7827e",
      "tag": "#286983"
    },
    "diff": {
      "inserted": "#56949f",
      "removed": "#b4637a"
    },
    "label": "Rose Pine Dawn"
  },
  "vscode-everforest-light": {
    "id": "vscode-everforest-light",
    "appearance": "light",
    "colors": {
      "foreground": "#5c6a72",
      "descriptionForeground": "#7a8478",
      "editor.background": "#fdf6e3",
      "editor.foreground": "#5c6a72",
      "sideBar.background": "#efebd4",
      "sideBar.foreground": "#5c6a72",
      "panel.background": "#f4f0d9",
      "panel.border": "#d8d3ba",
      "input.background": "#efebd4",
      "input.foreground": "#5c6a72",
      "input.border": "#c9c2a7",
      "button.background": "#3a94c5",
      "button.foreground": "#fff9e8",
      "button.secondaryBackground": "#e6e2cc",
      "button.secondaryForeground": "#5c6a72",
      "dropdown.background": "#efebd4",
      "dropdown.border": "#c9c2a7",
      "editorWidget.background": "#efebd4",
      "list.hoverBackground": "#e6e2cc",
      "list.activeSelectionBackground": "#d8d3ba",
      "list.activeSelectionForeground": "#3c4841",
      "activityBar.background": "#e6e2cc",
      "activityBar.foreground": "#5c6a72",
      "statusBar.background": "#efebd4",
      "statusBar.foreground": "#5c6a72",
      "titleBar.activeBackground": "#fdf6e3",
      "titleBar.activeForeground": "#5c6a72",
      "terminal.background": "#fdf6e3",
      "terminal.foreground": "#5c6a72",
      "terminal.selectionBackground": "#d8d3ba",
      "terminalCursor.foreground": "#3a94c5",
      "editorLineNumber.foreground": "#a6b0a0",
      "editorGutter.addedBackground": "#8da101",
      "editorGutter.modifiedBackground": "#dfa000",
      "editorGutter.deletedBackground": "#f85552",
      "textLink.foreground": "#3a94c5",
      "badge.background": "#d8d3ba",
      "badge.foreground": "#5c6a72"
    },
    "syntax": {
      "keyword": "#8da101",
      "string": "#7a8943",
      "comment": "#a0b58c",
      "number": "#df69ba",
      "function": "#3a94c5",
      "operator": "#5c6a72",
      "type": "#b47152",
      "tag": "#8da101"
    },
    "diff": {
      "inserted": "#8da101",
      "removed": "#f85552"
    },
    "label": "Everforest Light"
  },
  "vscode-ayu-light": {
    "id": "vscode-ayu-light",
    "appearance": "light",
    "colors": {
      "foreground": "#5c6773",
      "descriptionForeground": "#828c99",
      "editor.background": "#fafafa",
      "editor.foreground": "#5c6773",
      "sideBar.background": "#f0f0f0",
      "sideBar.foreground": "#5c6773",
      "panel.background": "#f5f5f5",
      "panel.border": "#d9d9d9",
      "input.background": "#ffffff",
      "input.foreground": "#5c6773",
      "input.border": "#d9d9d9",
      "button.background": "#55b4d4",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e8e8e8",
      "button.secondaryForeground": "#5c6773",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#d9d9d9",
      "editorWidget.background": "#ffffff",
      "list.hoverBackground": "#eeeeee",
      "list.activeSelectionBackground": "#d3edf6",
      "list.activeSelectionForeground": "#263238",
      "activityBar.background": "#e8e8e8",
      "activityBar.foreground": "#5c6773",
      "statusBar.background": "#f0f0f0",
      "statusBar.foreground": "#5c6773",
      "titleBar.activeBackground": "#fafafa",
      "titleBar.activeForeground": "#5c6773",
      "terminal.background": "#fafafa",
      "terminal.foreground": "#5c6773",
      "terminal.selectionBackground": "#d3edf6",
      "terminalCursor.foreground": "#55b4d4",
      "editorLineNumber.foreground": "#abb0b6",
      "editorGutter.addedBackground": "#86b300",
      "editorGutter.modifiedBackground": "#f29718",
      "editorGutter.deletedBackground": "#f07171",
      "textLink.foreground": "#55b4d4",
      "badge.background": "#d9d9d9",
      "badge.foreground": "#5c6773"
    },
    "syntax": {
      "keyword": "#a626a4",
      "string": "#50a04f",
      "comment": "#a0ada0",
      "number": "#b75c00",
      "function": "#399ee6",
      "operator": "#5c6166",
      "type": "#a626a4",
      "tag": "#a626a4"
    },
    "diff": {
      "inserted": "#86b300",
      "removed": "#f07171"
    },
    "label": "Ayu Light"
  }
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
