/**
 * VS Code light 主题 preset 数据 —— 移植自 codemoss(勿手改,说明见 ./index.ts)。
 * terminal.ansi* 16 色浅底可读适配:色相取自各主题官方终端色板(Rosé Pine 官方 kitty /
 * everforest 官方 vim / ayu 官方 vscode),对比度不足处保 H/S 降 L 至 WCAG ≥3:1。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART3 = {
  "vscode-rose-pine-dawn": {
    "id": "vscode-rose-pine-dawn",
    "appearance": "light",
    "colors": {
      "foreground": "#575279",
      "descriptionForeground": "#797593",
      "editor.background": "#faf4ed",
      "editor.foreground": "#575279",
      "sideBar.background": "#fffaf3",
      "sideBar.foreground": "#575279",
      "panel.background": "#f2e9e1",
      "panel.border": "#dfdad9",
      "input.background": "#fffaf3",
      "input.foreground": "#575279",
      "input.border": "#cecacd",
      "button.background": "#286983",
      "button.foreground": "#fffaf3",
      "button.secondaryBackground": "#f2e9e1",
      "button.secondaryForeground": "#575279",
      "dropdown.background": "#fffaf3",
      "dropdown.border": "#cecacd",
      "editorWidget.background": "#fffaf3",
      "list.hoverBackground": "#f2e9e1",
      "list.activeSelectionBackground": "#eadfd7",
      "list.activeSelectionForeground": "#575279",
      "activityBar.background": "#f2e9e1",
      "activityBar.foreground": "#575279",
      "statusBar.background": "#f2e9e1",
      "statusBar.foreground": "#575279",
      "titleBar.activeBackground": "#faf4ed",
      "titleBar.activeForeground": "#575279",
      "terminal.background": "#faf4ed",
      "terminal.foreground": "#575279",
      "terminal.selectionBackground": "#eadfd7",
      "terminalCursor.foreground": "#286983",
      "editorLineNumber.foreground": "#9893a5",
      "editorGutter.addedBackground": "#56949f",
      "editorGutter.modifiedBackground": "#ea9d34",
      "editorGutter.deletedBackground": "#b4637a",
      "textLink.foreground": "#286983",
      "badge.background": "#dfdad9",
      "badge.foreground": "#575279",
      "terminal.ansiBlack": "#575279",
      "terminal.ansiRed": "#b4637a",
      "terminal.ansiGreen": "#286983",
      "terminal.ansiYellow": "#c77b15",
      "terminal.ansiBlue": "#56949f",
      "terminal.ansiMagenta": "#907aa9",
      "terminal.ansiCyan": "#d1716c",
      "terminal.ansiWhite": "#575279",
      "terminal.ansiBrightBlack": "#8f8a9e",
      "terminal.ansiBrightRed": "#b4637a",
      "terminal.ansiBrightGreen": "#286983",
      "terminal.ansiBrightYellow": "#c77b15",
      "terminal.ansiBrightBlue": "#56949f",
      "terminal.ansiBrightMagenta": "#907aa9",
      "terminal.ansiBrightCyan": "#d1716c",
      "terminal.ansiBrightWhite": "#575279"
    },
    "syntax": {
      "keyword": "#286983",
      "string": "#d7827e",
      "comment": "#9893a5",
      "number": "#ea9d34",
      "function": "#907aa9",
      "operator": "#5c5a77",
      "type": "#d7827e",
      "tag": "#286983"
    },
    "diff": {
      "inserted": "#56949f",
      "removed": "#b4637a"
    },
    "label": "Rose Pine Dawn"
  },
  "vscode-everforest-light": {
    "id": "vscode-everforest-light",
    "appearance": "light",
    "colors": {
      "foreground": "#5c6a72",
      "descriptionForeground": "#7a8478",
      "editor.background": "#fdf6e3",
      "editor.foreground": "#5c6a72",
      "sideBar.background": "#efebd4",
      "sideBar.foreground": "#5c6a72",
      "panel.background": "#f4f0d9",
      "panel.border": "#d8d3ba",
      "input.background": "#efebd4",
      "input.foreground": "#5c6a72",
      "input.border": "#c9c2a7",
      "button.background": "#3a94c5",
      "button.foreground": "#fff9e8",
      "button.secondaryBackground": "#e6e2cc",
      "button.secondaryForeground": "#5c6a72",
      "dropdown.background": "#efebd4",
      "dropdown.border": "#c9c2a7",
      "editorWidget.background": "#efebd4",
      "list.hoverBackground": "#e6e2cc",
      "list.activeSelectionBackground": "#d8d3ba",
      "list.activeSelectionForeground": "#3c4841",
      "activityBar.background": "#e6e2cc",
      "activityBar.foreground": "#5c6a72",
      "statusBar.background": "#efebd4",
      "statusBar.foreground": "#5c6a72",
      "titleBar.activeBackground": "#fdf6e3",
      "titleBar.activeForeground": "#5c6a72",
      "terminal.background": "#fdf6e3",
      "terminal.foreground": "#5c6a72",
      "terminal.selectionBackground": "#d8d3ba",
      "terminalCursor.foreground": "#3a94c5",
      "editorLineNumber.foreground": "#a6b0a0",
      "editorGutter.addedBackground": "#8da101",
      "editorGutter.modifiedBackground": "#dfa000",
      "editorGutter.deletedBackground": "#f85552",
      "textLink.foreground": "#3a94c5",
      "badge.background": "#d8d3ba",
      "badge.foreground": "#5c6a72",
      "terminal.ansiBlack": "#5c6a72",
      "terminal.ansiRed": "#f85451",
      "terminal.ansiGreen": "#849601",
      "terminal.ansiYellow": "#b98400",
      "terminal.ansiBlue": "#3a94c5",
      "terminal.ansiMagenta": "#dd5fb5",
      "terminal.ansiCyan": "#339f76",
      "terminal.ansiWhite": "#849182",
      "terminal.ansiBrightBlack": "#5c6a72",
      "terminal.ansiBrightRed": "#f85451",
      "terminal.ansiBrightGreen": "#849601",
      "terminal.ansiBrightYellow": "#b98400",
      "terminal.ansiBrightBlue": "#3a94c5",
      "terminal.ansiBrightMagenta": "#dd5fb5",
      "terminal.ansiBrightCyan": "#339f76",
      "terminal.ansiBrightWhite": "#849182"
    },
    "syntax": {
      "keyword": "#8da101",
      "string": "#7a8943",
      "comment": "#a0b58c",
      "number": "#df69ba",
      "function": "#3a94c5",
      "operator": "#5c6a72",
      "type": "#b47152",
      "tag": "#8da101"
    },
    "diff": {
      "inserted": "#8da101",
      "removed": "#f85552"
    },
    "label": "Everforest Light"
  },
  "vscode-ayu-light": {
    "id": "vscode-ayu-light",
    "appearance": "light",
    "colors": {
      "foreground": "#5c6773",
      "descriptionForeground": "#828c99",
      "editor.background": "#fafafa",
      "editor.foreground": "#5c6773",
      "sideBar.background": "#f0f0f0",
      "sideBar.foreground": "#5c6773",
      "panel.background": "#f5f5f5",
      "panel.border": "#d9d9d9",
      "input.background": "#ffffff",
      "input.foreground": "#5c6773",
      "input.border": "#d9d9d9",
      "button.background": "#55b4d4",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e8e8e8",
      "button.secondaryForeground": "#5c6773",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#d9d9d9",
      "editorWidget.background": "#ffffff",
      "list.hoverBackground": "#eeeeee",
      "list.activeSelectionBackground": "#d3edf6",
      "list.activeSelectionForeground": "#263238",
      "activityBar.background": "#e8e8e8",
      "activityBar.foreground": "#5c6773",
      "statusBar.background": "#f0f0f0",
      "statusBar.foreground": "#5c6773",
      "titleBar.activeBackground": "#fafafa",
      "titleBar.activeForeground": "#5c6773",
      "terminal.background": "#fafafa",
      "terminal.foreground": "#5c6773",
      "terminal.selectionBackground": "#d3edf6",
      "terminalCursor.foreground": "#55b4d4",
      "editorLineNumber.foreground": "#abb0b6",
      "editorGutter.addedBackground": "#86b300",
      "editorGutter.modifiedBackground": "#f29718",
      "editorGutter.deletedBackground": "#f07171",
      "textLink.foreground": "#55b4d4",
      "badge.background": "#d9d9d9",
      "badge.foreground": "#5c6773",
      "terminal.ansiBlack": "#000000",
      "terminal.ansiRed": "#ef6163",
      "terminal.ansiGreen": "#5aa137",
      "terminal.ansiYellow": "#c08500",
      "terminal.ansiBlue": "#1c98d8",
      "terminal.ansiMagenta": "#a176cb",
      "terminal.ansiCyan": "#3ca17f",
      "terminal.ansiWhite": "#909090",
      "terminal.ansiBrightBlack": "#686868",
      "terminal.ansiBrightRed": "#ee6262",
      "terminal.ansiBrightGreen": "#769d00",
      "terminal.ansiBrightYellow": "#bf8500",
      "terminal.ansiBrightBlue": "#1998d9",
      "terminal.ansiBrightMagenta": "#a37acc",
      "terminal.ansiBrightCyan": "#3aa17f",
      "terminal.ansiBrightWhite": "#909090"
    },
    "syntax": {
      "keyword": "#a626a4",
      "string": "#50a04f",
      "comment": "#a0ada0",
      "number": "#b75c00",
      "function": "#399ee6",
      "operator": "#5c6166",
      "type": "#a626a4",
      "tag": "#a626a4"
    },
    "diff": {
      "inserted": "#86b300",
      "removed": "#f07171"
    },
    "label": "Ayu Light"
  }
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
