/**
 * VS Code light 主题 preset 数据 —— 移植自 codemoss features/theme/constants/vscodeThemePresets.ts(勿手改,说明见 ./index.ts)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART1 = {
  "vscode-light-modern": {
    "id": "vscode-light-modern",
    "appearance": "light",
    "colors": {
      "foreground": "#3b3b3b",
      "descriptionForeground": "#3b3b3b",
      "editor.background": "#ffffff",
      "editor.foreground": "#3b3b3b",
      "sideBar.background": "#f8f8f8",
      "sideBar.foreground": "#3b3b3b",
      "panel.background": "#f8f8f8",
      "panel.border": "#e5e5e5",
      "input.background": "#ffffff",
      "input.foreground": "#3b3b3b",
      "input.border": "#cecece",
      "button.background": "#005fb8",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e5e5e5",
      "button.secondaryForeground": "#3b3b3b",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#cecece",
      "editorWidget.background": "#f8f8f8",
      "list.hoverBackground": "#f2f2f2",
      "list.activeSelectionBackground": "#e8e8e8",
      "list.activeSelectionForeground": "#000000",
      "activityBar.background": "#f8f8f8",
      "activityBar.foreground": "#1f1f1f",
      "statusBar.background": "#f8f8f8",
      "statusBar.foreground": "#3b3b3b",
      "titleBar.activeBackground": "#f8f8f8",
      "titleBar.activeForeground": "#1e1e1e",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#3b3b3b",
      "terminal.selectionBackground": "#add6ff",
      "terminalCursor.foreground": "#005fb8",
      "editorLineNumber.foreground": "#6e7681",
      "editorGutter.addedBackground": "#2ea043",
      "editorGutter.modifiedBackground": "#005fb8",
      "editorGutter.deletedBackground": "#f85149",
      "textLink.foreground": "#005fb8",
      "badge.background": "#cccccc",
      "badge.foreground": "#3b3b3b"
    },
    "syntax": {
      "keyword": "#0000ff",
      "string": "#a31515",
      "comment": "#008000",
      "number": "#098658",
      "function": "#795e26",
      "operator": "#000000",
      "type": "#267f99",
      "tag": "#0000ff"
    },
    "diff": {
      "inserted": "#2ea043",
      "removed": "#f85149"
    },
    "label": "Light Modern"
  },
  "vscode-light-plus": {
    "id": "vscode-light-plus",
    "appearance": "light",
    "colors": {
      "foreground": "#3b3b3b",
      "descriptionForeground": "#616161",
      "editor.background": "#ffffff",
      "editor.foreground": "#000000",
      "sideBar.background": "#f3f3f3",
      "sideBar.foreground": "#3b3b3b",
      "panel.background": "#ffffff",
      "panel.border": "#d4d4d4",
      "input.background": "#ffffff",
      "input.foreground": "#3b3b3b",
      "input.border": "#cecece",
      "button.background": "#007acc",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#ececec",
      "button.secondaryForeground": "#000000",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#cecece",
      "editorWidget.background": "#f3f3f3",
      "list.hoverBackground": "#e8e8e8",
      "list.activeSelectionBackground": "#cce6ff",
      "list.activeSelectionForeground": "#000000",
      "activityBar.background": "#f3f3f3",
      "activityBar.foreground": "#424242",
      "statusBar.background": "#007acc",
      "statusBar.foreground": "#ffffff",
      "titleBar.activeBackground": "#dddddd",
      "titleBar.activeForeground": "#333333",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#3b3b3b",
      "terminal.selectionBackground": "#add6ff",
      "terminalCursor.foreground": "#000000",
      "editorLineNumber.foreground": "#237893",
      "editorGutter.addedBackground": "#2ea043",
      "editorGutter.modifiedBackground": "#007acc",
      "editorGutter.deletedBackground": "#cd3131",
      "textLink.foreground": "#006ab1",
      "badge.background": "#c4c4c4",
      "badge.foreground": "#333333"
    },
    "syntax": {
      "keyword": "#0000ff",
      "string": "#a31515",
      "comment": "#008000",
      "number": "#098658",
      "function": "#795e26",
      "operator": "#000000",
      "type": "#267f99",
      "tag": "#0000ff"
    },
    "diff": {
      "inserted": "#2ea043",
      "removed": "#cd3131"
    },
    "label": "Light+"
  },
  "vscode-github-light": {
    "id": "vscode-github-light",
    "appearance": "light",
    "colors": {
      "foreground": "#1f2328",
      "descriptionForeground": "#57606a",
      "editor.background": "#ffffff",
      "editor.foreground": "#1f2328",
      "sideBar.background": "#f6f8fa",
      "sideBar.foreground": "#1f2328",
      "panel.background": "#ffffff",
      "panel.border": "#d0d7de",
      "input.background": "#ffffff",
      "input.foreground": "#1f2328",
      "input.border": "#d0d7de",
      "button.background": "#0969da",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#f6f8fa",
      "button.secondaryForeground": "#1f2328",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#d0d7de",
      "editorWidget.background": "#ffffff",
      "list.hoverBackground": "#f3f4f6",
      "list.activeSelectionBackground": "#ddf4ff",
      "list.activeSelectionForeground": "#0b3d91",
      "activityBar.background": "#f6f8fa",
      "activityBar.foreground": "#24292f",
      "statusBar.background": "#f6f8fa",
      "statusBar.foreground": "#57606a",
      "titleBar.activeBackground": "#ffffff",
      "titleBar.activeForeground": "#1f2328",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#1f2328",
      "terminal.selectionBackground": "#b6e3ff",
      "terminalCursor.foreground": "#0969da",
      "editorLineNumber.foreground": "#8c959f",
      "editorGutter.addedBackground": "#1a7f37",
      "editorGutter.modifiedBackground": "#0969da",
      "editorGutter.deletedBackground": "#cf222e",
      "textLink.foreground": "#0969da",
      "badge.background": "#d0d7de",
      "badge.foreground": "#1f2328"
    },
    "syntax": {
      "keyword": "#cf222e",
      "string": "#0a3069",
      "comment": "#6e7781",
      "number": "#0550ae",
      "function": "#8250df",
      "operator": "#24292f",
      "type": "#953800",
      "tag": "#116329"
    },
    "diff": {
      "inserted": "#1a7f37",
      "removed": "#cf222e"
    },
    "label": "GitHub Light"
  },
  "vscode-solarized-light": {
    "id": "vscode-solarized-light",
    "appearance": "light",
    "colors": {
      "foreground": "#657b83",
      "descriptionForeground": "#6c7f86",
      "editor.background": "#fdf6e3",
      "editor.foreground": "#586e75",
      "sideBar.background": "#eee8d5",
      "sideBar.foreground": "#586e75",
      "panel.background": "#f7f0dd",
      "panel.border": "#d8cfb5",
      "input.background": "#fdf6e3",
      "input.foreground": "#586e75",
      "input.border": "#cfc7ad",
      "button.background": "#268bd2",
      "button.foreground": "#fdf6e3",
      "button.secondaryBackground": "#eee8d5",
      "button.secondaryForeground": "#586e75",
      "dropdown.background": "#fdf6e3",
      "dropdown.border": "#cfc7ad",
      "editorWidget.background": "#f7f0dd",
      "list.hoverBackground": "#f1ead7",
      "list.activeSelectionBackground": "#dce8ef",
      "list.activeSelectionForeground": "#073642",
      "activityBar.background": "#eee8d5",
      "activityBar.foreground": "#586e75",
      "statusBar.background": "#eee8d5",
      "statusBar.foreground": "#586e75",
      "titleBar.activeBackground": "#fdf6e3",
      "titleBar.activeForeground": "#586e75",
      "terminal.background": "#fdf6e3",
      "terminal.foreground": "#586e75",
      "terminal.selectionBackground": "#dce8ef",
      "terminalCursor.foreground": "#268bd2",
      "editorLineNumber.foreground": "#93a1a1",
      "editorGutter.addedBackground": "#859900",
      "editorGutter.modifiedBackground": "#b58900",
      "editorGutter.deletedBackground": "#dc322f",
      "textLink.foreground": "#268bd2",
      "badge.background": "#e0d8be",
      "badge.foreground": "#586e75"
    },
    "syntax": {
      "keyword": "#859900",
      "string": "#2aa198",
      "comment": "#93a1a1",
      "number": "#d33682",
      "function": "#268bd2",
      "operator": "#586e75",
      "type": "#b58900",
      "tag": "#268bd2"
    },
    "diff": {
      "inserted": "#859900",
      "removed": "#dc322f"
    },
    "label": "Solarized Light"
  },
  "vscode-catppuccin-latte": {
    "id": "vscode-catppuccin-latte",
    "appearance": "light",
    "colors": {
      "foreground": "#4c4f69",
      "descriptionForeground": "#6c6f85",
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      "sideBar.background": "#e6e9ef",
      "sideBar.foreground": "#4c4f69",
      "panel.background": "#eff1f5",
      "panel.border": "#ccd0da",
      "input.background": "#e6e9ef",
      "input.foreground": "#4c4f69",
      "input.border": "#bcc0cc",
      "button.background": "#1e66f5",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#dce0e8",
      "button.secondaryForeground": "#4c4f69",
      "dropdown.background": "#e6e9ef",
      "dropdown.border": "#bcc0cc",
      "editorWidget.background": "#e6e9ef",
      "list.hoverBackground": "#dce0e8",
      "list.activeSelectionBackground": "#ccd0da",
      "list.activeSelectionForeground": "#1e1e2e",
      "activityBar.background": "#dce0e8",
      "activityBar.foreground": "#4c4f69",
      "statusBar.background": "#e6e9ef",
      "statusBar.foreground": "#4c4f69",
      "titleBar.activeBackground": "#eff1f5",
      "titleBar.activeForeground": "#4c4f69",
      "terminal.background": "#eff1f5",
      "terminal.foreground": "#4c4f69",
      "terminal.selectionBackground": "#ccd0da",
      "terminalCursor.foreground": "#1e66f5",
      "editorLineNumber.foreground": "#8c8fa1",
      "editorGutter.addedBackground": "#40a02b",
      "editorGutter.modifiedBackground": "#df8e1d",
      "editorGutter.deletedBackground": "#d20f39",
      "textLink.foreground": "#1e66f5",
      "badge.background": "#ccd0da",
      "badge.foreground": "#4c4f69"
    },
    "syntax": {
      "keyword": "#8839ef",
      "string": "#40a02b",
      "comment": "#9ca0b0",
      "number": "#fe640b",
      "function": "#1e66f5",
      "operator": "#7c7f93",
      "type": "#df8e1d",
      "tag": "#dd7878"
    },
    "diff": {
      "inserted": "#40a02b",
      "removed": "#d20f39"
    },
    "label": "Catppuccin Latte"
  }
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
