/**
 * tmd 原创浅色主题 preset(低饱和高级灰取向,2026-10-02 定稿,原型见 docs/design/premium-themes.html)。
 * terminal.ansi* 16 色以 light-modern 对比度已验表为底,黄/亮绿/亮黄/亮白四槽加深
 * (雾灰 #f8f9fb / 暖帛 #fcfaf7 底上原值 WCAG 对比度 2.9x 不过 3:1 闸,实测值见下)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

const LIGHT_ANSI = {
  "terminal.ansiBlack": "#000000",
  "terminal.ansiRed": "#cd3131",
  "terminal.ansiGreen": "#107c10",
  "terminal.ansiYellow": "#8f9500",
  "terminal.ansiBlue": "#0451a5",
  "terminal.ansiMagenta": "#bc05bc",
  "terminal.ansiCyan": "#0598bc",
  "terminal.ansiWhite": "#555555",
  "terminal.ansiBrightBlack": "#666666",
  "terminal.ansiBrightRed": "#cd3131",
  "terminal.ansiBrightGreen": "#0fa30f",
  "terminal.ansiBrightYellow": "#8f9500",
  "terminal.ansiBrightBlue": "#0451a5",
  "terminal.ansiBrightMagenta": "#bc05bc",
  "terminal.ansiBrightCyan": "#0598bc",
  "terminal.ansiBrightWhite": "#8e8e8e"
};

export const LIGHT_PRESETS_PART8 = {
  "tmd-paper": {
    "id": "tmd-paper",
    "appearance": "light",
    "colors": {
      "foreground": "#26262b",
      "descriptionForeground": "#71717a",
      "editor.background": "#ffffff",
      "editor.foreground": "#26262b",
      "sideBar.background": "#fafafa",
      "sideBar.foreground": "#3f3f46",
      "panel.background": "#fafafa",
      "panel.border": "#e6e6e9",
      "input.background": "#ffffff",
      "input.foreground": "#26262b",
      "input.border": "#d9d9de",
      "button.background": "#1a1a1e",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#ececee",
      "button.secondaryForeground": "#26262b",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#d9d9de",
      "editorWidget.background": "#fafafa",
      "list.hoverBackground": "#f3f3f5",
      "list.activeSelectionBackground": "#e9e9ec",
      "list.activeSelectionForeground": "#17171a",
      "activityBar.background": "#fafafa",
      "activityBar.foreground": "#26262b",
      "statusBar.background": "#fafafa",
      "statusBar.foreground": "#71717a",
      "titleBar.activeBackground": "#fafafa",
      "titleBar.activeForeground": "#26262b",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#26262b",
      "terminal.selectionBackground": "#dcdce0",
      "terminalCursor.foreground": "#1a1a1e",
      "editorLineNumber.foreground": "#a8a8b0",
      "editorGutter.addedBackground": "#1a7f37",
      "editorGutter.modifiedBackground": "#0969da",
      "editorGutter.deletedBackground": "#cf222e",
      "textLink.foreground": "#4545a8",
      "badge.background": "#e4e4e7",
      "badge.foreground": "#26262b",
      ...LIGHT_ANSI
    },
    "syntax": {
      "keyword": "#6e56cf",
      "string": "#9d5b38",
      "comment": "#8e8e96",
      "number": "#9a6b2f",
      "function": "#7a5c17",
      "operator": "#52525a",
      "type": "#0f766e",
      "tag": "#6e56cf"
    },
    "diff": {
      "inserted": "#1a7f37",
      "removed": "#cf222e"
    },
    "label": "云白"
  },
  "tmd-mist": {
    "id": "tmd-mist",
    "appearance": "light",
    "colors": {
      "foreground": "#2c333b",
      "descriptionForeground": "#6b7682",
      "editor.background": "#f8f9fb",
      "editor.foreground": "#2c333b",
      "sideBar.background": "#eff1f4",
      "sideBar.foreground": "#3a424b",
      "panel.background": "#eff1f4",
      "panel.border": "#dde1e7",
      "input.background": "#ffffff",
      "input.foreground": "#2c333b",
      "input.border": "#ccd3db",
      "button.background": "#456089",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e2e6eb",
      "button.secondaryForeground": "#2c333b",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#ccd3db",
      "editorWidget.background": "#eff1f4",
      "list.hoverBackground": "#e7eaee",
      "list.activeSelectionBackground": "#d8e0ea",
      "list.activeSelectionForeground": "#1f2733",
      "activityBar.background": "#eff1f4",
      "activityBar.foreground": "#2c333b",
      "statusBar.background": "#eff1f4",
      "statusBar.foreground": "#6b7682",
      "titleBar.activeBackground": "#eff1f4",
      "titleBar.activeForeground": "#2c333b",
      "terminal.background": "#f8f9fb",
      "terminal.foreground": "#2c333b",
      "terminal.selectionBackground": "#d5dde6",
      "terminalCursor.foreground": "#456089",
      "editorLineNumber.foreground": "#9aa4af",
      "editorGutter.addedBackground": "#1a7f37",
      "editorGutter.modifiedBackground": "#456089",
      "editorGutter.deletedBackground": "#cf222e",
      "textLink.foreground": "#3e5c8a",
      "badge.background": "#dde2e8",
      "badge.foreground": "#2c333b",
      ...LIGHT_ANSI
    },
    "syntax": {
      "keyword": "#5560b0",
      "string": "#96603a",
      "comment": "#8a939e",
      "number": "#96682c",
      "function": "#77591a",
      "operator": "#57616c",
      "type": "#166b75",
      "tag": "#5560b0"
    },
    "diff": {
      "inserted": "#1a7f37",
      "removed": "#cf222e"
    },
    "label": "雾灰"
  },
  "tmd-linen": {
    "id": "tmd-linen",
    "appearance": "light",
    "colors": {
      "foreground": "#35312a",
      "descriptionForeground": "#7d766a",
      "editor.background": "#fcfaf7",
      "editor.foreground": "#35312a",
      "sideBar.background": "#f5f1eb",
      "sideBar.foreground": "#453f36",
      "panel.background": "#f5f1eb",
      "panel.border": "#e7e0d5",
      "input.background": "#fffefb",
      "input.foreground": "#35312a",
      "input.border": "#d8d0c2",
      "button.background": "#8f6b43",
      "button.foreground": "#fffaf2",
      "button.secondaryBackground": "#ece5da",
      "button.secondaryForeground": "#35312a",
      "dropdown.background": "#fffefb",
      "dropdown.border": "#d8d0c2",
      "editorWidget.background": "#f5f1eb",
      "list.hoverBackground": "#efe9e0",
      "list.activeSelectionBackground": "#e3dacb",
      "list.activeSelectionForeground": "#2e2a23",
      "activityBar.background": "#f5f1eb",
      "activityBar.foreground": "#35312a",
      "statusBar.background": "#f5f1eb",
      "statusBar.foreground": "#7d766a",
      "titleBar.activeBackground": "#f5f1eb",
      "titleBar.activeForeground": "#35312a",
      "terminal.background": "#fcfaf7",
      "terminal.foreground": "#35312a",
      "terminal.selectionBackground": "#e0d6c4",
      "terminalCursor.foreground": "#8f6b43",
      "editorLineNumber.foreground": "#a89f8f",
      "editorGutter.addedBackground": "#1a7f37",
      "editorGutter.modifiedBackground": "#8f6b43",
      "editorGutter.deletedBackground": "#cf222e",
      "textLink.foreground": "#7d5c36",
      "badge.background": "#e7dfd2",
      "badge.foreground": "#35312a",
      ...LIGHT_ANSI
    },
    "syntax": {
      "keyword": "#7d5ba8",
      "string": "#757531",
      "comment": "#99917f",
      "number": "#96682c",
      "function": "#77591a",
      "operator": "#6b6558",
      "type": "#3d7a6e",
      "tag": "#7d5ba8"
    },
    "diff": {
      "inserted": "#1a7f37",
      "removed": "#cf222e"
    },
    "label": "暖帛"
  },
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
