/**
 * VS Code light 主题 preset 数据 —— 移植自 codemoss features/theme/constants/vscodeThemePresets.ts(勿手改,说明见 ./index.ts)。
 */
import type { ThemePresetDefinition, ThemePresetId } from "./index";

export const LIGHT_PRESETS_PART1 = {
  "vscode-light-modern": {
    "id": "vscode-light-modern",
    "appearance": "light",
    "colors": {
      "foreground": "#3b3b3b",
      "descriptionForeground": "#3b3b3b",
      "editor.background": "#ffffff",
      "editor.foreground": "#3b3b3b",
      "sideBar.background": "#f8f8f8",
      "sideBar.foreground": "#3b3b3b",
      "panel.background": "#f8f8f8",
      "panel.border": "#e5e5e5",
      "input.background": "#ffffff",
      "input.foreground": "#3b3b3b",
      "input.border": "#cecece",
      "button.background": "#005fb8",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e5e5e5",
      "button.secondaryForeground": "#3b3b3b",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#cecece",
      "editorWidget.background": "#f8f8f8",
      "list.hoverBackground": "#f2f2f2",
      "list.activeSelectionBackground": "#e8e8e8",
      "list.activeSelectionForeground": "#000000",
      "activityBar.background": "#f8f8f8",
      "activityBar.foreground": "#1f1f1f",
      "statusBar.background": "#f8f8f8",
      "statusBar.foreground": "#3b3b3b",
      "titleBar.activeBackground": "#f8f8f8",
      "titleBar.activeForeground": "#1e1e1e",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#3b3b3b",
      "terminal.selectionBackground": "#add6ff",
      "terminalCursor.foreground": "#005fb8",
      "editorLineNumber.foreground": "#6e7681",
      "editorGutter.addedBackground": "#2ea043",
      "editorGutter.modifiedBackground": "#005fb8",
      "editorGutter.deletedBackground": "#f85149",
      "textLink.foreground": "#005fb8",
      "badge.background": "#cccccc",
      "badge.foreground": "#3b3b3b"
    },
    "syntax": {
      "keyword": "#0000ff",
      "string": "#a31515",
      "comment": "#008000",
      "number": "#098658",
      "function": "#795e26",
      "operator": "#000000",
      "type": "#267f99",
      "tag": "#0000ff"
    },
    "diff": {
      "inserted": "#2ea043",
      "removed": "#f85149"
    },
    "label": "Light Modern"
  },
  "vscode-light-plus": {
    "id": "vscode-light-plus",
    "appearance": "light",
    "colors": {
      "foreground": "#3b3b3b",
      "descriptionForeground": "#616161",
      "editor.background": "#ffffff",
      "editor.foreground": "#000000",
      "sideBar.background": "#f3f3f3",
      "sideBar.foreground": "#3b3b3b",
      "panel.background": "#ffffff",
      "panel.border": "#d4d4d4",
      "input.background": "#ffffff",
      "input.foreground": "#3b3b3b",
      "input.border": "#cecece",
      "button.background": "#007acc",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#ececec",
      "button.secondaryForeground": "#000000",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#cecece",
      "editorWidget.background": "#f3f3f3",
      "list.hoverBackground": "#e8e8e8",
      "list.activeSelectionBackground": "#cce6ff",
      "list.activeSelectionForeground": "#000000",
      "activityBar.background": "#f3f3f3",
      "activityBar.foreground": "#424242",
      "statusBar.background": "#007acc",
      "statusBar.foreground": "#ffffff",
      "titleBar.activeBackground": "#dddddd",
      "titleBar.activeForeground": "#333333",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#3b3b3b",
      "terminal.selectionBackground": "#add6ff",
      "terminalCursor.foreground": "#000000",
      "editorLineNumber.foreground": "#237893",
      "editorGutter.addedBackground": "#2ea043",
      "editorGutter.modifiedBackground": "#007acc",
      "editorGutter.deletedBackground": "#cd3131",
      "textLink.foreground": "#006ab1",
      "badge.background": "#c4c4c4",
      "badge.foreground": "#333333"
    },
    "syntax": {
      "keyword": "#0000ff",
      "string": "#a31515",
      "comment": "#008000",
      "number": "#098658",
      "function": "#795e26",
      "operator": "#000000",
      "type": "#267f99",
      "tag": "#0000ff"
    },
    "diff": {
      "inserted": "#2ea043",
      "removed": "#cd3131"
    },
    "label": "Light+"
  },
  "vscode-github-light": {
    "id": "vscode-github-light",
    "appearance": "light",
    "colors": {
      "foreground": "#1f2328",
      "descriptionForeground": "#57606a",
      "editor.background": "#ffffff",
      "editor.foreground": "#1f2328",
      "sideBar.background": "#f6f8fa",
      "sideBar.foreground": "#1f2328",
      "panel.background": "#ffffff",
      "panel.border": "#d0d7de",
      "input.background": "#ffffff",
      "input.foreground": "#1f2328",
      "input.border": "#d0d7de",
      "button.background": "#0969da",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#f6f8fa",
      "button.secondaryForeground": "#1f2328",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#d0d7de",
      "editorWidget.background": "#ffffff",
      "list.hoverBackground": "#f3f4f6",
      "list.activeSelectionBackground": "#ddf4ff",
      "list.activeSelectionForeground": "#0b3d91",
      "activityBar.background": "#f6f8fa",
      "activityBar.foreground": "#24292f",
      "statusBar.background": "#f6f8fa",
      "statusBar.foreground": "#57606a",
      "titleBar.activeBackground": "#ffffff",
      "titleBar.activeForeground": "#1f2328",
      "terminal.background": "#ffffff",
      "terminal.foreground": "#1f2328",
      "terminal.selectionBackground": "#b6e3ff",
      "terminalCursor.foreground": "#0969da",
      "editorLineNumber.foreground": "#8c959f",
      "editorGutter.addedBackground": "#1a7f37",
      "editorGutter.modifiedBackground": "#0969da",
      "editorGutter.deletedBackground": "#cf222e",
      "textLink.foreground": "#0969da",
      "badge.background": "#d0d7de",
      "badge.foreground": "#1f2328"
    },
    "syntax": {
      "keyword": "#cf222e",
      "string": "#0a3069",
      "comment": "#6e7781",
      "number": "#0550ae",
      "function": "#8250df",
      "operator": "#24292f",
      "type": "#953800",
      "tag": "#116329"
    },
    "diff": {
      "inserted": "#1a7f37",
      "removed": "#cf222e"
    },
    "label": "GitHub Light"
  },
} as unknown as Record<ThemePresetId, Omit<ThemePresetDefinition, "id">>;
