/**
 * omp 学堂课程目录 —— 82 条斜杠命令(10 章)+ 多示例。数据总表,拆分即伤对照性。
 *
 * 真源与提取法:omp 18.3.1 包内 src/slash-commands/builtin-registry.ts 的
 * BUILTIN_SLASH_COMMANDS_INTERNAL(bun 直读注册表导出;含 40 个 TUI-only 无
 * handle 命令,它们同样出现在 TUI / 菜单)。中文讲解/详解/四段示例为 tmd-cli
 * 侧人工内容。omp 升级后按同法重提,更新 sourceVersion。
 */
import type { AcademyCourse } from "@kernel/academy";
import { OMP_ACADEMY_LESSONS } from "./academyLessons";

export const OMP_ACADEMY_COURSE: AcademyCourse = {
  cliId: "omp",
  title: "omp 学堂",
  sourceVersion: "18.3.1",
  chapters: [
    { id: "lifecycle", title: "开始与会话", desc: "新建、恢复、清理会话;会话就像一个可来回切换的工作台", commands: [
      { name: "new", zh: "开始一个新会话", detail: "换任务时开全新会话。为什么:上一任务的上下文会残留干扰——agent 记着旧目标、旧文件,新任务容易答非所问;新会话 = 干净的脑子。旧会话完整留在磁盘,随时 /resume 找回,所以开新会话零成本。注意:只是同任务换思路,用 /clear 更合适,别把积累的上下文白白扔掉。", en: "Start a new session", how: "侧栏新建会话按钮直达同一动作", examples: [{ sc: "手头 bug 修完,要开始写新功能了", i: "/new", o: "✓ New session started", e: "旧会话原样留在磁盘,随时 /resume 回去补漏。/new 不带参数(写「/new 实现导出 PDF」整串会被当普通消息发出);换任务先 /new,再另发一条把新任务背景交代清楚。" }] },
      { name: "resume", zh: "恢复到另一个会话", detail: "找回历史会话继续干。为什么:omp 的一切(对话、改动、todo)都存在会话里,恢复 = 完整还原「做到哪了」,不用重新交代背景。不带参数列出最近会话;跨引擎会话也能恢复(@claude/@codex)。tmd-cli 侧栏 omp 分组点一下就是它。注意:resume 列表默认只显示当前目录的会话,别处开会话用 /move 或换目录。", en: "Resume a different session", usage: "[session id|@claude|@codex]", how: "侧栏 omp 分组点历史会话即恢复", examples: [{ sc: "昨天改到一半的会话,今天接着干", i: "/resume", o: "最近会话:\n▸ 修支付回调(2h 前)\n  重构登录模块(昨天)\n↑↓ 选择,Enter 恢复", e: "选中后对话、todo、改动记录完整还原,agent 记得做到哪。恢复后先让它复述一遍当前状态再继续,确认没走偏。" }, { sc: "在别的目录开的会话,列表里找不到", i: "/resume", o: "列表为空或只有本目录会话", e: "resume 按目录过滤——去原目录再 /resume,或用 /move 把会话挪过来。" }] },
      { name: "session", zh: "会话管理(info / delete / pin)", detail: "会话的档案入口。为什么:跑久了「这会话花了多少、干了什么」全靠回忆,info 一条命令给统计(消息数/token/费用/已服务模型)。delete 在这里做,pin 也在。注意:delete 不可恢复,只想清上下文请出门左转 /clear。", en: "Session management commands", how: "重命名/删除/置顶在侧栏会话右键菜单", examples: [{ sc: "感觉这会话跑挺久了,想看看花了多少", i: "/session info", o: "会话 8f3e21 · 42 条消息 · 128K tokens · 约 $0.86 · 时长 1h12m", e: "token 与费用按当前供应商口径估算。花得多且产出慢,考虑 /compact 或 /new 重开;数字正常就继续。" }], subs: [{ name: "info", en: "Show session info and stats" }, { name: "delete", en: "Delete current session and return to selector" }, { name: "pin", en: "Pin the current provider to a stored OAuth account", usage: "[account]" }] },
      { name: "pin", zh: "置顶/取消置顶(resume 列表)", detail: "把会话钉在 resume 列表顶部。为什么:会话多了新会话会把常用的挤下去,每次翻半天;钉住的永远在最上面。注意:再输一次取消;钉的是「在列表中的位置」,不是只读锁定,照常可用。", en: "Pin or unpin a session at the top of the resume list", usage: "[session id]", how: "在对话框输入 /pin 回车,即发送到终端执行", examples: [{ sc: "有个主会话天天用,老被新会话挤下去", i: "/pin", o: "已置顶:修支付回调", e: "它在 resume 列表永远排最上,不再翻找。不想置顶再输一次 /pin 即取消。" }] },
      { name: "rename", zh: "重命名当前会话(留空自动起名)", detail: "给会话起人能认的名字。为什么:默认会话名是自动摘要或 id,三天后 resume 列表里你自己都不认识;名字是检索会话的唯一人肉索引。不带参数时 agent 读内容自动起名,起得还挺准。注意:随手改名的习惯值回票价,尤其多会话并行时。", en: "Rename the current session (omit title to generate)", usage: "[title]", how: "在对话框输入 /rename 回车,即发送到终端执行", examples: [{ sc: "自动起的名字「修复 bug」太泛,认不出是哪个", i: "/rename 修支付回调超时", o: "已重命名:修支付回调超时", e: "resume 列表立刻显示新名字。一周后的你靠这行字找回会话,值得花两秒。" }] },
      { name: "move", zh: "把当前会话移到别的目录", detail: "把会话文件搬到另一目录。为什么:resume 按目录过滤,在 A 项目开的会话不会出现在 B 项目列表里;挪过去才找得到。注意:会话里记录的文件路径不会跟着改,跨项目引用的绝对路径注意失效。", en: "Move the current session to a different directory", usage: "[<path>]", how: "在对话框输入 /move 回车,即发送到终端执行", examples: [{ sc: "在临时目录开的会话,成果归到正式项目", i: "/move ~/code/tmd-cli", o: "会话已移动到 ~/code/tmd-cli", e: "在正式项目目录 /resume 就能找到它。注意会话里引用的绝对路径不受影响,跨目录的相对路径可能失效。" }] },
      { name: "delete", zh: "删除当前会话并新建", detail: "删除当前会话并立刻开新的。为什么:敏感内容(误贴的密钥、客户数据)需要彻底清除时用它;也用于清理废弃会话。注意:不可恢复、没有回收站;只是想轻装上阵用 /clear,想换任务用 /new——这仨别混。", en: "Delete the current session and start a new one", how: "在对话框输入 /delete 回车,即发送到终端执行", examples: [{ sc: "误把密钥贴进了会话,需要彻底清除", i: "/delete", o: "会话已删除,已开新会话", e: "文件级删除,不可恢复。密钥若已推给供应商,还要去后台吊销 key——删会话只是本地清场。" }] },
      { name: "fresh", zh: "重置供应商流状态(不动本地记录)", detail: "只重置模型连接状态。为什么:流卡死、连续 429/超时、回复断在半截,多半是连接态坏了而不是对话坏了;这时 /clear 或 /new 都是把孩子和洗澡水一起倒掉。注意:不动对话内容;fresh 完还不好使,再考虑重启 /restart。", en: "Reset provider stream state without changing the local transcript", how: "在对话框输入 /fresh 回车,即发送到终端执行", examples: [{ sc: "回复断在半截,再发就 429,上下文明明没满", i: "/fresh", o: "供应商流状态已重置(对话内容保留)", e: "坏的是连接态不是对话,fresh 后直接重发上一条即可。若依旧失败,等限流窗口过去或 /switch 换供应商。" }] },
      { name: "clear", zh: "原地清空对话上下文,保留会话", detail: "原地清空上下文但保留会话。为什么:同一任务做到一半「前面试错的垃圾信息太多,agent 被带偏了」,需要翻篇但不想丢会话身份与统计;clear 给你干净的上下文 + 连续的历史。注意:被清掉的细节不可恢复,重要结论先让 agent 写进文件或 /handoff。", en: "Clear the conversation context in place, keeping the session", how: "在对话框输入 /clear 回车,即发送到终端执行", examples: [{ sc: "同一个需求试错了十轮,上下文全是废稿,agent 被带偏", i: "/clear", o: "上下文已清空,会话与标题保留", e: "干净的脑子 + 保留的会话身份与统计。清前把有效结论让 agent 写进文件或记下来,清完重新交代约束,别指望它还记得。" }] },
      { name: "restart", zh: "用相同启动参数重启 omp 并恢复本会话", detail: "带参重启并恢复现场。为什么:升级版本、改配置文件后通常要重启才生效,手动退出→重开→找会话三步变成一步,且当前会话原样恢复。注意:跑着的后台任务会被打断,先 /jobs 看一眼再重启。", en: "Restart omp with the same launch flags, resuming this session", how: "在对话框输入 /restart 回车,即发送到终端执行", examples: [{ sc: "刚升级了 omp 版本,设置里改了配置", i: "/restart", o: "omp 正在重启并恢复本会话…", e: "几秒后回到同一会话,新版本与配置已生效。跑着的后台任务被打断,重启后 /jobs 检查残局。" }] },
      { name: "exit", zh: "退出应用", detail: "退出 omp。为什么:正常退出会确保会话落盘、子进程收尾;直接关终端窗口在极端情况下可能丢最后一轮。注意:tmd-cli 里关终端 tab 等效;会话自动保存,不用怕。", en: "Exit the application", how: "在对话框输入 /exit 回车,即发送到终端执行", examples: [{ sc: "今天收工", i: "/exit", o: "会话已保存,再见", e: "所有状态落盘,明天 /resume 无缝接上。tmd-cli 里直接关终端 tab 一样安全。" }] },
      { name: "quit", zh: "退出应用", detail: "同 /exit。为什么:肌肉记忆各有所好,两个都留。注意:无差别,选顺手的。", en: "Quit the application", how: "在对话框输入 /quit 回车,即发送到终端执行", examples: [{ sc: "收工(习惯说 quit)", i: "/quit", o: "同 /exit:会话已保存,再见", e: "无差别,两个命令一个效果。" }] },
    ] },
    { id: "model", title: "模型与账号", desc: "换模型、管账号、看用量;先搞清这些,花钱心里有数", commands: [
      { name: "model", zh: "为本会话切换模型", detail: "切换本会话模型。为什么:不同任务配不同脑子——读代码要长上下文、改文案要文笔、跑批要便宜;一根模型打天下又贵又笨。切换立即生效,历史上下文原样带过去。tmd-cli composer 的模型 pill 是同一能力。注意:切模型不改系统提示,个别模型差异大的任务建议配合 /new。", en: "Switch model for this session", how: "composer 上方模型 pill 快速切换", examples: [{ sc: "要写一段对文笔要求高的文案,当前是便宜的快模型", i: "/model", o: "选择模型:\n▸ GLM-4.6 (coding plan)\n  Claude Sonnet 4.5\n  GPT-5.1\nEnter 切换,Esc 取消", e: "选中即生效,下一条消息就换脑子,历史上下文原样带过去。文案写完记得切回默认,别让贵模型跑杂活。" }, { sc: "不确定该选哪个", i: "/model", o: "(选择器列表)", e: "经验:读码/大仓用长上下文款,写作用旗舰款,跑批用便宜款。tmd-cli composer 的模型 pill 是同一件事的图形化,顺手就用它。" }] },
      { name: "switch", zh: "切换模型(同 Alt+P),支持模糊 id", detail: "/model 的快捷版。为什么:选择器要点两下,背熟 id 后 switch sonnet 一秒完成;等价 Alt+P。支持模糊匹配,前缀够唯一就行。注意:歧义时直接报 Unknown model、不乱切;想浏览用 /model 选择器。", en: "Switch model for this session (same as alt+p); accepts fuzzy ids, provider/id, @role, :level", usage: "[model]", how: "composer 模型 pill 即可视化管理", examples: [{ sc: "背熟了 id,懒得进选择器", i: "/switch sonnet", o: "已切换:Claude Sonnet 4.5", e: "模糊匹配,前缀唯一即中;歧义会直接报 Unknown model,不会默默切错。等价快捷键 Alt+P。" }] },
      { name: "login", zh: "用 OAuth 登录供应商", detail: "OAuth 登录供应商。为什么:订阅类(Claude Pro、GLM Coding Plan)走 OAuth 才吃到订阅额度,API key 是另一套计费;登错通道是「有订阅却按量扣费」的常见原因。tmd-cli 凭据面板同一流程。注意:多账号轮换登录会被供应商风控盯上,一个供应商固定一个号。", en: "Login with OAuth provider", usage: "[provider|redirect URL]", how: "welcome 引擎卡「凭据」入口,OAuth 同流程", examples: [{ sc: "新买了 GLM Coding Plan 订阅,想吃到订阅额度", i: "/login", o: "选择供应商:\n▸ Z.ai Coding Plan (OAuth)\n  Anthropic (OAuth)\n浏览器即将打开授权页…", e: "浏览器授权后回到终端即登录成功。走 OAuth 才吃订阅额度——直接贴 API key 会走按量计费,这是「有订阅还扣钱」的头号原因。" }] },
      { name: "logout", zh: "退出 OAuth 登录", detail: "退出 OAuth。为什么:换号、借出的机器、回收凭据时必须主动退出,光删配置文件可能留残留 token。注意:logout 后该供应商立刻不可用,确保有备用通道(另一个供应商或 key)。", en: "Logout from OAuth provider", usage: "[provider]", how: "API key 可在凭据面板删;OAuth 退出仍在终端 /logout(面板删不了 OAuth 凭据)", examples: [{ sc: "这台共用机器登过我的号,要走了", i: "/logout", o: "选择要退出的供应商 → 已退出 Z.ai Coding Plan", e: "token 立即失效,该供应商不可用。确认有别的通道(另一个供应商或 key)再退,别把自己锁外面。" }] },
      { name: "setup", zh: "打开 provider 配置向导(接 API / 订阅)", detail: "provider 配置向导。为什么:首次配置要选供应商、贴 key、配 base URL、测连通,散着配容易漏;向导一条龙并当场验证。注意:已有配置跑 setup 不破坏现值,只改你动过的项。", en: "Open provider setup", how: "在对话框输入 /setup 回车,即发送到终端执行", examples: [{ sc: "第一次用,或换了新 key", i: "/setup", o: "Provider 配置向导:\n1 选择供应商 → 2 粘贴 key → 3 测试连通 ✓", e: "当场验证连通,配置完直接能聊。已有配置不会被覆盖,只改你动过的项。" }], subs: [{ name: "providers", en: "Configure sign-in and web search providers" }] },
      { name: "settings", zh: "打开设置菜单(模型、主题、行为等)", detail: "omp 设置菜单。为什么:默认模型、自动压缩阈值、主题、通知这些持久偏好在这;tmd-cli 设置面板覆盖常用项,细项和全量在这里。注意:设置是全局的,本会话临时的开关(如 plan 模式)不在这。", en: "Open settings menu", how: "tmd-cli 设置里「omp」分区覆盖常用项", examples: [{ sc: "想把自动压缩阈值调低点,少占上下文", i: "/settings", o: "设置:默认模型 / 压缩阈值 / 主题 / 通知 …", e: "改的是全局持久配置。tmd-cli 设置面板的 omp 分区覆盖常用项,细项来这里。" }] },
      { name: "usage", zh: "查看供应商用量与额度限制", detail: "看额度与限流。为什么:「怎么突然变笨了」十有八九是限流或配额见底;用量心里有数,跑大批任务前先看一眼余额,避免跑到一半断粮。tmd-cli composer 的额度 chip 读同一凭据的额度(各自独立实现,口径可能略有差)。注意:多供应商时显示当前会话所用供应商的额度,切换后数字会变。", en: "Show provider usage and limits", how: "composer 工具条的额度 chip 看同源凭据的额度", examples: [{ sc: "感觉回复变慢变笨了,先排除限流", i: "/usage", o: "GLM Coding Plan 本月:112.4M / 120M tokens(94%)\n5h 窗口:已用 82%", e: "原因找到了:配额见底被限流。要么等窗口重置、要么 /slow 降优先级、要么切备用供应商。大批任务前先看这,别跑一半断粮。" }], subs: [{ name: "show", en: "Show provider usage and limits" }, { name: "reset", en: "Spend a saved provider rate-limit reset", usage: "[provider/credential-id|provider/active]" }] },
      { name: "stats", zh: "启动本地统计 Dashboard", detail: "本地统计 Dashboard。为什么:usage 看当下,stats 看历史——花费曲线、项目分布、会话趋势,月底对账、优化烧钱习惯靠它。本地数据不出机器。注意:起的是本地 web 服务,用完可关;数据依赖会话文件在默认位置。", en: "Launch the local stats dashboard", usage: "[--port <port>] [--host <host>]", how: "在对话框输入 /stats 回车,即发送到终端执行", examples: [{ sc: "月底了,看看这个月钱花在哪个项目", i: "/stats", o: "统计 Dashboard → http://127.0.0.1:28431\n会话 47 · tokens 210M · 项目分布图 …", e: "本地数据不出机器。发现某项目独占六成花费,考虑给它限速或换便宜模型。" }] },
      { name: "fast", zh: "切换 priority 服务档(OpenAI/Anthropic 高优先级通道)", detail: "切 priority 高优通道。为什么:同一模型有快慢通道,高峰期普通通道排队明显;fast 花钱买确定性延迟。赶交付、演示前开它。注意:费率上浮明显(可能数倍),日常挂 fast 纯属烧钱,用完切回。", en: "Toggle priority service tier (OpenAI service_tier=priority, Anthropic speed=fast)", how: "在对话框输入 /fast 回车,即发送到终端执行", examples: [{ sc: "下午要给客户演示,响应必须快", i: "/fast", o: "priority 服务档已开启(费率上浮,响应更快)", e: "高峰期也能拿到稳定低延迟。演示完记得 /slow 或切回默认——fast 费率可能是数倍,日常挂着纯烧钱。" }], subs: [{ name: "on", en: "Enable fast mode" }, { name: "off", en: "Disable fast mode" }, { name: "status", en: "Show fast mode status" }] },
      { name: "slow", zh: "切换 slow 档:flex/低优先级,省额度换等待", detail: "切 flex/低优先级档。为什么:不急的任务(夜间批量、文档生成)用折扣价换供应商空闲时段调度,成本能省一大截。注意:等待时间不可控,交互式工作别开;配额类订阅看规则,可能不省钱只降优先级。", en: "Toggle slow mode: flex tier on OpenAI/Google; on Anthropic, continue at lower priority after the Claude session limit", how: "在对话框输入 /slow 回车,即发送到终端执行", examples: [{ sc: "今晚要跑一批文档生成,不急", i: "/slow", o: "已切到 flex 档:更省钱,调度等待变长", e: "供应商闲时才调度,成本省一大截。交互工作别用——等 30 秒回一句话会疯。" }], subs: [{ name: "on", en: "Flex tier, or Anthropic lower priority at the session limit (auto)" }, { name: "off", en: "Standard service; stop Anthropic lower-priority mode" }, { name: "status", en: "Show slow mode status" }] },
      { name: "extended-context", zh: "切换扩展上下文窗口", detail: "请求扩展上下文窗口。为什么:大仓库全局重构、超长文档分析,200K 装不下时唯一解是更大的窗口;避免暴力拆分丢全局视野。注意:扩展部分费率通常更高,先 /context 看真需要多少,别为 30K 的任务开 1M。", en: "Toggle extended context windows", how: "在对话框输入 /extended-context 回车,即发送到终端执行", examples: [{ sc: "要把整个仓库 300 个文件做全局重构分析", i: "/extended-context", o: "扩展上下文已开启:200K → 1M(费率见供应商)", e: "现在能一次装下全仓。先 /context 确认真装了这么多——只为 30K 的任务开 1M 是纯浪费,费率通常更高。" }], subs: [{ name: "on", en: "Enable larger context windows" }, { name: "off", en: "Use default or standard-pricing context windows" }, { name: "status", en: "Show extended context status" }] },
    ] },
    { id: "modes", title: "模式与自主", desc: "omp 的灵魂:让 agent 先想后做、持续自主、排队不插队", commands: [
      { name: "plan", zh: "切换 Plan 模式:先出计划再动手", detail: "Plan 模式:先出计划再动手。为什么:agent 直接动手的第一版常常方向就错,返工成本远大于先看计划;plan 强制只读调研,把「做什么、改哪些文件、风险」摊开给你拍板。复杂/不可逆操作(重构、删代码、改架构)前必开。注意:小改动别开,仪式感浪费时间;也可以直接在消息里要求「先说思路再改」轻量达成。", en: "Toggle plan mode (agent plans before executing)", usage: "[prompt]", how: "在对话框输入 /plan 回车,即发送到终端执行", examples: [{ sc: "要做大重构:动 20 个文件,改核心接口", i: "/plan", o: "Plan 模式已开启:下一轮只做调研与计划,确认后再执行", e: "接下来发需求,agent 只读代码出计划(改哪些文件/风险/顺序),不动一行代码。逐条确认或打回,计划定稿再放行——这是返工率最低的工作方式。" }, { sc: "计划执行一半,想回看最初承诺", i: "/plan-review", o: "已重新打开计划评审(上次计划:重构登录模块)", e: "对照原始计划判断:计划本身错了就 /branch 回退改计划;只是执行偏了就把偏差指出来纠正。" }] },
      { name: "plan-review", zh: "重新打开最近一次计划的评审视图", detail: "重看最近一次计划。为什么:执行到一半发现不对劲,需要对照原始计划确认是「计划错了」还是「执行偏了」;也用于给新同事复盘决策。注意:只针对最近一次 plan,更早的翻 /export 记录。", en: "Re-open the plan review for the latest plan (plan mode only)", how: "在对话框输入 /plan-review 回车,即发送到终端执行", examples: [{ sc: "执行到一半发现和当初说的不一样", i: "/plan-review", o: "已重新打开计划评审", e: "对照计划:计划错→branch 回退;执行偏→指出纠正。别凭记忆吵架,看原始文档。" }] },
      { name: "vibe", zh: "切换 Vibe 模式:主会话只读,派快/好档 worker 干活", detail: "Vibe 模式:你只发指令,主会话转只读调度器,把活派给常驻的快/好档 worker 会话去干。为什么:小改动连发时不必每步确认,你指挥、worker 执行,保持心流。注意:大改动、生产文件、不熟悉的模块别 vibe——worker 自主少确认;配合 /loop 用注意配额。", en: "Toggle vibe mode (direct persistent fast/good worker sessions; read-only toolset)", usage: "[prompt]", how: "在对话框输入 /vibe 回车,即发送到终端执行", examples: [{ sc: "连续做十个小改动:改文案、调样式、补注释", i: "/vibe", o: "Vibe mode enabled. You direct fast/good worker sessions.", e: "此后主会话只下指令(工具集转只读),实际改动由派生的快/好档 worker 执行。涉及生产配置、数据库、不熟悉的模块先关 vibe——少掉的确认是最后一道闸。" }] },
      { name: "goal", zh: "切换 Goal 模式:给会话一个持续自主的目标", detail: "给会话一个持续自主的目标。为什么:多步任务(修 flaky、清 warning)一句一句指挥太累;goal 让 agent 自转「做→验证→继续」直到达成,你只看结果。目标质量决定一切:写成可判定的完成条件(命令通过、数字达标),别写「弄好一点」。注意:烧 token 大户,睡觉/离开前挂上,配额度上限;偏离就 /pause 拉回。", en: "Toggle goal mode (persistent autonomous objective for this session)", usage: "[objective]", how: "在对话框输入 /goal 回车,即发送到终端执行", examples: [{ sc: "仓库有 14 个 flaky 测试,想一次清干净", i: "/goal 把 flaky 测试修到全绿", o: "目标已设定:把 flaky 测试修到全绿\n完成判定:pnpm test 连续 2 次全绿", e: "agent 开始「修→跑→继续」自转,不用你每轮指挥。目标里「连续 2 次全绿」是可判定条件——写成这种才有效;睡觉前挂上,早上收结果。中途偏离 /pause 拉回。" }], subs: [{ name: "set", en: "Set or replace the goal", usage: "<objective>" }, { name: "show", en: "Show current goal details" }, { name: "pause", en: "Pause the current goal" }, { name: "resume", en: "Resume a paused goal" }, { name: "drop", en: "Drop the current goal" }, { name: "budget", en: "Adjust the token budget", usage: "<N|off>" }] },
      { name: "guided-goal", zh: "由 agent 对话式采访你,再帮你配置 goal 模式", detail: "agent 采访式配 goal。为什么:goal 难写——容易写成愿望而非完成条件;采访(要什么/怎么判定/禁区)逼你把模糊想法变成可执行目标,最后自动配好。注意:采访会花两三轮对话,急事直接手写 goal。", en: "Have the agent interview you in chat, then set up goal mode", usage: "[rough objective]", how: "在对话框输入 /guided-goal 回车,即发送到终端执行", examples: [{ sc: "知道要啥但写不出合格的 goal", i: "/guided-goal", o: "我先问你三个问题:想达成什么?怎么算完成?有什么禁区?", e: "两三轮问答后自动生成合格 goal(含可判定完成条件)。适合第一次用 goal 的人学怎么写——看它怎么问,下次就会自己写了。" }] },
      { name: "loop", zh: "切换 Loop:开启后下一条消息在每轮结束后重发", detail: "循环重发消息。为什么:「盯着修到测试全绿」这类任务,每轮结束手动喊继续太蠢;loop 开启后,你发的下一条消息在每次 agent yield 后自动重发,人不用守着。给数字=最多 N 轮,给时长(10m)=该时间窗内持续重发的总时限,配 --while/--until 用命令退出码决定下一轮跑不跑。注意:务必设上限或终止条件否则烧穿配额;Esc 暂停当前循环,再输 /loop 关闭。", en: "Toggle loop mode. While enabled, the next prompt you send re-submits after every yield. Bound it with a count/duration, or gate it with `--until '<cmd>'` / `--while '<cmd>'` — the command's exit status decides whether the next iteration runs. Esc suspends the ongoing loop; /loop again to disable.", usage: "[count|duration] [--while|--until '<cmd>'] [prompt]", how: "在对话框输入 /loop 回车,即发送到终端执行", examples: [{ sc: "让 agent 盯着 CI,直到测试全绿", i: "/loop --until 'pnpm test' 把 flaky 测试修到全绿", o: "Loop: on(until: pnpm test)", e: "这条消息会在每轮结束后自动重发,直到 --until 命令退出码为真。给时长(如 /loop 10m)是总时限不是间隔:到点打印「Loop time limit reached. Loop mode disabled.」。务必写清达标即停并盯 /usage——无人值守循环是头号烧钱方式。" }] },
      { name: "queue", zh: "把消息排进队列,等 agent 忙完这轮再发送", detail: "排队发消息。为什么:agent 正在跑长任务,直接发消息要么插队打断、要么被吞;queue 把话排上,这轮结束自动送出,不打断节奏。注意:排队消息在待发送区可见,留意别排了忘发;紧急打断还是直接发。", en: "Queue a message for after the agent yields", usage: "<message>", how: "在对话框输入 /queue 回车,即发送到终端执行", examples: [{ sc: "agent 正跑长重构,突然想到还要补个单测", i: "/queue 修完顺手给 parse 补个单测", o: "已排队:这轮结束后自动发送", e: "不打断当前节奏,这轮结束自动送出。排队的事会被记住并发送——排之前想清楚,别排了又忘。真紧急直接发,那是打断。" }] },
      { name: "advisor", zh: "切换 advisor:第二个模型逐轮复核并插话", detail: "第二模型当顾问。为什么:单模型自说自话容易集体走偏;advisor 逐轮复核主模型输出、可插话纠偏,等于自带 code review。重要项目、复杂架构决策开它。注意:token 消耗接近翻倍,别全天挂;advisor 与主模型最好异构(不同厂)避免同源盲区。", en: "Toggle the advisor (a second model that reviews each turn and injects notes)", how: "在对话框输入 /advisor 回车,即发送到终端执行", examples: [{ sc: "架构决策拍板前,想要第二意见", i: "/advisor on", o: "Advisor enabled.", e: "此后每轮多一个模型复核主模型结论,异议摆上台面。顾问模型经设置里的 advisor 角色或 /advisor configure 指定(不能行内带模型名);最好选异厂避免同源盲区,token 翻倍,大决策开、日常关。" }], subs: [{ name: "on", en: "Enable the advisor" }, { name: "off", en: "Disable the advisor" }, { name: "status", en: "Show advisor status" }, { name: "dump", en: "Copy the advisor's transcript to clipboard", usage: "[raw]" }, { name: "configure", en: "Open the advisor configuration editor (TUI)" }] },
      { name: "prewalk", zh: "布置一次性模型交接:主模型规划,改文件时切小模型", detail: "一次性模型交接。为什么:长上下文模型读代码强但改文件贵,小模型改文件便宜够用;prewalk 布置一轮交接——规划用 @default 主模型,到第一次 edit/write(todo 门控)自动切到 @smol 小模型收尾。注意:只管一轮,不是持久切换;参数只接受 restart(回 @default 并重新布置),带别的会报 Usage。", en: "Arm or restart a one-shot model handoff", how: "在对话框输入 /prewalk 回车,即发送到终端执行", examples: [{ sc: "这轮既要读大量代码又要改文件,想省改文件的钱", i: "/prewalk", o: "Prewalk armed: @default 规划,到第一次 edit/write 切 @smol", e: "规划由主模型做,落到改文件时自动降级小模型,省一笔。只影响一轮;想重来用 /prewalk restart。" }], subs: [{ name: "restart", en: "Return to @default and re-arm the handoff to @smol" }] },
      { name: "pause", zh: "冻结全部 agent(主/子/advisor)直到恢复", detail: "冻结全部 agent。为什么:发现 agent 跑偏、想改需求、或突然要接手键盘,需要「立刻全停」而不是逐个杀;pause 一键冻结主/子/顾问。注意:跑到一半的子任务会完成当前步再停;暂停是全屏画面,按 Esc/回车/空格恢复(不是再输一次 /pause)。", en: "Freeze all agents (main, subagents, advisor) until resumed", how: "在对话框输入 /pause 回车,即发送到终端执行", examples: [{ sc: "agent 理解跑偏,再跑下去越错越远", i: "/pause", o: "已冻结全部 agent(暂停画面)", e: "主/子/顾问全部急停,损失止步于此。屏幕被暂停画面接管,按 Esc 或回车/空格恢复;冷静改需求后继续,跑一半的子任务会做完当前步再停,去 /jobs 收尾。" }] },
      { name: "force", zh: "强制下一轮使用指定工具", detail: "强制下一轮用指定工具。为什么:排查「agent 怎么不用某工具」时,把变量隔离——强制调用看工具本身好不好使,区分是工具问题还是模型选择问题;也用于测试新工具链。注意:纯调试命令,日常用会把 agent 搞得刻舟求剑。", en: "Force next turn to use a specific tool", usage: "<tool-name> [prompt]", how: "在对话框输入 /force 回车,即发送到终端执行", examples: [{ sc: "怀疑 read 工具坏了,agent 老说找不到文件", i: "/force read", o: "下一轮我将强制首先调用 read 工具", e: "变量隔离:强制调用后还失败 = 工具/环境问题;成功 = 模型选择问题。调试完就停用,别拿它当常规手段。" }] },
    ] },
    { id: "tasks", title: "任务与后台", desc: "盯进度、派后台、修诊断", commands: [
      { name: "todo", zh: "查看/修改 agent 的 todo 列表", detail: "agent 的任务列表。为什么:大任务被拆成步骤后,进度全在 todo 里;盯 todo 比滚屏看输出清楚得多,也方便插手(改优先级、删废任务)。11 个子命令覆盖编辑/导入导出。tmd-cli 未来可在侧栏可视化。注意:todo 是 agent 的工作记忆,你手动改完记得让它重新读取。", en: "View or modify the agent's todo list", how: "在对话框输入 /todo 回车,即发送到终端执行", examples: [{ sc: "大任务跑起来了,想知道现在干到哪", i: "/todo", o: "● 进行中 修复 parse 竞态(2/5)\n○ 待办 补回归测试\n✓ 完成 定位根因:fs 竞态", e: "这是 agent 的工作计划,比滚屏看输出直观。发现优先级不对可以直接让它调整;全部 ✓ 说明任务收尾了,该验收 diff 了。" }], subs: [{ name: "edit", en: "Open todos in $EDITOR (Markdown round-trip)" }, { name: "copy", en: "Copy todos as Markdown to clipboard" }, { name: "expand", en: "Show every phase and task in the HUD" }, { name: "collapse", en: "Restore the bounded HUD preview" }, { name: "export", en: "Write todos as Markdown to a file (default: TODO.md)", usage: "[<path>]" }, { name: "import", en: "Replace todos from a Markdown file (default: TODO.md)", usage: "[<path>]" }, { name: "append", en: "Append a task; phase fuzzy-matched or auto-created", usage: "[<phase>] <task...>" }, { name: "start", en: "Mark task in_progress (fuzzy-matched)", usage: "<task>" }, { name: "done", en: "Mark task/phase/all completed (fuzzy-matched)", usage: "[<task|phase>]" }, { name: "drop", en: "Mark task/phase/all abandoned (fuzzy-matched)", usage: "[<task|phase>]" }, { name: "rm", en: "Remove task/phase/all (fuzzy-matched)", usage: "[<task|phase>]" }] },
      { name: "jobs", zh: "查看异步后台任务状态", detail: "后台任务状态。为什么:子 agent、长命令、扫描全在后台跑,「它在磨蹭还是死了」看 jobs 一目了然;也用于确认没有残留任务就关机走人。注意:失败的子任务会在这里留尸,定期清一下。", en: "Show async background jobs status", how: "在对话框输入 /jobs 回车,即发送到终端执行", examples: [{ sc: "感觉后台在跑东西,不确定是啥", i: "/jobs", o: "[1] tan (running) — 2m10s\n[2] cleanse (done) — 40s", e: "看清谁在跑、跑了多久。收工前检查这里,别留孤儿任务;失败的子任务会留尸,定期清。" }] },
      { name: "tan", zh: "派一个完整后台 agent 去干不相干的事", detail: "派后台 agent 干不相干的事。为什么:写文档、查资料这类活放进主会话会稀释上下文、拖慢主线;tan 独立上下文并行干,成果落盘不占你脑子。注意:后台 agent 看不到你们聊到哪,派活要把背景写全;跑完去 jobs 验收。", en: "Run a full background agent on tangential work", usage: "<work>", how: "在对话框输入 /tan 回车,即发送到终端执行", examples: [{ sc: "主线在改核心逻辑,顺便想把 README 翻译了", i: "/tan 把 README 翻译成英文", o: "已派出后台 agent:README 翻译(jobs 可查进度)", e: "翻译在独立上下文并行跑,不稀释主线注意力。派活把背景写全(译成什么风格、放哪),它看不到你们聊过什么;完成后结果自动带回主会话,jobs 看进度。" }] },
      { name: "cleanse", zh: "加权并行子 agent 检测并修复项目诊断问题", detail: "并行子 agent 清诊断。为什么:lint 报 200 条手修到吐;cleanse 加权分派给并行子 agent,按严重度排期修,一次大扫除。发版前、接手老项目时用。注意:改动面大,跑之前确保工作区干净、可回滚(git);修完自己过一遍 diff。", en: "Detect and fix project diagnostics with weighted parallel subagents", usage: "[request] [--all]", how: "在对话框输入 /cleanse 回车,即发送到终端执行", examples: [{ sc: "接手老项目,lint 报 200+ 条", i: "/cleanse", o: "已启动 4 个并行子 agent 扫描诊断…", e: "按严重度加权分派、并行修复,完成后给汇总。改动面大——跑前确保 git 干净可回滚,跑后自己过一遍 diff,机器修的东西要人签字。" }] },
      { name: "retry", zh: "重试上一轮失败的 agent 回合", detail: "重试上一轮。为什么:网络抖动、429 限流、供应商抽风导致回合失败,内容没问题只是传输断了;retry 原样重发,不用重新组织 prompt。注意:失败原因是你 prompt 本身的话,retry 只是再错一遍,先改 prompt。", en: "Retry the last failed agent turn", how: "在对话框输入 /retry 回车,即发送到终端执行", examples: [{ sc: "上一轮回复到一半报 429 断了", i: "/retry", o: "正在重试上一轮(429 限流已恢复)…", e: "原样重发失败的那轮,prompt 不用重新写。若是内容本身的问题(格式错、逻辑错),retry 只是再错一遍,先改 prompt 再试。" }] },
    ] },
    { id: "context", title: "上下文与记忆", desc: "上下文是钱也是智商;这章教你省钱又不失忆", commands: [
      { name: "context", zh: "显示上下文用量估算明细", detail: "上下文用量明细。为什么:上下文是钱也是智商——超了报错、接近了变笨;明细告诉你谁在吃额度(通常是工具结果),压缩决策全靠它。建议当仪表盘随手看。注意:数字是估算,与账单口径略有差异。", en: "Show estimated context usage breakdown", how: "在对话框输入 /context 回车,即发送到终端执行", examples: [{ sc: "回复越来越慢,怀疑上下文快满", i: "/context", o: "上下文 142K / 200K(71%)\n系统提示 8.2K · 工具结果 96.4K · 对话 37.4K", e: "元凶是工具结果占 96K。马上到 80% 警戒线,主动 /compact 或 /shake;越早压失真越小,等到自动压缩是应急式乱压。" }] },
      { name: "compact", zh: "手动压缩会话上下文", detail: "压缩上下文成摘要。为什么:长会话必然爆;compact 把过程细节折叠成结论摘要,agent 记得「做过什么决定」、忘掉「中间吐了几版」。主动压缩比等自动压缩好——在章节边界压,失真最小。注意:压掉的具体输出不可恢复,关键数据先落文件;压缩后 agent 可能短暂「忘事」,重要约束重申一遍。", en: "Manually compact the session context", how: "在对话框输入 /compact 回车,即发送到终端执行", examples: [{ sc: "上下文 71%,刚完成一个大章节,准备进下一章", i: "/compact", o: "已压缩:142K → 38.6K(保留关键结论与文件清单)", e: "章节边界压最划算:结论保留、废稿丢弃。压完 agent 记得「决定」忘掉「过程」,重要约束(编码规范、禁区)重新强调一遍。" }, { sc: "不确定压缩会不会丢关键信息", i: "/compact", o: "(压缩摘要)", e: "看摘要里有没有你要的结论。被压掉的原始输出不可恢复——所以关键数据先落文件再压,这是铁律。" }], subs: [{ name: "soft", en: "Summarize locally with the active model (skip server compaction)", usage: "[focus]" }, { name: "remote", en: "Summarize via OpenAI-compatible server compaction, then fall back to a local summary", usage: "[focus]" }, { name: "snapcompact", en: "Archive history onto dense bitmap images the model reads back (no LLM call)" }] },
      { name: "shake", zh: "甩掉上下文里的重内容(工具结果、大块)", detail: "只丢重内容,比 compact 保守。为什么:感觉 agent 变笨但对话脉络很重要,全压缩太激进;shake 专丢老工具输出、大块代码这类可再生的重物,保留对话逻辑。注意:被丢的工具结果如需引用,让 agent 重新读文件;shake 不改善系统性混乱,那是 compact 的活。", en: "Drop heavy content from context (tool results, large blocks)", how: "在对话框输入 /shake 回车,即发送到终端执行", examples: [{ sc: "agent 变笨了,但对话推理链很重要不能压", i: "/shake", o: "已丢弃 9 个旧工具结果与大块输出,释放 41.2K", e: "脉络保留、重物扔掉,比 compact 温和。丢的工具结果需要时让 agent 重新读文件即可——文件还在,丢了也不心疼。" }], subs: [{ name: "elide", en: "Strip tool results + large blocks (default)" }, { name: "images", en: "Strip image blocks" }, { name: "thinking", en: "Drop all thinking blocks" }] },
      { name: "handoff", zh: "把会话总结成交接摘要并原地压缩", detail: "总结成交接摘要并原地压缩。为什么:跨天、换人、换会话时,新会话最缺「做到哪了」的上下文;handoff 让模型把现状写成一份交接摘要、作为压缩分界点提交进会话,再原地压缩,接力零成本。注意:摘要生成后扫一眼,下一步建议不符预期就补一句让它重写;手输 /handoff 不落项目根文件(仅自动压缩路径 + 开 handoffSaveToDisk 才写盘)。", en: "Summarize the session into a handoff document and compact in place", usage: "[focus instructions]", how: "在对话框输入 /handoff 回车,即发送到终端执行", examples: [{ sc: "今天必须收工,任务明天换个会话继续", i: "/handoff", o: "Context handed off and compacted in place.", e: "现状被写成一份交接摘要并作为压缩点提交,历史折叠进它。明天 /resume 回本会话即可续上;摘要方向不对,补一句让它重写。" }] },
      { name: "btw", zh: "问个题外话,或浏览本会话的 BTW 历史", detail: "题外话通道。为什么:「顺便问下这个函数谁写的」这类问题走主上下文,回答会稀释主线还烧额度;btw 独立小上下文问答,主对话纯净如初。历史保留可回看。注意:btw 里的结论不会自动进入主对话上下文,要采纳得明说。", en: "Ask a side question, or browse this session's BTW history", usage: "[question]", how: "在对话框输入 /btw 回车,即发送到终端执行", examples: [{ sc: "改代码途中想问「这函数谁写的」,不想污染主线", i: "/btw 这个 parse 函数最早谁写的", o: "(独立上下文)git log 显示 2025-03 由 … 引入,最初为了 …", e: "答案只出现在 btw 里,主对话上下文一尘不染。要把结论用于主线,得明说「把刚才结论带进来」。" }] },
      { name: "memory", zh: "检查并维护记忆", detail: "agent 长期记忆维护。为什么:记忆是双刃剑——记对了事半功倍,记错了它永远「记得」你的错误偏好;view/stats/diagnose/sync/clear 等子命令查看、诊断、清理,定期修剪。注意:clear(=reset)清空持久记忆不可逆;没有逐条 edit/read 子命令,改错记忆靠 clear 后重建或经 mm 系列。", en: "Inspect and operate memory maintenance", how: "在对话框输入 /memory 回车,即发送到终端执行", examples: [{ sc: "agent 老是记错:偏好早改成 pnpm 了它还用 npm", i: "/memory view", o: "显示当前注入的记忆载荷", e: "先 view 看注入内容、定位错误记忆。没有 /memory edit 逐条改——改正靠 clear 后重新沉淀,或 mm 系列管理心智模型;记忆错一对,未来会话错一对,定期修剪值回票价。" }], subs: [{ name: "view", en: "Show current memory injection payload" }, { name: "stats", en: "Show memory backend statistics" }, { name: "diagnose", en: "Run memory backend diagnostics" }, { name: "queue", en: "Show pending memory deltas awaiting consolidation" }, { name: "sync", en: "Run memory consolidation now" }, { name: "clear", en: "Clear persisted memory data and artifacts" }, { name: "reset", en: "Alias for clear" }, { name: "enqueue", en: "Enqueue memory consolidation maintenance" }, { name: "rebuild", en: "Alias for enqueue" }, { name: "mm list", en: "List mental models on the active bank" }, { name: "mm show", en: "Show one mental model (id required)" }, { name: "mm refresh", en: "Refresh auto-refresh models bank-wide, or one model by id" }, { name: "mm history", en: "Diff the change history of a mental model" }, { name: "mm seed", en: "Create any built-in mental models that are missing" }, { name: "mm delete", en: "Delete a mental model from the bank (id required)" }, { name: "mm reload", en: "Re-pull the cached <mental_models> block" }] },
      { name: "add-dir", zh: "给会话添加额外工作目录(多根)", detail: "添加额外工作目录。为什么:跨仓改动(主仓 + lib 库)、monorepo 子包,agent 默认只认一个根;add-dir 给第二个目录同等读写权,不用切会话。注意:agent 获得对新目录的全部权限,确认目录里没有敏感内容;权限给多了记得 remove-dir 收回。", en: "Add a workspace directory to this session (multi-root)", usage: "<path>", how: "在对话框输入 /add-dir 回车,即发送到终端执行", examples: [{ sc: "主仓改接口,同步要改依赖的 lib 库", i: "/add-dir ~/code/lib-pay", o: "已添加工作目录:~/code/lib-pay(共 2 个根)", e: "agent 现在能同时读写两个仓,跨仓重构不用切会话。确认 lib-pay 里没敏感内容——权限是全量的;用完 remove-dir 收回。" }] },
      { name: "remove-dir", zh: "移除一个工作目录", detail: "移除工作目录。为什么:临时借的目录用完收回,最小权限原则;也让 dirs 列表保持干净。注意:主目录不可移;移除后未完成的跨目录任务会开始报路径错。", en: "Remove a workspace directory from this session", usage: "<path>", how: "在对话框输入 /remove-dir 回车,即发送到终端执行", examples: [{ sc: "跨仓任务完成,收回多余权限", i: "/remove-dir ~/code/lib-pay", o: "已移除工作目录:~/code/lib-pay", e: "回到单根,agent 碰不到 lib-pay 了。最小权限原则:借了就还,dirs 里只留该在的。" }] },
      { name: "dirs", zh: "列出本会话的工作目录", detail: "列出工作目录。为什么:多根会话里确认 agent 能碰哪些地方,安全审计第一步;也用于排查「它说找不到文件」是不是目录没加。注意:只读操作,随便看。", en: "List this session's workspace directories", how: "在对话框输入 /dirs 回车,即发送到终端执行", examples: [{ sc: "不确定 agent 现在能访问哪些目录", i: "/dirs", o: "1. ~/code/tmd-cli(主)\n2. ~/code/lib-pay", e: "安全自查一步:这之外它都不该碰。发现陌生目录立刻 remove-dir 并排查是谁加的。" }] },
    ] },
    { id: "branch", title: "历史与分支", desc: "对话也能开分支:走错路随时回头", commands: [
      { name: "branch", zh: "回退到之前某条消息,旧路径保留为分支", detail: "回退并保留分支。为什么:方案 B 走了五步发现不对,直接回退会丢掉这五步里的有效产出;branch 弹出消息选择器,选中某条即回退、旧路径存成分支,换方案 C 随时能回去抄作业。大胆试错的前提是有后悔药。注意:/branch 不带数字参数(带参会被当普通消息发出),回退点在选择器里挑;分支多了 /tree 会乱,定期收编或放弃。", en: "Rewind to a previous message, keeping the old path as a branch", how: "在对话框输入 /branch 回车,即发送到终端执行", examples: [{ sc: "方案 B(重构解析器)做了五步,越走越不对", i: "/branch", o: "弹出用户消息选择器(选中一条即回退并留分支)", e: "选中关键决策前那条即回退,五步成果躺在分支里,现在从该点试方案 C。回退点选「决策前」而非最后一条——决策前的状态才干净。" }, { sc: "两条分支都试完了,想回去看方案 B 的产出", i: "/tree", o: "main ▸ 决策点 ▸ 方案 C\n       └ 分支(方案 B)", e: "tree 里选中方案 B 分支即切回去看产出。收编结论(比如抄几段代码)后把废分支放弃,树要常修剪。" }] },
      { name: "fork", zh: "从之前某条消息分叉出新会话", detail: "从历史分叉新会话。为什么:同一个起点想跑两条完全独立的路线(两套方案并行对比),fork 复制现场各跑各的,互不干扰。注意:fork 是复制不是移动,原会话照旧;两条线都要人管,别fork太多顾不过来。", en: "Create a new fork from a previous message", how: "在对话框输入 /fork 回车,即发送到终端执行", examples: [{ sc: "一个需求想同时跑两套方案,各自独立推进", i: "/fork", o: "弹出消息选择器(选中一条即分叉新会话)", e: "选一条历史消息分叉,两条线完全独立并行推进。/fork 不带数字参数(带参会被当普通消息);原会话不受影响,复制不是移动。" }] },
      { name: "tree", zh: "浏览会话树并切换分支", detail: "会话树导航。为什么:branch/fork 玩起来后,线性列表表达不了树状历史;tree 画出全部分支,看清「哪条线在哪、谁包含谁」,切换分支的地图。注意:纯导航,不删不改;收编完的分支建议留个空 commit 标记。", en: "Navigate session tree (switch branches)", how: "在对话框输入 /tree 回车,即发送到终端执行", examples: [{ sc: "branch/fork 用多了,记不清哪条线是什么", i: "/tree", o: "main ▸ 12 ▸ 18\n       └ branch-1 ▸ 15\n         └ fork-scheme-b ▸ 3", e: "地图在手:看清结构再切换,避免迷路。废分支定期放弃,树越干净越敢试错。" }] },
    ] },
    { id: "share", title: "分享与协作", desc: "导出、分享、多人协作、语音与录屏", commands: [
      { name: "export", zh: "把会话导出为 HTML 文件", detail: "导出自包含 HTML。为什么:会话里有大量交接价值(决策过程、代码演进),但 jsonl 发出去没人能读;export 一键成排版好的 HTML,代码高亮齐全,发同事/贴工单/存档。注意:含敏感内容的会话导出前想清楚传播范围;文件在当前目录,别误提交。", en: "Export session to HTML file", usage: "[--themes] [path]", how: "在对话框输入 /export 回车,即发送到终端执行", examples: [{ sc: "这套重构的决策过程要同步给没参与的人", i: "/export", o: "Session exported to: omp-session-<会话id>.html", e: "单文件发出去即可读,代码高亮齐全(默认文件名带会话 id)。导出前想清楚内容敏感度——文件会离开你的机器;存档记得别误提交进仓库。" }] },
      { name: "share", zh: "生成加密链接分享会话(share server 或 secret gist)", detail: "加密链接分享。为什么:「你看一眼这个报错」这种场景,导 HTML 太重;share 生成端到端加密只读链接,对方点开即看。注意:链接 + 密钥即全部权限,泄露无法远程撤销内容本身;share 不承诺有效期,重要内容另用 /export 定向备份。", en: "Share session via an encrypted link (share server or secret gist)", how: "在对话框输入 /share 回车,即发送到终端执行", examples: [{ sc: "想让同事远程看一眼当前报错,不想导文件", i: "/share", o: "Share URL: https://my.omp.sh/s/<id>#<key>", e: "对方点开即读,端到端加密。链接即权限,外泄收不回内容——敏感会话改用 /export 定向发送;别指望链接自动过期。" }] },
      { name: "trace", zh: "在统计 Dashboard 里打开本会话的 trace", detail: "会话 trace 明细。为什么:「这轮为什么这么慢/这么贵」需要看每轮的请求 token、耗时、重试;trace 在本地 Dashboard 展开全过程,性能与成本排查的事实依据。注意:trace 数据不自动上报,纯本地;长会话数据量大,打开稍慢。", en: "Open this session's trace in the stats dashboard", how: "在对话框输入 /trace 回车,即发送到终端执行", examples: [{ sc: "这轮响应特别慢,想知道慢在哪", i: "/trace", o: "已在 Dashboard 打开本会话 trace(18 轮请求明细)", e: "逐轮看 token、耗时、重试分布:慢在供应商还是上下文过大,数据说话。纯本地数据,放心看。" }] },
      { name: "dump", zh: "复制会话记录到剪贴板(并在 /tmp 写 LLM 请求 JSON)", detail: "会话原文导出。为什么:拿会话去别处分析(贴 issue、喂给另一个工具)需要原始数据;dump 复制全文到剪贴板,同时在 /tmp 落完整 LLM 请求 JSON,方便程序化处理。注意:/tmp 的 JSON 含全部对话与代码,机器共享环境用完删。", en: "Copy session transcript to clipboard (and write LLM request JSON to tmp)", how: "在对话框输入 /dump 回车,即发送到终端执行", examples: [{ sc: "要把会话原样交给另一个工具分析", i: "/dump", o: "会话已复制到剪贴板;LLM 请求 JSON:/tmp/omp-dump-8f3e.json", e: "剪贴板是纯文本全文,/tmp 的 JSON 是结构化请求。共享机器用完删 /tmp 文件——里面是完整对话与代码。" }] },
      { name: "collab", zh: "经中继实时共享本会话", detail: "实时共享会话。为什么:结对/求助时对方看不到你终端;collab 把会话经中继共享出去,生成 join 链接与二维码,对方实时看、默认还能提示词操作。注意:对方能看到后续一切输入,敏感信息先想;只想给人看用 /collab view(只读);结束 /collab stop,别开着直播下班。", en: "Share this session live via a relay", usage: "[start|view|list|stop|status] [relayUrl]", how: "在对话框输入 /collab 回车,即发送到终端执行", examples: [{ sc: "同事远程求助,想让他实时看到我的会话", i: "/collab start", o: "共享已开启:omp join \"<relay 链接>\"(附二维码)", e: "对方用该链接 /join 即进入。默认链接持有者可读会话并向 agent 发提示词;只读分享用 /collab view。开始后你的一切输入对方可见——密钥先想;完事 /collab stop。" }], subs: [{ name: "view", en: "Share a read-only link (guests can watch, not prompt)" }, { name: "list", en: "List active local Collab hosts (no links; use `omp collab link`)" }, { name: "status", en: "Show link + participants" }, { name: "stop", en: "Stop sharing" }] },
      { name: "join", zh: "加入一个共享的 collab 会话", detail: "加入共享会话。为什么:拿到 join 链接后一条命令进入对方现场,权限由发起方控制(只读/可提示词)。注意:可提示词模式下你的操作会真实作用在对方环境,手别抖;加入先看清楚是哪个项目。", en: "Join a shared collab session", usage: "<link>", how: "在对话框输入 /join 回车,即发送到终端执行", examples: [{ sc: "收到同事发来的 join 链接,要进入他的现场", i: "/join <relay 链接>", o: "已加入共享会话", e: "实时看到对方会话流动。链接由 /collab start 给出(不是邀请码)。可提示词模式下你的操作真实作用于对方环境——先看清权限,手别抖。" }] },
      { name: "leave", zh: "离开当前 collab 会话", detail: "离开共享会话。为什么:协作完断开连接,停止接收对方现场;也避免自己误操作继续生效。注意:离开不影响对方会话本身。", en: "Leave the collab session", how: "在对话框输入 /leave 回车,即发送到终端执行", examples: [{ sc: "协作结束", i: "/leave", o: "已离开共享会话", e: "断开连接,对方那边不受影响。确认退出后自己这边的会话照常可用。" }] },
      { name: "hub", zh: "打开实时 Agent Hub", detail: "Agent Hub 总览大屏。为什么:多 agent 并行时(主会话 + 子任务 + tan),「现在到底有几个在跑、各自烧多少」需要一屏看清;hub 聚合本机全部运行中 agent。注意:以总览为主,精细配置在 /agents;纯本地视图。", en: "Open the live Agent Hub", how: "在对话框输入 /hub 回车,即发送到终端执行", examples: [{ sc: "开了主会话 + 2 个 tan,不知道现在总共在跑啥", i: "/hub", o: "Agent Hub:3 个 agent 运行中\n▸ main 修支付回调 · tan#1 翻译 · tan#2 基准测试", e: "一屏看清并行全貌与各自状态。只看不控——要改配置去 /agents;收工前瞄一眼,确认没有该停的。" }] },
      { name: "agents", zh: "打开 agents hub(每个子 agent 的模型/prewalk/advisor)", detail: "子 agent 管理台。为什么:子任务全用主模型又贵又慢;agents 给每个子 agent 单独配模型——跑腿用便宜的、拍板用贵的,成本结构优化在这里。也能给子 agent 配 prewalk/advisor。注意:子模型太弱会拖质量,关键路径别省;配置立即生效,跑着的任务不受影响。", en: "Open the agents hub (per-agent model, prewalk, and advisor)", how: "在对话框输入 /agents 回车,即发送到终端执行", examples: [{ sc: "子任务全用主模型,账单有点扛不住", i: "/agents", o: "子 agent 配置:scout → glm-4.6-flash · worker → 主模型", e: "把跑腿型子 agent(搜索、扫描)换成便宜模型,关键路径保留主模型——成本结构当场优化。跑着的任务不受影响,下个子任务生效。" }] },
      { name: "live", zh: "启动 Codex 实时语音模式", detail: "实时语音模式。为什么:走读代码、口头迭代场景,打字不如说话快;live 接通语音,你边说 agent 边干。注意:依赖 Codex 通道与麦克风权限;嘈杂环境识别率下降,重要改动结束后看 diff 确认。", en: "Start Codex-backed realtime voice mode", how: "在对话框输入 /live 回车,即发送到终端执行", examples: [{ sc: "想带同事口头走读一遍新模块", i: "/live", o: "实时语音已连接,按住空格说话", e: "说就行,agent 边听边操作。结束后照常看 diff 确认——语音迭代快,但改动签字权还在你手上。" }] },
      { name: "record", zh: "录制屏幕为可回放文件(omp play)", detail: "录屏为可回放文件。为什么:教学、复现偶现 bug、给同事演示操作路径,文字说不清;record 录下 omp 会话全过程,omp play 原样回放(包括你的输入节奏)。注意:录的内容含终端上一切信息,敏感先清屏;文件别传公开网盘。", en: "Start or stop recording this screen to a replayable file (omp play)", how: "在对话框输入 /record 回车,即发送到终端执行", examples: [{ sc: "要给新同事演示一套操作流程,文字讲不清", i: "/record", o: "录制中…(再输 /record 停止)", e: "全程录成可回放文件,omp play 原样回放(含输入节奏)。停止 = 再输一次 /record(它不接受 stop 参数)。录之前清屏,终端上的一切都会进去;文件含工作内容,别传公开网盘。" }] },
    ] },
    { id: "git", title: "Git 与安全", desc: "git 界面、worktree、安全扫描、SSH 主机", commands: [
      { name: "git", zh: "打开 git UI(分屏 diff、暂存、提交)", detail: "会话内 git UI。为什么:改完想看 diff/暂存/提交,切出去开 IDE 心流就断;git 分屏 diff + 暂存 + 提交一体化,在对话流里完成闭环。tmd-cli 的 Git 面板管系统级操作(历史、分支管理),两者互补。注意:提交前照常 diff 确认,agent 改的文件不一定全在暂存区。", en: "Open the git UI (split diff viewer, staging, commit composer)", usage: "[revision]", how: "在对话框输入 /git 回车,即发送到终端执行", examples: [{ sc: "agent 改完了,提交前想亲自过一遍 diff", i: "/git", o: "git UI 已打开:左 diff 右暂存,底部提交框", e: "分屏核对每处改动,可疑的当场问 agent;确认后直接在界面里暂存提交,不切 IDE。agent 改的文件不一定全在暂存区,以界面显示为准。" }] },
      { name: "wt", zh: "把本会话搬进新 worktree,连改动一起", detail: "搬进新 worktree。为什么:实验性大改动直接在工作区跑,会把未提交状态搅乱;wt 把当前会话连人带改动搬进独立 worktree,与主线物理隔离,搞砸整棵删掉,主线毫发无伤。注意:worktree 占磁盘(完整 checkout);结束记得清理,worktree 里提交的分支要手动合回。", en: "Move this session into a new worktree, changes included", usage: "[<branch>]", how: "在对话框输入 /wt 回车,即发送到终端执行", examples: [{ sc: "要试一个激进的缓存方案,不想搅乱当前工作区", i: "/wt", o: "已创建 worktree ../tmd-cli-wt-3,会话与改动已迁入", e: "实验在独立 worktree 里跑,主线工作区毫发无伤。搞砸了整棵删掉;worktree 里的提交要手动合回,结束记得清理目录与分支。" }] },
      { name: "security", zh: "安全扫描:规划、运行、导入与对比 OMP 原生安全扫描", detail: "原生安全扫描。为什么:依赖漏洞、硬编码密钥、危险调用,人肉审计靠运气;security 走 plan→scan→status→compare 流程,11 个子命令把安全检查工程化,结果可对比历史。注意:扫描器有误报,高危项人工确认再改;CI 里也建议挂一条。", en: "Plan, run, inspect, import, and compare OMP-native security scans", how: "在对话框输入 /security 回车,即发送到终端执行", examples: [{ sc: "发版前例行安全检查", i: "/security scan", o: "扫描完成:依赖 214(2 个已知 CVE)· 代码风险 12 项\n/security status 看详情", e: "高危项人工确认后修,误报拉白名单;compare 子命令对比上次扫描,新引入的风险一目了然。CI 建议同步挂一条。" }], subs: [{ name: "plan", en: "Create an immutable security scan plan" }, { name: "scan", en: "Start a planned or newly planned native scan" }, { name: "status", en: "Show native scan operation status" }, { name: "cancel", en: "Cancel a running native scan" }, { name: "scans", en: "List stored project security scans" }, { name: "show", en: "Render a scan or security:// resource" }, { name: "import", en: "Import SARIF or a Codex Security bundle" }, { name: "export", en: "Export a canonical bundle, SARIF, or report" }, { name: "validate", en: "Validate one finding with OMP-native tools" }, { name: "compare", en: "Compare finding lineage across two scans" }, { name: "disposition", en: "Set a finding disposition with rationale" }] },
      { name: "ssh", zh: "管理 SSH 主机(增/列/删)", detail: "管理 omp 的 SSH 主机。为什么:远程执行、远程任务需要主机清单,ssh add/list/remove/help 管理;tmd-cli 的 SSH 面板管连接本身,这里管 omp 会话内可用主机。注意:主机凭据配置要对齐 tmd-cli 侧,两边各存一份;连通性在实际连接时体现(无独立 test 子命令)。", en: "Manage SSH hosts (add, list, remove)", usage: "<subcommand>", how: "在对话框输入 /ssh 回车,即发送到终端执行", examples: [{ sc: "要把一个部署任务派到生产服务器", i: "/ssh list", o: "SSH 主机:2 台\n▸ ecs-prod (root@47.x.x.x)\n  home-nas", e: "确认目标主机在列,再派远程任务(连通性在实际连接时体现,无独立 test)。凭据与 tmd-cli SSH 面板各存一份,改密码两边都要改。" }], subs: [{ name: "add", en: "Add an SSH host", usage: "<name> --host <host> [--user <user>] [--port <port>] [--key <keyPath>] [--scope project|user]" }, { name: "list", en: "List all configured SSH hosts" }, { name: "remove", en: "Remove an SSH host", usage: "<name> [--scope project|user]" }, { name: "help", en: "Show help message" }] },
    ] },
    { id: "ext", title: "扩展与生态", desc: "插件、技能、MCP;omp 的能力边界由你决定", commands: [
      { name: "marketplace", zh: "管理市场源与已装插件", detail: "管理市场源与 marketplace 插件。为什么:官方源之外的插件要加源才能装;marketplace add/remove/list 管源与已装 marketplace 插件。注意:第三方源 = 第三方代码进你的会话,加源前确认信任;tmd-cli 扩展市场面板管的是 npm 生态扩展,不覆盖 marketplace 源清单。", en: "Manage marketplace plugin sources and installed plugins", how: "源与 marketplace 插件用 /marketplace 命令行管;tmd-cli 扩展市场面板管 npm 生态扩展", examples: [{ sc: "想装个社区源里的插件", i: "/marketplace add https://…", o: "市场源已添加:community(312 个插件)", e: "源与 marketplace 插件的浏览装卸走命令行 /marketplace;tmd-cli 扩展市场面板管 npm 生态扩展。第三方源 = 第三方代码进会话,只加信得过的源。" }], subs: [{ name: "add", en: "Add a marketplace source", usage: "<source>" }, { name: "remove", en: "Remove a marketplace source", usage: "<name>" }, { name: "update", en: "Update marketplace catalog(s)", usage: "[name]" }, { name: "list", en: "List configured marketplaces" }, { name: "discover", en: "Browse available plugins", usage: "[marketplace]" }, { name: "install", en: "Install a plugin (interactive browser if no args)", usage: "[--force] [name@marketplace]" }, { name: "uninstall", en: "Uninstall a plugin (selector if no args)", usage: "[name@marketplace]" }, { name: "installed", en: "List installed marketplace plugins" }, { name: "upgrade", en: "Upgrade outdated plugins", usage: "[name@marketplace]" }, { name: "help", en: "Show usage guide" }] },
      { name: "plugins", zh: "查看并管理已装插件", detail: "已装插件状态。为什么:排查「某功能怎么没生效」第一步看插件在不在、有没有被禁用;plugins 列出全部已装与启用态(disabled/shadowed 标记)。装卸去 tmd-cli 扩展市场面板,图形化更顺手。注意:/plugins 不显示加载报错(报错在启动诊断/日志);长期不用的禁用别硬扛。", en: "View and manage installed plugins", how: "cli-omp 扩展市场面板已装卸 omp 插件", examples: [{ sc: "某个功能突然不生效了", i: "/plugins", o: "已装插件:3 个\ngit-tools v1.2 · doctor v0.9 (disabled) · commit-lint v2.0", e: "doctor 标 (disabled)——功能失效根因找到。/plugins 只显示启用/禁用与遮蔽态,加载报错看启动诊断。先确认启用态,再 /reload-plugins 或到 tmd-cli 扩展市场面板启用。" }], subs: [{ name: "list", en: "List all installed plugins (npm + marketplace)" }, { name: "enable", en: "Enable a marketplace plugin", usage: "<name@marketplace>" }, { name: "disable", en: "Disable a marketplace plugin", usage: "<name@marketplace>" }] },
      { name: "reload-plugins", zh: "重载全部插件(skills/commands/hooks/tools/agents/MCP)", detail: "热重载全部插件。为什么:改了插件/技能/命令配置,重启会话太重;reload 秒级生效,插件开发必备。注意:热重载不保证有状态插件完美恢复,行为异常时重启一次兜底。", en: "Reload all plugins (skills, commands, hooks, tools, agents, MCP)", how: "在对话框输入 /reload-plugins 回车,即发送到终端执行", examples: [{ sc: "刚改了自己的插件配置,想立即生效", i: "/reload-plugins", o: "Plugins reloaded.", e: "秒级生效不用重启(输出只报已重载,不分类计数)。若重载后行为诡异(有状态插件没恢复干净),重启一次会话兜底。" }] },
      { name: "skills", zh: "从 skills.omp.sh 搜索/安装/更新技能", detail: "技能注册表搜索/安装/更新。为什么:技能 = 预制的提示词工程包(react 性能审查、commit 规范…),装完即用,不用自己从零写 prompt;skills.omp.sh 是官方注册表。注意:看清楚技能内容再装(它会进系统提示);装多了 token 略涨,不用的删。", en: "Search, install, and update skills from the skills.omp.sh registry", how: "在对话框输入 /skills 回车,即发送到终端执行", examples: [{ sc: "想让 agent 按 React 最佳实践审查代码,自己写 prompt 太长", i: "/skills search react", o: "react-perf · 1.2K weekly downloads · updated 3d ago\nreact-review · 800 weekly downloads · updated 1w ago", e: "看中哪个 /skills install 装上即用——技能是预制提示词工程包。装前看内容(它会进系统提示);下载量与更新时间是质量参考(注册表不下发评分)。" }], subs: [{ name: "search", en: "Search the skill registry", usage: "<query>" }, { name: "install", en: "Install registry skills", usage: "<@scope/name[@range]>… [--global]" }, { name: "installed", en: "List installed registry skills" }, { name: "update", en: "Update registry skills within their ranges", usage: "[@scope/name…] [--global]" }] },
      { name: "extensions", zh: "打开扩展控制中心 Dashboard", detail: "扩展控制中心。为什么:插件、技能、MCP、hooks 全算扩展,数量多了启用/禁用需要总控台;extensions 图形化一屏管理全部扩展的启停挂点。注意:全部扩展的启用/禁用总开关在这,比逐个 /plugins 排查快;面板不标扩展间冲突,行为异常靠逐个禁用二分定位。", en: "Open Extension Control Center dashboard", how: "在对话框输入 /extensions 回车,即发送到终端执行", examples: [{ sc: "装了新插件后某功能行为变了,怀疑冲突", i: "/extensions", o: "扩展控制中心:列出全部扩展的启用/禁用挂点", e: "逐个禁用二分定位行为变化,比翻配置快。全部扩展的启停总开关在这。" }] },
      { name: "mcp", zh: "管理 MCP 服务器(增/列/删/测)", detail: "MCP 服务器管理。为什么:MCP 是接外部工具的标准口(数据库、浏览器、内部系统),mcp 的 17 个子命令覆盖 add/list/remove/test/call 全生命周期。注意:add 时给的工具权限就是 agent 能拿到的权限,生产库只给只读账号;test 先验证再启用。", en: "Manage MCP servers (add, list, remove, test)", usage: "<subcommand>", how: "在对话框输入 /mcp 回车,即发送到终端执行", examples: [{ sc: "想让 agent 直接查 Postgres 数据库", i: "/mcp add postgres --url postgresql://…", o: "MCP postgres 已添加,4 个工具可用", e: "连接串里的权限就是 agent 的权限——生产库只给只读账号。add 用 --url(HTTP)或 -- 后接命令(stdio);完事 /mcp test 验证,工具列表在 /tools 核对。" }], subs: [{ name: "add", en: "Add a new MCP server", usage: "<name> [--scope project|user] [--url <url>] [-- <command...>]" }, { name: "list", en: "List all configured MCP servers" }, { name: "remove", en: "Remove an MCP server", usage: "<name> [--scope project|user]" }, { name: "test", en: "Test connection to a server", usage: "<name>" }, { name: "reauth", en: "Reauthorize OAuth for a server", usage: "<name>" }, { name: "unauth", en: "Remove OAuth auth from a server", usage: "<name>" }, { name: "enable", en: "Enable an MCP server", usage: "<name>" }, { name: "disable", en: "Disable an MCP server", usage: "<name>" }, { name: "smithery-search", en: "Search Smithery registry and deploy an MCP server", usage: "<keyword> [--scope project|user] [--limit <1-100>] [--semantic]" }, { name: "smithery-login", en: "Login to Smithery and cache API key" }, { name: "smithery-logout", en: "Remove cached Smithery API key" }, { name: "reconnect", en: "Reconnect to a specific MCP server", usage: "<name>" }, { name: "reload", en: "Force reload MCP runtime tools" }, { name: "resources", en: "List available resources from connected servers" }, { name: "prompts", en: "List available prompts from connected servers" }, { name: "notifications", en: "Show notification capabilities and subscriptions" }, { name: "help", en: "Show help message" }] },
      { name: "browser", zh: "切换浏览器 eval 前奏的无头/可见模式", detail: "切浏览器无头/可见。为什么:headless 省资源但你看不到 agent 在网页上干什么;切 visible 现场直播它的点击与填写,调试自动化脚本、演示、不放心它时用。注意:visible 会真弹窗口抢焦点;跑完切回 headless。", en: "Toggle browser eval-prelude headless vs visible mode", how: "在对话框输入 /browser 回车,即发送到终端执行", examples: [{ sc: "agent 写的自动化脚本一直点错按钮,想看现场", i: "/browser visible", o: "浏览器切到可见模式:agent 操作你看得见", e: "下一次浏览器任务真弹窗口,每一步点击可见——脚本问题当场定位。调试完切回 headless,visible 抢焦点且费资源。" }], subs: [{ name: "headless", en: "Switch to headless mode" }, { name: "visible", en: "Switch to visible mode" }] },
      { name: "computer", zh: "切换本会话的 computer-use 评估前奏", detail: "开关 computer-use 前奏。为什么:桌面自动化(操作 GUI 应用、截图点按钮)需要屏幕与键鼠能力,computer 开启后 agent 才有这双手。安全敏感:它能操作你桌面的一切。注意:用完即关;开启期间别离开工位,相当于把键盘借出去。", en: "Toggle the native computer-use eval prelude for this session", how: "在对话框输入 /computer 回车,即发送到终端执行", examples: [{ sc: "要让 agent 操作一个没有 CLI 的桌面应用", i: "/computer", o: "computer-use 前奏已开启(截图 + 键鼠控制)", e: "agent 获得屏幕截图与键鼠能力,可操作桌面 GUI。相当于把键盘借出去——开启期间人在旁边,用完立刻再输一次关闭。" }], subs: [{ name: "on", en: "Enable computer use for this session" }, { name: "off", en: "Disable computer use for this session" }, { name: "status", en: "Show computer use status" }] },
      { name: "skillful", zh: "是否把可用 skills 列入系统提示(仅本会话)", detail: "技能清单是否进系统提示。为什么:技能多了,清单本身占 token 还稀释注意力;skillful off 让本会话不带技能清单,省 token 或排查「它怎么不知道这技能」。注意:关掉后本会话技能不可被主动引用,记得回开。", en: "Toggle listing available skills in the system prompt (session only)", how: "在对话框输入 /skillful 回车,即发送到终端执行", examples: [{ sc: "技能装了 20 个,系统提示被清单撑大", i: "/skillful off", o: "本会话不再把技能清单放进系统提示(省 token)", e: "立省一笔固定开销,专注当前任务。代价是本会话技能不可被引用——纯干活的会话关,需要技能的会话记得回开。" }], subs: [{ name: "on", en: "List skills in the prompt for this session" }, { name: "off", en: "Omit the skills listing for this session" }, { name: "status", en: "Show skill listing status" }] },
    ] },
    { id: "misc", title: "界面与杂项", desc: "小工具合集", commands: [
      { name: "copy", zh: "从对话里挑文本或代码复制", detail: "从对话挑内容复制。为什么:长会话里找「刚才那段 SQL」滚屏手选很痛苦;copy 列出全部代码块与文本段,↑↓ 选择直接复制。注意:复制的是对话里出现过的,文件里的内容用编辑器更顺手。", en: "Pick text or code from the conversation to copy", how: "在对话框输入 /copy 回车,即发送到终端执行", examples: [{ sc: "半小时前那段建表 SQL 还要用,滚屏找不到", i: "/copy", o: "选择要复制的内容:\n▸ 代码块 x3 · 文本段 x7(↑↓ 选择)", e: "列表选中直接进剪贴板,不用翻屏手选。只覆盖对话里出现过的内容;文件里的东西用编辑器更快。" }] },
      { name: "open", zh: "在浏览器打开对话里最近/选中的链接", detail: "打开对话里的链接。为什么:agent 常贴文档链接,复制→开浏览器→粘贴三步;open 一条命令打开对话里最近出现的链接。注意:只取最后一条 URL、不弹列表;想挑历史链接用 /copy。", en: "Open the last link from the conversation in your browser (or pick one with /copy)", how: "在对话框输入 /open 回车,即发送到终端执行", examples: [{ sc: "agent 贴了个 Tauri 文档链接,想立刻看", i: "/open", o: "已在浏览器打开最近链接:tauri.app/develop/…", e: "直接打开最近一条 URL,省去复制粘贴三步。要挑更早的链接用 /copy(arg link/url 或选择器)。" }] },
      { name: "hotkeys", zh: "显示全部键盘快捷键", detail: "快捷键总表。为什么:omp 效率上限很大程度在快捷键(Alt+P 换模型、循环跳转、多光标),hotkeys 两页纸列全;每周扫一遍总有新收获。注意:tmd-cli 有自己的快捷键体系(⌘K 等),两套别混;在终端里以 omp 的为准。", en: "Show all keyboard shortcuts", how: "在对话框输入 /hotkeys 回车,即发送到终端执行", examples: [{ sc: "觉得手速到瓶颈了,想挖快捷键", i: "/hotkeys", o: "快捷键总表:Alt+P 换模型 · 循环跳转 · 多光标 …(两页)", e: "挑一两个融入肌肉记忆,一周后再扫。注意 tmd-cli 有自己的快捷键体系(⌘K 等),终端里以 omp 的为准,别混。" }] },
      { name: "changelog", zh: "查看更新日志", detail: "看更新内容。为什么:omp 迭代快,新功能、行为变更都在 changelog;升级后扫一眼,好东西常藏在 minor 版本里。注意:只列版本要点,细节看官方 release notes。", en: "Show changelog entries", how: "在对话框输入 /changelog 回车,即发送到终端执行", examples: [{ sc: "刚升级完 18.3.1,看有啥新东西", i: "/changelog", o: "v18.3.1:Goal 完成判定更严格;修复 /usage 5h 窗口显示…", e: "新功能常藏在 minor 版本里,扫一眼避免「一直手动干它早自动了」的事。细节看官方 release notes。" }], subs: [{ name: "full", en: "Show complete changelog" }, { name: "last", en: "Show the last N releases (default 1)", usage: "[N]" }] },
      { name: "tools", zh: "显示 agent 当前可见的工具", detail: "列出 agent 可见工具。为什么:「它怎么不能读文件」第一排查点:工具在不在、来源是什么(内建/MCP);tools 一眼看清能力边界,配置问题当场暴露。注意:工具在但不用,是模型选择问题,配合 /force 区分。", en: "Show tools currently visible to the agent", how: "在对话框输入 /tools 回车,即发送到终端执行", examples: [{ sc: "agent 说「没有工具能读数据库」,存疑", i: "/tools", o: "可见工具 12 个:read write edit bash … MCP: postgres(4)", e: "postgres 的 4 个工具明明在列——「没有工具」是模型误判。工具在不用是选择问题(/force 区分),工具不在才是配置问题(去 /mcp 查)。" }] },
      { name: "debug", zh: "打开调试工具选择器", detail: "调试工具选择器。为什么:插件异常、行为诡异时需要现场:最近日志、系统/终端状态、原始 SSE 流、报告打包、CPU 剖析等工具集中在 debug 菜单。注意:转储/打包内容含会话数据,外发前脱敏。", en: "Open debug tools selector", how: "在对话框输入 /debug 回车,即发送到终端执行", examples: [{ sc: "某插件一启用就异常,要看现场", i: "/debug", o: "调试菜单:artifacts / perf profile / dump bundle / memory / logs / system info / terminal state / raw SSE …", e: "挑对应项看现场(logs 看最近日志、raw SSE 看模型原始流)。转储含会话数据,外发前脱敏。" }] },
      { name: "omfg", zh: "从一条抱怨锻造成 TTSR 规则,根治反复出现的行为", detail: "把抱怨变成规则。为什么:「别再自动 commit」说了三遍它还犯——因为每次都是新会话;omfg 把抱怨锻造成 TTSR 规则写成规则文件(可选项目级 .omp/rules 或全局 ~/.omp/agent/rules),匹配的后续会话都受约束,一次根治。注意:规则要写成明确行为约束,情绪化表述效果差;项目级只覆盖该目录会话,全局才对所有会话生效。", en: "Forge a TTSR rule from a complaint to stop a recurring behavior", usage: "<complaint>", how: "在对话框输入 /omfg 回车,即发送到终端执行", examples: [{ sc: "它第三次没问我就直接 commit 了", i: "/omfg 提交前必须先给我看 diff 并征得同意", o: "已锻造规则:提交前必须征得确认(写入规则文件)", e: "规则写进规则文件(选全局则所有会话生效、选项目级只覆盖本目录),不用每个会话重申。写成明确行为约束(何时/必须/禁止)比情绪化抱怨有效;规则多了删规则文件或 /memory 清理。" }] },
    ] },
  ],
  lessons: OMP_ACADEMY_LESSONS,
};
