/**
 * omp 学堂入门课 —— 13 课覆盖全部 10 章,终章结业速查。
 * 内容与 academyCatalog.ts 同源纪律(见其头注);chapter 指向目录章节 id
 * (指南「去学」互链);demo 为终端打字演示序列。
 */
import type { AcademyCourse } from "@kernel/academy";

type Lesson = AcademyCourse["lessons"][number];

export const OMP_ACADEMY_LESSONS: Lesson[] = [
  { id: "welcome", title: "omp 是什么", sub: "3 分钟", goal: "搞懂 omp 和 tmd-cli 的关系,以及学堂四件套(入口/入门课/指南/斜杠抽屉)怎么配合。", points: ["omp 跑在 tmd-cli 的终端里:你发消息,它读项目、改文件、跑命令", "左上角「omp 学堂」是总入口:这门课、完整指南、速查表都在这", "对话框输入 <b>/</b> 随时唤出命令抽屉,学到哪查到哪", "这门课 13 课,每课 1-3 分钟,练完即会"], demo: [["你好", "你好!我是 omp,已读入项目 tmd-cli(214 个文件)。输入 / 查看全部命令,或跟着左侧入门课走。"]], practice: "/rename 我的第一次对话", practiceWhy: "热身:给当前会话起名,resume 列表里立刻能认出它。" },
  { id: "lifecycle", title: "会话:开始、恢复、翻篇", sub: "约 2 分钟", goal: "会话是你和 agent 的一段连续工作。学完这课你会:开新会话、找回旧会话、轻量翻篇。", chapter: "lifecycle", points: ["<b>/new</b> 换任务先开新会话,旧的不丢", "<b>/resume</b> 找回历史会话;tmd-cli 侧栏 omp 分组点一下等效", "<b>/clear</b> 同任务翻篇:<b>/new</b> 是换任务,<b>/clear</b> 是同一任务重新开始", "<b>/fresh</b> 连接卡死先试它,别急着清上下文"], demo: [["/new", "✓ New session started"], ["/session info", "会话 8f3e21 · 3 条消息 · 2.1K tokens"], ["/clear", "上下文已清空,会话与标题保留"]], practice: "/rename 修支付回调", practiceWhy: "给会话起个一眼能认的名字,一周后 /resume 不抓瞎。" },
  { id: "model", title: "模型与额度:花对每一分钱", sub: "约 2 分钟", goal: "会换模型、会看额度。模型决定智商与花费,这两个命令第一天就要会。", chapter: "model", points: ["<b>/model</b> 弹选择器切模型,下一条消息立即生效;composer 模型 pill 等效", "<b>/switch sonnet</b> 背熟 id 后直接切,最快", "<b>/usage</b> 随时看还剩多少额度;composer 额度 chip 读同一凭据", "<b>/fast</b> /<b>/slow</b> 快慢档:赶工开快档,跑批挂慢档"], demo: [["/model", "▸ GLM-4.6 (coding plan)\n  Claude Sonnet 4.5\nEnter 切换"], ["/usage", "本月 12.4M / 120M tokens(10%) · 限流正常"]], practice: "/model", practiceWhy: "打开选择器看一眼你有哪些模型,顺便记住 composer 的模型 pill。" },
  { id: "plan", title: "先想后做:Plan 模式", sub: "约 2 分钟", goal: "复杂任务先让 agent 出计划,你拍板再动手——返工最少的习惯。", chapter: "modes", points: ["<b>/plan</b> 开启后 agent 只读调研、产出计划,不写代码", "逐条确认计划后再执行,方向错了零损失", "<b>/plan-review</b> 执行到一半想回看原始计划", "小改动不用开:直接说「先说思路再改」也行"], demo: [["/plan", "Plan 模式已开启:下一轮只做调研与计划"], ["(发消息)帮我把死代码清一遍", "计划:1. 扫描引用 2. 列清单 3. 逐个确认删除 …"], ["/plan-review", "已重新打开计划评审"]], practice: "/plan", practiceWhy: "开着它发下一条任务,亲眼看 agent 先给计划不动手。" },
  { id: "auto", title: "自主模式:goal / loop / queue", sub: "约 3 分钟", goal: "让 agent 自己转起来:长期目标、循环重试、排队不打断。这是 omp 和「一问一答工具」的分水岭。", chapter: "modes", points: ["<b>/goal 把 flaky 测试修到全绿</b> 持续自主直到达成,完成条件要可判定", "<b>/loop</b> 下一条消息每轮结束自动重发,给 10m=总时限窗口,「盯到过为止」神器", "<b>/queue</b> agent 忙时排队插话,不打断当前工作", "<b>/pause</b> 紧急刹车全冻结(Esc/回车恢复);<b>/advisor on</b> 请第二个模型复核"], demo: [["/goal 把 flaky 测试修到全绿", "目标已设定 · 完成判定:pnpm test 连续 2 次全绿"], ["/queue 修完顺手补个单测", "已排队:这轮结束后自动发送"], ["/pause", "已冻结全部 agent(暂停画面,Esc 恢复)"]], practice: "/queue", practiceWhy: "趁 agent 忙时排一条消息,体会不打断的工作流。" },
  { id: "tasks", title: "盯进度:todo 与后台", sub: "约 2 分钟", goal: "大任务被拆成 todo,耗时活丢后台。学会看这两块,就不用盯屏等了。", chapter: "tasks", points: ["<b>/todo</b> 任务列表面板:进行中/待办/完成,11 个子命令", "<b>/jobs</b> 后台任务状态:子 agent、长命令跑完没有", "<b>/tan</b> 派后台 agent 干不相干的事,不占本会话上下文", "<b>/retry</b> 网络错/限流后重试上一轮,不用重打 prompt"], demo: [["/todo", "● 进行中 修复 flaky 测试(2/5)\n○ 待办 补回归测试\n✓ 完成 定位竞态根因"], ["/jobs", "后台:tan#1 README 翻译(运行 2m)"]], practice: "/todo", practiceWhy: "看看当前会话的任务列表长什么样。" },
  { id: "context", title: "上下文:管住钱也管住智商", sub: "约 3 分钟", goal: "上下文越长越贵、越迟钝。会看用量、会压缩、会交接,长任务不翻车。", chapter: "context", points: ["<b>/context</b> 看用量明细:工具结果通常占大头", "<b>/compact</b> 压缩成摘要;<b>/shake</b> 更保守,只丢重内容", "<b>/handoff</b> 总结成交接摘要原地压缩(不落文件),跨天接力必备", "<b>/btw</b> 题外话走小上下文,不污染主线"], demo: [["/context", "42.1K / 200K(21%)· 工具结果 21.4K 占一半"], ["/compact", "已压缩:67.3K → 18.9K"], ["/handoff", "Context handed off and compacted in place."]], practice: "/context", practiceWhy: "看看你现在的上下文花在哪了。" },
  { id: "branch", title: "分支:大胆试错,随时回头", sub: "约 2 分钟", goal: "对话可以像 git 一样开分支。有它,试错成本趋近于零。", chapter: "branch", points: ["<b>/branch</b> 弹选择器回退到某条消息,旧路径存为分支", "<b>/fork</b> 选一条历史消息分叉全新会话,两条路线并行", "<b>/tree</b> 会话树地图,分支间切换", "试错前不用备份:先 branch 再折腾"], demo: [["/branch", "弹出用户消息选择器(选中即回退并留分支)"], ["/tree", "main ▸ 12 ▸ 18\n       └ branch-1 ▸ 15"]], practice: "/tree", practiceWhy: "打开会话树,看看分支长什么样。" },
  { id: "share", title: "分享与协作", sub: "约 2 分钟", goal: "会话导出、加密分享、实时协作、语音与录屏——让成果出得了门。", chapter: "share", points: ["<b>/export</b> 导出自包含 HTML,发同事/贴工单", "<b>/share</b> 端到端加密只读链接(链接即权限),「看一眼这个报错」", "<b>/collab</b> 实时共享会话,结对/求助;<b>/hub</b> 全部 agent 大屏", "<b>/record</b> 录屏回放(omp play),教学与复现"], demo: [["/export", "Session exported to: omp-session-<会话id>.html"], ["/share", "Share URL: https://my.omp.sh/s/<id>#<key>"]], practice: "/export", practiceWhy: "把当前会话导出一个 HTML,发给朋友看看你的工作流。" },
  { id: "git", title: "Git 与安全:会话内闭环", sub: "约 2 分钟", goal: "git 操作不切出去,安全扫描定期做。tmd-cli 的 Git 面板管系统级操作,会话内用 omp 的。", chapter: "git", points: ["<b>/git</b> 分屏 diff + 暂存 + 提交,不离开会话", "<b>/wt</b> 实验性大改动搬进新 worktree,搞砸整棵删", "<b>/security scan</b> 依赖与代码风险体检", "<b>/ssh</b> 管理远程主机,tmd-cli SSH 面板管连接"], demo: [["/git", "git UI 已打开:左 diff 右暂存"], ["/security scan", "依赖 214 · 代码风险 12 项待查"]], practice: "/git", practiceWhy: "在会话里直接看一眼当前 diff。" },
  { id: "ext", title: "扩展:插件、技能、MCP", sub: "约 3 分钟", goal: "omp 的能力边界由你决定。装插件、装技能、接 MCP,三张口都认识一下。", chapter: "ext", points: ["<b>/plugins</b> 已装插件状态;装卸去 tmd-cli 扩展市场面板点两下", "<b>/skills search react</b> 技能注册表:预制的提示词工程包,装完即用", "<b>/mcp add</b> 接外部工具(数据库/浏览器/内部系统)", "改完配置 <b>/reload-plugins</b> 热重载"], demo: [["/skills search react", "react-perf · 1.2K weekly downloads · updated 3d ago"], ["/mcp list", "postgres(4 tools) · playwright(6 tools)"]], practice: "/plugins", practiceWhy: "看看你现在装了哪些插件(tmd-cli 扩展市场同源)。" },
  { id: "misc", title: "效率杂项:小命令大顺手", sub: "约 2 分钟", goal: "捡走最容易上手的五个小命令,今天就开始省时间。", chapter: "misc", points: ["<b>/copy</b> 从对话挑代码块复制,不用滚屏手选", "<b>/open</b> 打开对话里最近的链接", "<b>/hotkeys</b> 全部快捷键,每周扫一遍总有新收获", "<b>/omfg 别再自动 commit</b> 把抱怨锻成规则文件,根治重复烦扰"], demo: [["/copy", "选择要复制的内容:代码块 x3 · 文本段 x7"], ["/omfg 别再不问我就自动 commit", "已锻造规则:提交前必须征得确认(写入规则文件)"]], practice: "/hotkeys", practiceWhy: "过一遍快捷键总表,挑一个明天就开始用。" },
  { id: "graduation", title: "结业:速查表与下一步", sub: "1 分钟", goal: "全部 10 章过完。这张速查表覆盖每章最常用命令,完整版在「omp 指南」tab(82 条全量 + 搜索 + 示例)。", points: [], cheat: true },
];
