/**
 * claude 学堂入门课 —— 9 课覆盖全部 7 章,首课欢迎/末课结业速查。
 * 内容与 academyCatalog.ts 同源纪律(见其头注);chapter 指向目录章节 id。
 */
import type { AcademyCourse } from "@kernel/academy";

type Lesson = AcademyCourse["lessons"][number];

export const CLAUDE_ACADEMY_LESSONS: Lesson[] = [
  { id: "welcome", title: "claude 是什么", sub: "1 分钟", goal: "claude(Claude Code)是跑在终端里的编程 agent:你用自然语言下指令,它读代码、改文件、跑命令。学完这课你会发出第一条指令。", points: ["直接打字描述任务,回车发送——不需要任何命令也能干活", "斜杠 <b>/</b> 开头的是命令,负责管理会话、上下文、模型、权限这些「工具箱」本身", "本学堂 7 章 40 条命令;先混个脸熟,用到了再回来查"], demo: [["你好,帮我看看这个仓库的结构", "agent 开始读目录并给出概览(直接对话即可,无需命令)"]], practice: "/rename 我的第一次对话", practiceWhy: "给会话起个一眼能认的名字,一周后 /resume 不抓瞎。" },
  { id: "sessions", title: "会话:开始、找回与命名", sub: "约 2 分钟", goal: "会话是你和 agent 的连续工作现场。学完这课你会:开新会话、找回旧的、命名、一行摘要。", chapter: "sessions", points: ["<b>/clear</b> 换任务先翻篇,旧会话留盘可恢复(别名 reset/new)", "<b>/resume 搜索词</b> 找回历史会话;侧栏 claude 分组点一下等效", "<b>/rename</b> 起名趁早,一周后不抓瞎", "<b>/recap</b> 一行摘要,汇报与交接的起点"], demo: [["/clear 支付重构", "新会话已开始,旧会话留盘"], ["/resume 解析器", "弹出会话选择器(按搜索词过滤)"], ["/recap", "输出一行当前进展摘要"]], practice: "/clear", practiceWhy: "体会「换任务先翻篇」:旧会话不会丢,新现场立刻干净。" },
  { id: "context", title: "上下文与记忆:续命术", sub: "约 3 分钟", goal: "上下文是弹药:会看余量、会压缩、会管 CLAUDE.md——长任务跑不跑得动全在这。", chapter: "context", points: ["<b>/context</b> 彩色网格看谁在吃上下文空间", "<b>/compact 保留指示</b> 上下文见长就压缩;关键约束写进指示才保得住", "<b>/autocompact</b> 设自动压缩水位,auto 或具体 token 数", "<b>/init</b> 新项目先生成 CLAUDE.md;<b>/memory</b> 维护项目记忆"], demo: [["/context", "彩色网格显示各部分占用与剩余"], ["/compact 保留接口签名与文件清单", "历史压成摘要,余量回升"]], practice: "/context", practiceWhy: "看一眼当前会话谁在吃上下文,心里有数才好做长任务。" },
  { id: "model", title: "模型、强度与账号", sub: "约 2 分钟", goal: "会切模型、会调思考强度、会看用量与账号状态——智商、花费、连通三天前就该会。", chapter: "model", points: ["<b>/model</b> 切模型:硬骨头用 Opus,日常用 Sonnet;只影响本会话", "<b>/effort</b> 思考强度档位:批量小活调低提速,架构决策调高", "<b>/usage</b>(别名 cost)看花费与限额;<b>/status</b> 排查第一站", "<b>/login</b>/<b>/logout</b> 账号进出;订阅走 OAuth"], demo: [["/model", "弹出模型选择器(回车切换)"], ["/usage", "显示会话花费、套餐用量与限额"], ["/status", "版本 · 模型 · 账号 · API 连通 · 工具状态"]], practice: "/model", practiceWhy: "打开选择器看看你有哪些模型,简单活记得切回性价比档。" },
  { id: "settings", title: "配置与终端体验", sub: "约 2 分钟", goal: "把 claude 调成自己的:设置、主题、输出风格、状态栏、换行键位与快捷键。", chapter: "settings", points: ["<b>/config</b> 设置总入口;key=value 可直改单项", "<b>/theme</b> 配色对齐终端背景;<b>/output-style</b> 切回复风格", "<b>/statusline</b> 底部常驻模型/分支/余量", "<b>/terminal-setup</b> 装 Shift+Enter 换行键位,多行输入必修课", "<b>/keybindings</b> 键位冲突时改 keybindings.json"], demo: [["/theme", "弹出主题选择(即时预览)"], ["/terminal-setup", "检测终端并安装对应键位方案"]], practice: "/theme", practiceWhy: "顺手换个舒服的主题,顺眼的界面用得更久。" },
  { id: "safety", title: "权限、计划与安全", sub: "约 3 分钟", goal: "信任边界上的命令:放行规则、先谋后动的计划模式、安全审查与健康体检。", chapter: "safety", points: ["<b>/permissions</b>(别名 allowed-tools)画信任边界:读类放行,写操作留人工确认", "<b>/plan</b> 大改动先出方案等拍板,批准才动手", "<b>/security-review</b> 提交前对分支改动过一遍安全关", "<b>/doctor</b>(别名 checkup)行为诡异时的第一步体检"], demo: [["/permissions", "打开权限规则管理界面"], ["/plan 先出迁移方案", "进入计划模式,方案等你批准"]], practice: "/permissions", practiceWhy: "把你天天用的测试命令加进 allow 规则,体验「先紧后松」。" },
  { id: "extensions", title: "扩展与集成", sub: "约 2 分钟", goal: "MCP、hooks、插件、技能——claude 的能力边界由这组命令决定。", chapter: "extensions", points: ["<b>/mcp</b> 外部工具的连接面板,断连先 reconnect", "<b>/hooks</b> 查看事件钩子配置(在 settings.json 里配)", "<b>/plugin</b>(别名 marketplace)装插件,一个顶四件但先看来源", "<b>/skills</b> 列技能,调用直接 /技能名", "<b>/reload-plugins</b>/<b>/reload-skills</b> 会话内热更,调试必备"], demo: [["/mcp", "显示各 MCP 服务器连接状态"], ["/plugin", "打开插件市场"], ["/skills", "列出全部可用技能"]], practice: "/mcp", practiceWhy: "看看当前接了哪些 MCP 服务器,把不用的 disable 掉省上下文。" },
  { id: "workspace", title: "工作区与成果输出", sub: "约 2 分钟", goal: "跨仓库协作与把成果带出门:追加目录、导出会话、一键复制。", chapter: "workspace", points: ["<b>/add-dir</b> 挂第二个仓库进会话,跨仓库改动一次完成", "<b>/cd</b> 搬家(单目录);add-dir 是加地产(多目录)", "<b>/export 文件名</b> 导出完整会话记录;敏感信息先掂量", "<b>/copy</b>(可带 N 取倒数第 N 条)最近回复进剪贴板", "<b>/help</b> 每周扫一遍,新命令自然浮出来"], demo: [["/add-dir ../my-api", "新目录已加入工作区"], ["/copy", "Copied to clipboard"]], practice: "/help", practiceWhy: "过一遍 help 总表,对照本学堂看哪些命令已经眼熟了。" },
  { id: "graduation", title: "结业:速查表与下一步", sub: "1 分钟", goal: "全部章节过完。这张卡是每章最常用命令;完整指南在左栏学堂菜单里随时可查。", points: [], cheat: true },
];
